table customers
	lineageTag: 6988b1e5-2768-4038-bf06-31c59ecb675c

	column customerId
		dataType: string
		lineageTag: 55d540e5-6678-42f4-b261-35d6f9885b1b
		summarizeBy: none
		sourceColumn: customerId

		annotation SummarizationSetBy = Automatic

	column customerType
		dataType: string
		lineageTag: b5223982-08a0-4a9a-ae49-1be520768c2e
		summarizeBy: none
		sourceColumn: customerType

		annotation SummarizationSetBy = Automatic

	column firstName
		dataType: string
		lineageTag: 06dec22c-986d-4792-b8aa-d992cc659450
		summarizeBy: none
		sourceColumn: firstName

		annotation SummarizationSetBy = Automatic

	column lastName
		dataType: string
		lineageTag: f08b404c-7942-4432-8af5-34b0787faf1e
		summarizeBy: none
		sourceColumn: lastName

		annotation SummarizationSetBy = Automatic

	column companyName
		dataType: string
		lineageTag: d870a81b-b572-4dbd-862d-3df6226b2ceb
		summarizeBy: none
		sourceColumn: companyName

		annotation SummarizationSetBy = Automatic

	column fullName
		dataType: string
		lineageTag: 6c49beb5-dcc2-4cfc-aa83-e046972c3fc6
		summarizeBy: none
		sourceColumn: fullName

		annotation SummarizationSetBy = Automatic

	column culture
		dataType: string
		lineageTag: 2a3c7e36-255c-4c10-8249-0933c216dc2f
		summarizeBy: none
		sourceColumn: culture

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 6a39e6b5-7407-4689-b5be-3648a13ff727
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: int64
		formatString: 0
		lineageTag: c10a4c3d-98a8-4f6f-b42c-b363b61ebdff
		summarizeBy: sum
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: eb3c956b-3790-4c14-a68b-d189be92487e
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 1813b7fc-3cf8-4fb3-b91f-fa9bba823d50
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 460cfa00-0a38-49bb-8fae-6bd1a779212e
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: d4ea8ab3-fc8c-49c8-867f-980c63861f4e
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column postalCode
		dataType: int64
		formatString: 0
		lineageTag: 76b09922-45eb-48e2-9be3-4caa4d3353d3
		summarizeBy: count
		sourceColumn: postalCode

		annotation SummarizationSetBy = Automatic

	column registrationDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: a46d68eb-f8f1-4868-8170-7c5e42ced5fe
		summarizeBy: none
		sourceColumn: registrationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column loyaltyPoints
		dataType: int64
		formatString: 0
		lineageTag: 64678f88-b82a-43cc-836c-242918ffbbf0
		summarizeBy: sum
		sourceColumn: loyaltyPoints

		annotation SummarizationSetBy = Automatic

	column creditLimit
		dataType: int64
		formatString: 0
		lineageTag: 873d3aa5-525c-4670-8d0c-c3e0ae872aac
		summarizeBy: sum
		sourceColumn: creditLimit

		annotation SummarizationSetBy = Automatic

	column customerSegment
		dataType: string
		lineageTag: e12bb4f4-0d55-4a1b-88a5-067899dc75f2
		summarizeBy: none
		sourceColumn: customerSegment

		annotation SummarizationSetBy = Automatic

	column preferredContact
		dataType: string
		lineageTag: 11edfced-ca34-4d5b-8ee4-2dce4ff98278
		summarizeBy: none
		sourceColumn: preferredContact

		annotation SummarizationSetBy = Automatic

	column lifetimeValue
		dataType: int64
		formatString: 0
		lineageTag: c091429e-a1f3-4df2-8d15-f2e3d4f87472
		summarizeBy: sum
		sourceColumn: lifetimeValue

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: d0a9cac0-1539-40a2-88e6-cfded648f203
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column taxId
		dataType: string
		lineageTag: 07a24d22-3910-414d-808a-a4e9d6c5e332
		summarizeBy: none
		sourceColumn: taxId

		annotation SummarizationSetBy = Automatic

	partition customers = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "inventory_sales_report", [ReturnSingleDatabase=true]),
				    inventory_sales_report_customers = Source{[Schema="inventory_sales_report",Item="customers"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(inventory_sales_report_customers,"-","",Replacer.ReplaceText,{"phone"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"phone", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

