createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table sales
			lineageTag: 08c3d125-6ba5-4882-a435-8da1439ec7c0

			column orderId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 68e7f385-acbc-495f-8c0f-91af85cdeccd
				summarizeBy: none
				sourceColumn: orderId

				annotation SummarizationSetBy = Automatic

			column invoiceNumber
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: eb44fbf8-a554-4e1a-bd13-f516ca7f4b7d
				summarizeBy: none
				sourceColumn: invoiceNumber

				annotation SummarizationSetBy = Automatic

			column orderDate
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: 91e37551-d801-482e-a148-ca05893fab25
				summarizeBy: none
				sourceColumn: orderDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column orderTime
				dataType: dateTime
				formatString: Long Time
				sourceProviderType: time
				lineageTag: bc6afed4-84fd-415b-a4e2-ad9f33b6761c
				summarizeBy: none
				sourceColumn: orderTime

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Time

			column customerId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 8502aa9e-50f7-45bb-beb3-5265493c5c24
				summarizeBy: none
				sourceColumn: customerId

				annotation SummarizationSetBy = Automatic

			column customerName
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 3aad980b-c3e7-484c-8b83-223c60a3f78b
				summarizeBy: none
				sourceColumn: customerName

				annotation SummarizationSetBy = Automatic

			column customerType
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 3dbbb49c-7fbb-4721-b52c-8de764573f28
				summarizeBy: none
				sourceColumn: customerType

				annotation SummarizationSetBy = Automatic

			column customerCountry
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: acd1948f-5598-4752-b66f-b5805e5eb1cf
				summarizeBy: none
				sourceColumn: customerCountry

				annotation SummarizationSetBy = Automatic

			column customerCity
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: f6b93b50-b9e3-435e-90d9-a121c74d8d31
				summarizeBy: none
				sourceColumn: customerCity

				annotation SummarizationSetBy = Automatic

			column customerRegion
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: c5b01b1d-e18c-4f06-9764-1c33098cf11a
				summarizeBy: none
				sourceColumn: customerRegion

				annotation SummarizationSetBy = Automatic

			column salespersonId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: fd09a378-6e50-4657-90a8-e1896637590e
				summarizeBy: none
				sourceColumn: salespersonId

				annotation SummarizationSetBy = Automatic

			column salespersonName
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 31b6adc9-d1b6-451e-a72c-3d11a236aa6e
				summarizeBy: none
				sourceColumn: salespersonName

				annotation SummarizationSetBy = Automatic

			column managerId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 237ea9e8-f085-4c29-b036-3c7c2af58df1
				summarizeBy: none
				sourceColumn: managerId

				annotation SummarizationSetBy = Automatic

			column managerName
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: fe50a336-eb3c-4c8f-8303-b0435a615b72
				summarizeBy: none
				sourceColumn: managerName

				annotation SummarizationSetBy = Automatic

			column salesRegion
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: e8b32a15-16cb-42b7-9011-0cbca6a22fc6
				summarizeBy: none
				sourceColumn: salesRegion

				annotation SummarizationSetBy = Automatic

			column salesCountry
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 76a29a95-7872-4ec8-b70c-be219ec0207e
				summarizeBy: none
				sourceColumn: salesCountry

				annotation SummarizationSetBy = Automatic

			column salesCity
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 62b3a327-a84b-4d12-bf2b-9f08d1a025df
				summarizeBy: none
				sourceColumn: salesCity

				annotation SummarizationSetBy = Automatic

			column orderStatus
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 3e9df1ea-b870-407a-8f91-614bf8c1cf4f
				summarizeBy: none
				sourceColumn: orderStatus

				annotation SummarizationSetBy = Automatic

			column paymentMethod
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: c2d4dc00-0c9f-4b07-8ee5-3eb4bae73c97
				summarizeBy: none
				sourceColumn: paymentMethod

				annotation SummarizationSetBy = Automatic

			column paymentStatus
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 9988ebf8-3e97-41bc-8237-662654c19bd4
				summarizeBy: none
				sourceColumn: paymentStatus

				annotation SummarizationSetBy = Automatic

			column paymentTerms
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 1525f1da-e34c-46a9-8b9c-0848d495d769
				summarizeBy: none
				sourceColumn: paymentTerms

				annotation SummarizationSetBy = Automatic

			column shippingMethod
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: e6eae025-0b73-40f3-8103-49b266e1a1a1
				summarizeBy: none
				sourceColumn: shippingMethod

				annotation SummarizationSetBy = Automatic

			column shippingCity
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 57a6a85b-0edf-4747-a077-fb0cb87a74ab
				summarizeBy: none
				sourceColumn: shippingCity

				annotation SummarizationSetBy = Automatic

			column shippingCountry
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 0ebb2a94-12a4-4ae6-9907-fe29ff7a9746
				summarizeBy: none
				sourceColumn: shippingCountry

				annotation SummarizationSetBy = Automatic

			column billingCity
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 038e2e11-4237-46c4-a2e1-cbfb10a2d395
				summarizeBy: none
				sourceColumn: billingCity

				annotation SummarizationSetBy = Automatic

			column billingCountry
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: ce211375-c7f4-487f-a5e0-78cd77e15c37
				summarizeBy: none
				sourceColumn: billingCountry

				annotation SummarizationSetBy = Automatic

			column itemCount
				dataType: int64
				isNullable: false
				formatString: 0
				sourceProviderType: tinyint
				lineageTag: 461ce916-9632-4044-9f8e-15464011ea08
				summarizeBy: sum
				sourceColumn: itemCount

				annotation SummarizationSetBy = Automatic

			column totalQuantity
				dataType: int64
				isNullable: false
				formatString: 0
				sourceProviderType: tinyint
				lineageTag: 2d49ae1b-3154-448a-9041-8993d6d303ee
				summarizeBy: sum
				sourceColumn: totalQuantity

				annotation SummarizationSetBy = Automatic

			column subtotal
				dataType: double
				isNullable: false
				formatString: #,0
				sourceProviderType: float
				lineageTag: d580bb11-227d-4510-ad08-11476f9c60c1
				summarizeBy: sum
				sourceColumn: subtotal

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isDecimal":true}

			column taxAmount
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: 2e4db3b0-8362-4d32-b5af-7e8901c7ce85
				summarizeBy: sum
				sourceColumn: taxAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column shippingCost
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: e397b277-42db-4aa2-961b-74716250dc09
				summarizeBy: sum
				sourceColumn: shippingCost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column totalAmount
				dataType: double
				isNullable: false
				formatString: #,0
				sourceProviderType: float
				lineageTag: e0e55e2c-bf18-454a-aa56-221258685ef8
				summarizeBy: sum
				sourceColumn: totalAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isDecimal":true}

			column totalCost
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: 7de518bf-46bc-4678-92ed-3ec56c002fd1
				summarizeBy: sum
				sourceColumn: totalCost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column profit
				dataType: double
				isNullable: false
				formatString: #,0
				sourceProviderType: float
				lineageTag: 2583f08f-2ed3-40bc-9f6d-3d9ee567e891
				summarizeBy: sum
				sourceColumn: profit

				annotation SummarizationSetBy = Automatic

			column profitMargin
				dataType: double
				isNullable: false
				formatString: #,0
				sourceProviderType: float
				lineageTag: 66c2145b-f207-4a41-930e-1ff30dac2cf2
				summarizeBy: sum
				sourceColumn: profitMargin

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isDecimal":true}

			column commission
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: cea2e3c9-1621-4805-b686-df949afaeedd
				summarizeBy: sum
				sourceColumn: commission

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column currency
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 35a6c5bf-bb5a-4bc5-835b-60629acb4f98
				summarizeBy: none
				sourceColumn: currency

				annotation SummarizationSetBy = Automatic

			column exchangeRate
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: 1221f578-a44b-4903-a509-f668b2c5c054
				summarizeBy: sum
				sourceColumn: exchangeRate

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column notes
				dataType: string
				sourceProviderType: nvarchar(50)
				lineageTag: 43f70339-0fd1-4e19-a456-f8118bdde40b
				summarizeBy: none
				sourceColumn: notes

				annotation SummarizationSetBy = Automatic

			column shipDate
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: cf4cf517-a8c0-4ba9-8d92-51601fc2e23a
				summarizeBy: none
				sourceColumn: shipDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column estimatedDelivery
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: 91c6b5c8-f1d3-4ac9-9ab5-b56037655cfc
				summarizeBy: none
				sourceColumn: estimatedDelivery

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column actualDelivery
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: aae8801d-75a0-4978-bdd7-8ca9984ac611
				summarizeBy: none
				sourceColumn: actualDelivery

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column carrier
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 0833371d-68e2-4db3-b4d9-8506febde1e4
				summarizeBy: none
				sourceColumn: carrier

				annotation SummarizationSetBy = Automatic

			column returnReason
				dataType: string
				sourceProviderType: nvarchar(50)
				lineageTag: ec4ccb3c-7a74-4747-8f15-1ab1bbc89328
				summarizeBy: none
				sourceColumn: returnReason

				annotation SummarizationSetBy = Automatic

			column source
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 92e68846-a7a2-4f2d-b003-37c8ea30a6c2
				summarizeBy: none
				sourceColumn: source

				annotation SummarizationSetBy = Automatic

			column channel
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 3b0c841c-ea28-44c0-ac3a-9491b0bce52c
				summarizeBy: none
				sourceColumn: channel

				annotation SummarizationSetBy = Automatic

			column shippingAddress
				dataType: string
				sourceProviderType: nvarchar(50)
				lineageTag: 50709a44-978d-40b2-9d8d-0436782e71a5
				summarizeBy: none
				sourceColumn: shippingAddress

				annotation SummarizationSetBy = Automatic

			column billingAddress
				dataType: string
				sourceProviderType: nvarchar(50)
				lineageTag: 43e3795d-fa3b-49fe-918e-65c16a73739d
				summarizeBy: none
				sourceColumn: billingAddress

				annotation SummarizationSetBy = Automatic

			column returnRequested
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				sourceProviderType: bit
				lineageTag: 56330153-353e-456c-8008-b360cfc0ff38
				summarizeBy: none
				sourceColumn: returnRequested

				annotation SummarizationSetBy = Automatic

			column trackingNumber
				dataType: string
				sourceProviderType: nvarchar(50)
				lineageTag: 3ffc8d91-91bf-4582-a8a2-1a449e1651fb
				summarizeBy: none
				sourceColumn: trackingNumber

				annotation SummarizationSetBy = Automatic

			partition sales = m
				mode: dual
				source =
						let
						    Source = Sql.Database("RAFAEL", "inventory_sales_report"),
						    dbo_sales = Source{[Schema="dbo",Item="sales"]}[Data]
						in
						    dbo_sales

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table sales_items
			lineageTag: 5855d3cd-9ab8-4d9b-8e76-a8be7d7be837

			column lineItemId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 5693f137-21ea-4cff-ab5d-ed5e55265e0d
				summarizeBy: none
				sourceColumn: lineItemId

				annotation SummarizationSetBy = Automatic

			column orderId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: ffeaf025-2bcc-4110-b324-28e1e62c2ea5
				summarizeBy: none
				sourceColumn: orderId

				annotation SummarizationSetBy = Automatic

			column invoiceNumber
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 2bf09685-a69a-4acc-849b-8e88de94825f
				summarizeBy: none
				sourceColumn: invoiceNumber

				annotation SummarizationSetBy = Automatic

			column orderDate
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: 5df2e6f3-17e5-4def-9883-5f8b086c02a7
				summarizeBy: none
				sourceColumn: orderDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column customerId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 90ce3629-a14d-4e7b-b123-283b861c5036
				summarizeBy: none
				sourceColumn: customerId

				annotation SummarizationSetBy = Automatic

			column salespersonId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: b96133ad-29a4-49d7-97ad-217b5b676242
				summarizeBy: none
				sourceColumn: salespersonId

				annotation SummarizationSetBy = Automatic

			column productId
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 880c29b2-6836-47f2-abf5-d1bfba0c356f
				summarizeBy: none
				sourceColumn: productId

				annotation SummarizationSetBy = Automatic

			column sku
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 49d74081-1388-45f0-9add-8f2a489ac719
				summarizeBy: none
				sourceColumn: sku

				annotation SummarizationSetBy = Automatic

			column productName
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: c8b1d580-b208-457e-8faf-24198b34b8f2
				summarizeBy: none
				sourceColumn: productName

				annotation SummarizationSetBy = Automatic

			column category
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 5ccbd3a2-19fa-4de6-8e14-cd598667fb3e
				summarizeBy: none
				sourceColumn: category

				annotation SummarizationSetBy = Automatic

			column subcategory
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 5d1e0242-6829-48ef-9dd2-88ed4f746d7f
				summarizeBy: none
				sourceColumn: subcategory

				annotation SummarizationSetBy = Automatic

			column brand
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 1aa7f6ab-e8e0-422f-9a02-35c0e187d83a
				summarizeBy: none
				sourceColumn: brand

				annotation SummarizationSetBy = Automatic

			column quantity
				dataType: int64
				isNullable: false
				formatString: 0
				sourceProviderType: tinyint
				lineageTag: 6026791e-7261-4985-b325-0478d9bb0fc8
				summarizeBy: sum
				sourceColumn: quantity

				annotation SummarizationSetBy = Automatic

			column unitPrice
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: de3b8af5-0889-40c3-a895-dc866f816c50
				summarizeBy: sum
				sourceColumn: unitPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column costPrice
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: e5a82d08-4ff5-4666-8c84-20deae8dbe4c
				summarizeBy: sum
				sourceColumn: costPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column discountPercent
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: f99a4754-861c-455b-a72d-9d0604abf14b
				summarizeBy: sum
				sourceColumn: discountPercent

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column discountAmount
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: 3e536896-87c3-461e-a200-ae8905913758
				summarizeBy: sum
				sourceColumn: discountAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column lineTotal
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: 18afc3a0-d22b-47ea-9968-29610adef819
				summarizeBy: sum
				sourceColumn: lineTotal

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column taxAmount
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: e9e139cc-0bcc-4420-b141-68d9a9ca948f
				summarizeBy: sum
				sourceColumn: taxAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column warehouse
				dataType: string
				isNullable: false
				sourceProviderType: nvarchar(50)
				lineageTag: 71824a53-9429-4d11-b478-c913628bb533
				summarizeBy: none
				sourceColumn: warehouse

				annotation SummarizationSetBy = Automatic

			column margin
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: 18127c34-c708-4805-8619-d09f46393384
				summarizeBy: sum
				sourceColumn: margin

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column marginPercent
				dataType: double
				isNullable: false
				sourceProviderType: float
				lineageTag: fa239bfe-ca1d-4548-86f7-bec00db83d14
				summarizeBy: sum
				sourceColumn: marginPercent

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column taxRate
				dataType: double
				sourceProviderType: decimal(3, 2)
				lineageTag: 6a7f5ed3-b9f8-43a5-95ae-245eaec267ef
				summarizeBy: sum
				sourceColumn: taxRate

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Total Revenue (lineTotal & taxAmount)' =
					
					sales_items[lineTotal] + sales_items[taxAmount]
				formatString: \$#,0;(\$#,0);\$#,0
				lineageTag: 4e1ceeda-bec0-4965-8069-0ce783125271
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			column barcode
				dataType: int64
				isNullable: false
				formatString: 0
				sourceProviderType: bigint
				lineageTag: 51d6a3a3-dd55-46bc-abb0-4cf4b540a2a5
				summarizeBy: sum
				sourceColumn: barcode

				annotation SummarizationSetBy = Automatic

			partition sales_items = m
				mode: dual
				source =
						let
						    Source = Sql.Database("RAFAEL", "inventory_sales_report"),
						    dbo_sales_items = Source{[Schema="dbo",Item="sales_items"]}[Data]
						in
						    dbo_sales_items

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table products
			lineageTag: 3d2fbbb7-0333-4405-856b-69b5e89d5348

			column productId
				dataType: string
				lineageTag: d7f9801e-ca9a-4b0b-a3b5-a2eacd7f27e2
				summarizeBy: none
				sourceColumn: productId

				annotation SummarizationSetBy = Automatic

			column sku
				dataType: string
				lineageTag: 1f97e93e-2990-4f5b-8ba1-c0b671dba853
				summarizeBy: none
				sourceColumn: sku

				annotation SummarizationSetBy = Automatic

			column barcode
				dataType: int64
				formatString: 0
				lineageTag: dc86ddcf-e8b2-43e5-a609-20326eb047ec
				summarizeBy: none
				sourceColumn: barcode

				annotation SummarizationSetBy = Automatic

			column productName
				dataType: string
				lineageTag: 368ee3db-ee19-475e-b11a-7fb8e9c091f9
				summarizeBy: none
				sourceColumn: productName

				annotation SummarizationSetBy = Automatic

			column description
				dataType: string
				lineageTag: 974cb4e9-9c07-459f-8c6d-464c10b16d47
				summarizeBy: none
				sourceColumn: description

				annotation SummarizationSetBy = Automatic

			column category
				dataType: string
				lineageTag: 257b7418-484b-405c-b9f2-c7ea5f5b284d
				summarizeBy: none
				sourceColumn: category

				annotation SummarizationSetBy = Automatic

			column subcategory
				dataType: string
				lineageTag: be60e097-3f8a-40a9-afd7-fce9cdc850a5
				summarizeBy: none
				sourceColumn: subcategory

				annotation SummarizationSetBy = Automatic

			column brand
				dataType: string
				lineageTag: 4b7b48dd-05d1-4a70-b397-68d4a931772c
				summarizeBy: none
				sourceColumn: brand

				annotation SummarizationSetBy = Automatic

			column manufacturer
				dataType: string
				lineageTag: dcc5e363-16dd-47aa-b1da-227e8adecc2b
				summarizeBy: none
				sourceColumn: manufacturer

				annotation SummarizationSetBy = Automatic

			column unitPrice
				dataType: double
				lineageTag: 487908b9-89de-441f-a5c2-e3574f7b138a
				summarizeBy: none
				sourceColumn: unitPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column costPrice
				dataType: double
				lineageTag: 4fca837a-d5cc-4cbd-b661-536e4572910f
				summarizeBy: none
				sourceColumn: costPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column msrp
				dataType: double
				lineageTag: 7e70d8fc-0dbc-46a6-9e48-548e84e2763f
				summarizeBy: none
				sourceColumn: msrp

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column supplier
				dataType: string
				lineageTag: d544310b-d071-4d63-8eee-10984f249d6f
				summarizeBy: none
				sourceColumn: supplier

				annotation SummarizationSetBy = Automatic

			column supplierSku
				dataType: string
				lineageTag: 6ef385c8-e703-47a1-983c-0c594d404529
				summarizeBy: none
				sourceColumn: supplierSku

				annotation SummarizationSetBy = Automatic

			column weight
				dataType: double
				lineageTag: 07139838-abb8-4121-88b0-f28d40722b56
				summarizeBy: none
				sourceColumn: weight

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column weightUnit
				dataType: string
				lineageTag: a851f375-5d68-4128-9b26-ead7668c7dd6
				summarizeBy: none
				sourceColumn: weightUnit

				annotation SummarizationSetBy = Automatic

			column dimensions
				dataType: string
				lineageTag: 7a8d1415-596e-4ad7-8bfe-3486b75e218e
				summarizeBy: none
				sourceColumn: dimensions

				annotation SummarizationSetBy = Automatic

			column dimensionUnit
				dataType: string
				lineageTag: 77df2e4b-76a2-4be8-9de4-0dbb00ff8cc8
				summarizeBy: none
				sourceColumn: dimensionUnit

				annotation SummarizationSetBy = Automatic

			column color
				dataType: string
				lineageTag: d3467b10-5813-435e-8af7-ae33ef29c90c
				summarizeBy: none
				sourceColumn: color

				annotation SummarizationSetBy = Automatic

			column size
				dataType: string
				lineageTag: 29d580e6-fea0-43a5-b93e-453a6d1936d5
				summarizeBy: none
				sourceColumn: size

				annotation SummarizationSetBy = Automatic

			column material
				dataType: string
				lineageTag: 43c2e6d0-26e1-4181-bb29-66a68e39a73e
				summarizeBy: none
				sourceColumn: material

				annotation SummarizationSetBy = Automatic

			column stockQuantity
				dataType: int64
				formatString: 0
				lineageTag: a57b0478-0327-4d2a-a2cb-95794ed341a8
				summarizeBy: none
				sourceColumn: stockQuantity

				annotation SummarizationSetBy = Automatic

			column reservedQuantity
				dataType: int64
				formatString: 0
				lineageTag: 044a3ba5-caa9-4dea-8acc-a192027eb1d6
				summarizeBy: none
				sourceColumn: reservedQuantity

				annotation SummarizationSetBy = Automatic

			column availableQuantity
				dataType: int64
				formatString: 0
				lineageTag: a3331f68-d0a9-4bbc-a28d-20757fec7982
				summarizeBy: none
				sourceColumn: availableQuantity

				annotation SummarizationSetBy = Automatic

			column reorderLevel
				dataType: int64
				formatString: 0
				lineageTag: d02a3d29-41b7-4c1e-986e-ed7286831b65
				summarizeBy: none
				sourceColumn: reorderLevel

				annotation SummarizationSetBy = Automatic

			column reorderQuantity
				dataType: int64
				formatString: 0
				lineageTag: 178ddda1-e559-41ad-8cc4-98c8989b1b92
				summarizeBy: none
				sourceColumn: reorderQuantity

				annotation SummarizationSetBy = Automatic

			column minOrderQuantity
				dataType: int64
				formatString: 0
				lineageTag: f6edc571-c8f7-41aa-95ed-73e4570c2de1
				summarizeBy: none
				sourceColumn: minOrderQuantity

				annotation SummarizationSetBy = Automatic

			column maxOrderQuantity
				dataType: int64
				formatString: 0
				lineageTag: 2c70d628-38e0-40aa-8edb-a7172529c4c2
				summarizeBy: none
				sourceColumn: maxOrderQuantity

				annotation SummarizationSetBy = Automatic

			column warehouse
				dataType: string
				lineageTag: a78daa66-bbd8-4242-9423-b8acf2a7ba50
				summarizeBy: none
				sourceColumn: warehouse

				annotation SummarizationSetBy = Automatic

			column aisle
				dataType: string
				lineageTag: e1ccde71-d0ae-42f0-8d85-cc2d69873a90
				summarizeBy: none
				sourceColumn: aisle

				annotation SummarizationSetBy = Automatic

			column shelf
				dataType: string
				lineageTag: dd73bd58-d971-4da5-85e3-0f7d46d80ade
				summarizeBy: none
				sourceColumn: shelf

				annotation SummarizationSetBy = Automatic

			column bin
				dataType: string
				lineageTag: 4c132f7a-c91d-46e2-99f0-55ab128b418d
				summarizeBy: none
				sourceColumn: bin

				annotation SummarizationSetBy = Automatic

			column warrantyMonths
				dataType: int64
				formatString: 0
				lineageTag: e4731c24-ac89-4b93-a91d-3418cbe7e1aa
				summarizeBy: none
				sourceColumn: warrantyMonths

				annotation SummarizationSetBy = Automatic

			column returnPolicy
				dataType: int64
				formatString: 0
				lineageTag: 1e228b55-de6c-4ab7-b430-a1dafd6a20cf
				summarizeBy: none
				sourceColumn: returnPolicy

				annotation SummarizationSetBy = Automatic

			column isActive
				dataType: string
				lineageTag: c9558aad-a8ce-41fc-be90-e1e3801cf38c
				summarizeBy: none
				sourceColumn: isActive

				annotation SummarizationSetBy = Automatic

			column isFeatured
				dataType: string
				lineageTag: 05534017-921b-40ce-ac09-5aa33da7fe94
				summarizeBy: none
				sourceColumn: isFeatured

				annotation SummarizationSetBy = Automatic

			column isOnSale
				dataType: string
				lineageTag: 079a443e-696f-482d-978b-8311c425b01b
				summarizeBy: none
				sourceColumn: isOnSale

				annotation SummarizationSetBy = Automatic

			column rating
				dataType: double
				lineageTag: cf9b1db3-29b6-4eea-86f5-9f0ea346be2f
				summarizeBy: none
				sourceColumn: rating

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column reviewCount
				dataType: int64
				formatString: 0
				lineageTag: 057102e5-b0d3-4065-8140-70c187687d5c
				summarizeBy: none
				sourceColumn: reviewCount

				annotation SummarizationSetBy = Automatic

			column tags
				dataType: string
				lineageTag: 6788820d-e93e-4652-8d22-ded1c2437c95
				summarizeBy: none
				sourceColumn: tags

				annotation SummarizationSetBy = Automatic

			partition products = m
				mode: import
				source =
						let
						    Source = MySQL.Database("localhost", "inventory_sales_report", [ReturnSingleDatabase=true]),
						    inventory_sales_report_products = Source{[Schema="inventory_sales_report",Item="products"]}[Data]
						in
						    inventory_sales_report_products

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table customers
			lineageTag: 6988b1e5-2768-4038-bf06-31c59ecb675c

			column customerId
				dataType: string
				lineageTag: 55d540e5-6678-42f4-b261-35d6f9885b1b
				summarizeBy: none
				sourceColumn: customerId

				annotation SummarizationSetBy = Automatic

			column customerType
				dataType: string
				lineageTag: b5223982-08a0-4a9a-ae49-1be520768c2e
				summarizeBy: none
				sourceColumn: customerType

				annotation SummarizationSetBy = Automatic

			column firstName
				dataType: string
				lineageTag: 06dec22c-986d-4792-b8aa-d992cc659450
				summarizeBy: none
				sourceColumn: firstName

				annotation SummarizationSetBy = Automatic

			column lastName
				dataType: string
				lineageTag: f08b404c-7942-4432-8af5-34b0787faf1e
				summarizeBy: none
				sourceColumn: lastName

				annotation SummarizationSetBy = Automatic

			column companyName
				dataType: string
				lineageTag: d870a81b-b572-4dbd-862d-3df6226b2ceb
				summarizeBy: none
				sourceColumn: companyName

				annotation SummarizationSetBy = Automatic

			column fullName
				dataType: string
				lineageTag: 6c49beb5-dcc2-4cfc-aa83-e046972c3fc6
				summarizeBy: none
				sourceColumn: fullName

				annotation SummarizationSetBy = Automatic

			column culture
				dataType: string
				lineageTag: 2a3c7e36-255c-4c10-8249-0933c216dc2f
				summarizeBy: none
				sourceColumn: culture

				annotation SummarizationSetBy = Automatic

			column email
				dataType: string
				lineageTag: 6a39e6b5-7407-4689-b5be-3648a13ff727
				summarizeBy: none
				sourceColumn: email

				annotation SummarizationSetBy = Automatic

			column phone
				dataType: int64
				formatString: 0
				lineageTag: c10a4c3d-98a8-4f6f-b42c-b363b61ebdff
				summarizeBy: sum
				sourceColumn: phone

				annotation SummarizationSetBy = Automatic

			column address
				dataType: string
				lineageTag: eb3c956b-3790-4c14-a68b-d189be92487e
				summarizeBy: none
				sourceColumn: address

				annotation SummarizationSetBy = Automatic

			column city
				dataType: string
				lineageTag: 1813b7fc-3cf8-4fb3-b91f-fa9bba823d50
				summarizeBy: none
				sourceColumn: city

				annotation SummarizationSetBy = Automatic

			column region
				dataType: string
				lineageTag: 460cfa00-0a38-49bb-8fae-6bd1a779212e
				summarizeBy: none
				sourceColumn: region

				annotation SummarizationSetBy = Automatic

			column country
				dataType: string
				lineageTag: d4ea8ab3-fc8c-49c8-867f-980c63861f4e
				summarizeBy: none
				sourceColumn: country

				annotation SummarizationSetBy = Automatic

			column postalCode
				dataType: int64
				formatString: 0
				lineageTag: 76b09922-45eb-48e2-9be3-4caa4d3353d3
				summarizeBy: count
				sourceColumn: postalCode

				annotation SummarizationSetBy = Automatic

			column registrationDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: a46d68eb-f8f1-4868-8170-7c5e42ced5fe
				summarizeBy: none
				sourceColumn: registrationDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column loyaltyPoints
				dataType: int64
				formatString: 0
				lineageTag: 64678f88-b82a-43cc-836c-242918ffbbf0
				summarizeBy: sum
				sourceColumn: loyaltyPoints

				annotation SummarizationSetBy = Automatic

			column creditLimit
				dataType: int64
				formatString: 0
				lineageTag: 873d3aa5-525c-4670-8d0c-c3e0ae872aac
				summarizeBy: sum
				sourceColumn: creditLimit

				annotation SummarizationSetBy = Automatic

			column customerSegment
				dataType: string
				lineageTag: e12bb4f4-0d55-4a1b-88a5-067899dc75f2
				summarizeBy: none
				sourceColumn: customerSegment

				annotation SummarizationSetBy = Automatic

			column preferredContact
				dataType: string
				lineageTag: 11edfced-ca34-4d5b-8ee4-2dce4ff98278
				summarizeBy: none
				sourceColumn: preferredContact

				annotation SummarizationSetBy = Automatic

			column lifetimeValue
				dataType: int64
				formatString: 0
				lineageTag: c091429e-a1f3-4df2-8d15-f2e3d4f87472
				summarizeBy: sum
				sourceColumn: lifetimeValue

				annotation SummarizationSetBy = Automatic

			column industry
				dataType: string
				lineageTag: d0a9cac0-1539-40a2-88e6-cfded648f203
				summarizeBy: none
				sourceColumn: industry

				annotation SummarizationSetBy = Automatic

			column taxId
				dataType: string
				lineageTag: 07a24d22-3910-414d-808a-a4e9d6c5e332
				summarizeBy: none
				sourceColumn: taxId

				annotation SummarizationSetBy = Automatic

			partition customers = m
				mode: import
				source =
						let
						    Source = MySQL.Database("localhost", "inventory_sales_report", [ReturnSingleDatabase=true]),
						    inventory_sales_report_customers = Source{[Schema="inventory_sales_report",Item="customers"]}[Data],
						    #"Replaced Value" = Table.ReplaceValue(inventory_sales_report_customers,"-","",Replacer.ReplaceText,{"phone"}),
						    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"phone", Int64.Type}})
						in
						    #"Changed Type"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table salespeople
			lineageTag: 8134b5dc-d077-433d-9ae8-093db8bba8b1

			column salespersonId
				dataType: string
				lineageTag: 1cd403e3-2a92-438c-a623-f3ea9f9647cb
				summarizeBy: none
				sourceColumn: salespersonId

				annotation SummarizationSetBy = Automatic

			column firstName
				dataType: string
				lineageTag: dd5dd7be-7830-4cbd-b85a-aac52778d0ea
				summarizeBy: none
				sourceColumn: firstName

				annotation SummarizationSetBy = Automatic

			column lastName
				dataType: string
				lineageTag: f6cea3f9-54b3-4d51-9837-77991d4878fe
				summarizeBy: none
				sourceColumn: lastName

				annotation SummarizationSetBy = Automatic

			column fullName
				dataType: string
				lineageTag: cffc720e-4b79-4dd0-8c30-1b66f751812f
				summarizeBy: none
				sourceColumn: fullName

				annotation SummarizationSetBy = Automatic

			column culture
				dataType: string
				lineageTag: 4e65a4f1-f5a7-4ece-8d83-989fcce2dad1
				summarizeBy: none
				sourceColumn: culture

				annotation SummarizationSetBy = Automatic

			column email
				dataType: string
				lineageTag: 9abd968f-4262-4c2c-8a5f-3a391d01f6e7
				summarizeBy: none
				sourceColumn: email

				annotation SummarizationSetBy = Automatic

			column phone
				dataType: string
				lineageTag: 9365e934-2c3a-460f-bcae-0155a5673d40
				summarizeBy: none
				sourceColumn: phone

				annotation SummarizationSetBy = Automatic

			column hireDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: 62c98c8d-7df4-41b5-8c46-0ae881a2a5e6
				summarizeBy: none
				sourceColumn: hireDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column region
				dataType: string
				lineageTag: 00aea9c2-cf0b-46bb-8d84-e7f8a24c4ffe
				summarizeBy: none
				sourceColumn: region

				annotation SummarizationSetBy = Automatic

			column country
				dataType: string
				lineageTag: 1da65e34-9b6e-4cd2-b28c-8f663057e80b
				summarizeBy: none
				sourceColumn: country

				annotation SummarizationSetBy = Automatic

			column city
				dataType: string
				lineageTag: 04431072-3cba-415a-897a-e113d974a7a9
				summarizeBy: none
				sourceColumn: city

				annotation SummarizationSetBy = Automatic

			column managerId
				dataType: string
				lineageTag: 161435a8-1fca-436d-b329-65794821c8b6
				summarizeBy: none
				sourceColumn: managerId

				annotation SummarizationSetBy = Automatic

			column managerName
				dataType: string
				lineageTag: b1cc3e56-2205-42dd-a8f5-338fbdef3db3
				summarizeBy: none
				sourceColumn: managerName

				annotation SummarizationSetBy = Automatic

			column commissionRate
				dataType: double
				lineageTag: 04de2330-549e-4499-8aa6-d497cc87a1cf
				summarizeBy: sum
				sourceColumn: commissionRate

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column performanceRating
				dataType: double
				lineageTag: 9449741a-11e2-4809-aa8d-0451f671c9be
				summarizeBy: sum
				sourceColumn: performanceRating

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column yearsExperience
				dataType: int64
				formatString: 0
				lineageTag: 215d3dd6-c7fc-444f-8679-d18bfd3c0bb9
				summarizeBy: sum
				sourceColumn: yearsExperience

				annotation SummarizationSetBy = Automatic

			column salesTarget
				dataType: int64
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: 7ba878b9-dd3c-4172-9eb1-6e7f0fbe8600
				summarizeBy: sum
				sourceColumn: salesTarget

				annotation SummarizationSetBy = Automatic

			column achievementPercent
				dataType: double
				lineageTag: 6c2c1596-7e1d-4b1b-8dac-e705306951c0
				summarizeBy: sum
				sourceColumn: achievementPercent

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column employmentStatus
				dataType: string
				lineageTag: c10b4656-56a3-43c3-8655-89e187020291
				summarizeBy: none
				sourceColumn: employmentStatus

				annotation SummarizationSetBy = Automatic

			column languagesSpoken
				dataType: string
				lineageTag: 1ceaa24e-cff6-4e75-83e1-2333db962f7f
				summarizeBy: none
				sourceColumn: languagesSpoken

				annotation SummarizationSetBy = Automatic

			column certifications
				dataType: string
				lineageTag: 9455584e-c939-4985-bff1-f705a3355bff
				summarizeBy: none
				sourceColumn: certifications

				annotation SummarizationSetBy = Automatic

			partition salespeople = m
				mode: import
				source =
						let
						    Source = Csv.Document(File.Contents("C:\Users\Rafael\Documents\GitHub\Big Inventory Data\salespeople.csv"),[Delimiter=",", Columns=22, Encoding=65001, QuoteStyle=QuoteStyle.None]),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"salespersonId", type text}, {"firstName", type text}, {"lastName", type text}, {"fullName", type text}, {"culture", type text}, {"email", type text}, {"phone", type text}, {"hireDate", type date}, {"region", type text}, {"country", type text}, {"city", type text}, {"territory", type text}, {"managerId", type text}, {"managerName", type text}, {"commissionRate", type number}, {"performanceRating", type number}, {"yearsExperience", Int64.Type}, {"salesTarget", Int64.Type}, {"achievementPercent", type number}, {"employmentStatus", type text}, {"languagesSpoken", type text}, {"certifications", type text}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"territory"})
						in
						    #"Removed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table managers
			lineageTag: 4d6d6354-4d1c-4552-931f-851678adfc96

			column managerId
				dataType: string
				lineageTag: 493eba66-97d5-4703-b053-45368d38ff26
				summarizeBy: none
				sourceColumn: managerId

				annotation SummarizationSetBy = Automatic

			column firstName
				dataType: string
				lineageTag: 0ea50127-f683-4a6c-a76d-66cf41201df5
				summarizeBy: none
				sourceColumn: firstName

				annotation SummarizationSetBy = Automatic

			column lastName
				dataType: string
				lineageTag: f5599787-7503-4dd2-9506-819c5af9aae7
				summarizeBy: none
				sourceColumn: lastName

				annotation SummarizationSetBy = Automatic

			column fullName
				dataType: string
				lineageTag: 55c06da8-96f3-4f09-ae1f-d8f9507f73ba
				summarizeBy: none
				sourceColumn: fullName

				annotation SummarizationSetBy = Automatic

			column culture
				dataType: string
				lineageTag: 457b03e8-ba41-41a5-ad70-2fbcbcbd892a
				summarizeBy: none
				sourceColumn: culture

				annotation SummarizationSetBy = Automatic

			column email
				dataType: string
				lineageTag: 520adcf0-4bad-4418-98cf-5d196bc3b1ec
				summarizeBy: none
				sourceColumn: email

				annotation SummarizationSetBy = Automatic

			column phone
				dataType: string
				lineageTag: 0af50021-8c22-4e7f-b272-10ae25c43072
				summarizeBy: none
				sourceColumn: phone

				annotation SummarizationSetBy = Automatic

			column region
				dataType: string
				lineageTag: 6679066d-7bdc-4c21-9d8c-4166f5e24c03
				summarizeBy: none
				sourceColumn: region

				annotation SummarizationSetBy = Automatic

			column country
				dataType: string
				lineageTag: bcc48d6f-8bc0-4f2a-9297-c7672cb8ae5c
				summarizeBy: none
				sourceColumn: country

				annotation SummarizationSetBy = Automatic

			column city
				dataType: string
				lineageTag: 83add417-370f-4806-a92c-979413e01bae
				summarizeBy: none
				sourceColumn: city

				annotation SummarizationSetBy = Automatic

			column hireDate
				dataType: dateTime
				formatString: Long Date
				lineageTag: 81a98e0b-ece9-40dd-abb4-e5ac4f546240
				summarizeBy: none
				sourceColumn: hireDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column department
				dataType: string
				lineageTag: 0a0b0137-76cf-4ed1-9936-5f47d5b91c99
				summarizeBy: none
				sourceColumn: department

				annotation SummarizationSetBy = Automatic

			column performanceRating
				dataType: double
				lineageTag: 7a0cf27c-6b0a-4f8c-8581-7f7e20f760c7
				summarizeBy: none
				sourceColumn: performanceRating

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column yearsExperience
				dataType: int64
				formatString: 0
				lineageTag: 13bd3a6a-8d0c-4e5f-b360-f12776571094
				summarizeBy: none
				sourceColumn: yearsExperience

				annotation SummarizationSetBy = Automatic

			column reportsTo
				dataType: string
				lineageTag: 8f171616-0b94-4293-a72e-451e05fb954f
				summarizeBy: none
				sourceColumn: reportsTo

				annotation SummarizationSetBy = Automatic

			partition managers = m
				mode:import
				source =
						let
						    Source = Csv.Document(File.Contents("C:\Users\Rafael\Documents\GitHub\Big Inventory Data\managers.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"managerId", type text}, {"firstName", type text}, {"lastName", type text}, {"fullName", type text}, {"culture", type text}, {"email", type text}, {"phone", type text}, {"region", type text}, {"country", type text}, {"city", type text}, {"hireDate", type date}, {"department", type text}, {"performanceRating", type number}, {"yearsExperience", Int64.Type}, {"reportsTo", type text}})
						in
						    #"Changed Type"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Calendar
			lineageTag: 16f968a2-e75f-4102-864e-722ba11ead14
			dataCategory: Time

			column Date
				isKey
				formatString: Short Date
				lineageTag: a18163b2-bced-4c36-8ebf-713f02c1e40a
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column 'Start Of Quarter' =
					
					STARTOFQUARTER('Calendar'[Date])
				formatString: Short Date
				lineageTag: 66970f33-3bbe-4940-94f4-c38a2b2b0834
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column 'Start Of Month' =
					
					STARTOFMONTH('Calendar'[Date])
				formatString: Short Date
				lineageTag: 05162084-db80-439f-8dbc-3472dc2fea6f
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column Quarter =
					
					QUARTER('Calendar'[Date])
				formatString: 0
				lineageTag: 25d76d45-da50-458d-9c07-6d6feed31812
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column Year =
					
					YEAR('Calendar'[Date])
				formatString: 0
				lineageTag: 7a231a34-d804-4578-954c-710527146ebc
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column Month =
					
					MONTH('Calendar'[Date])
				formatString: 0
				lineageTag: f8a4940f-528c-428e-a8e3-1e6250f18872
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column 'Quarter Name' =
					
					"Q" & QUARTER('Calendar'[Date])
				lineageTag: 93a4aa69-1125-491f-8b75-9d7929621504
				summarizeBy: none
				sortByColumn: Quarter

				annotation SummarizationSetBy = Automatic

			column Week =
					
					WEEKNUM('Calendar'[Date], 11)
				formatString: 0
				lineageTag: c0c888e0-1a91-4a4b-a915-d5a15156375a
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column Weekday =
					
					WEEKDAY('Calendar'[Date], 2)
				formatString: 0
				lineageTag: ac3d93b4-2ee4-4755-9410-d313fb3be249
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column 'Day Num' =
					
					DAY('Calendar'[Date])
				formatString: 0
				lineageTag: cb12a058-e5bb-4b79-8419-7626d816f730
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column 'Month Name' =
					
					FORMAT('Calendar'[Date], "mmm")
				lineageTag: de282000-68a7-4cce-a3bd-b8e7db0e22a3
				summarizeBy: none
				sortByColumn: Month

				annotation SummarizationSetBy = Automatic

			column 'Day Name' =
					
					FORMAT('Calendar'[Date], "ddd")
				lineageTag: 033c81af-3dcf-48c8-b17d-0aa32812387f
				summarizeBy: none
				sortByColumn: Weekday

				annotation SummarizationSetBy = Automatic

			partition Calendar = calculated
				mode: import
				source = ```
						
						    CALENDAR(
						        MIN(sales[orderDate]),
						        UTCTODAY()
						    )
						
						```

			annotation PBI_Id = ced4fd688052423fac933ba48d22adf3

		table 'All Measures'
			lineageTag: 7037c896-4ae6-4fe5-912b-cf6d122657e7

			measure 'Total Customers Till Date' =
					
					COALESCE (
					    CALCULATE (
					        DISTINCTCOUNT ( customers[customerId] ),
					        USERELATIONSHIP ( 'Calendar'[Date], customers[registrationDate] ),
					        FILTER ( ALL ( 'Calendar' ), 'Calendar'[Date] <= MAX ( 'Calendar'[Date] ) )
					    ),
					    0
					)
				formatString: #,0
				displayFolder: Customer Insights
				lineageTag: 74437511-2ac6-48d5-8aa3-7a3f113af833

			measure 'Total Revenue' =
					
					CALCULATE (
					    SUMX ( sales, sales[totalAmount] ),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					)
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: 97e20897-993a-4e26-989b-80b2720ddecc

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure 'MTD Revenue' = ```
					
					-- VAR MaxDate = MAX('Calendar'[Date])
					-- RETURN
					COALESCE (
					    CALCULATE ( [Total Revenue], 
					    DATESMTD ( 'Calendar'[Date] ),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					    ),0
					)
					```
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: 5ca5e467-4603-4e32-b7d3-6770e4dd8048

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure 'YTD Revenue' =
					
					COALESCE (
					    CALCULATE (
					        [Total Revenue],
					        DATESYTD ( 'Calendar'[Date] ),
					        USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					    ),
					    0
					)
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: 1616b274-687d-494c-ae5a-f773a7289faa

			measure 'Prev Month Revenue (PREVIOUSMONTH)' =
					
					CALCULATE ( [Total Revenue], PREVIOUSMONTH ( 'Calendar'[Date] ) )
				displayFolder: Revenue Measures
				lineageTag: 7f833eab-92cc-4737-81cb-6017b11e5cac

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Previous Month Revenue' =
					
					CALCULATE ( [Total Revenue], DATEADD ( 'Calendar'[Date], -1, MONTH ) )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: b7fee67e-6199-4296-8876-39bffe711991

			measure 'Previous Month Revenue (From MTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousMonthEnd =
					    EOMONTH ( MaxDate, -1 )
					VAR PreviousMonthStart =
					    DATE ( YEAR ( PreviousMonthEnd ), MONTH ( PreviousMonthEnd ), 1 )
					RETURN
					    CALCULATE (
					        [Total Revenue],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousMonthStart, PreviousMonthEnd )
					    )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: f313c259-3317-443d-bc47-271d344818eb

			measure 'Previous Month Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PrevMonthDate =
					    EOMONTH ( MaxDate, -1 )
					RETURN
					    "Previous Month Revenue: " & FORMAT ( PrevMonthDate, "MMM yyyy" )
				displayFolder: Titles
				lineageTag: aedbae6a-809d-46a7-b0ee-d3d9e53521c4

			measure 'Current Month Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					RETURN
					    "Period (Till Date): " & FORMAT ( MaxDate, "MMM - yyyy" )
				displayFolder: Titles
				lineageTag: 7a933250-c072-457c-933f-13e65669b678

			measure 'Total Cost' =
					
					COALESCE (
					    CALCULATE (
					        SUMX ( sales, sales[totalCost] ),
					        USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					    ),
					    0
					)
				displayFolder: Cost Measures
				lineageTag: 18db8867-a17a-45d9-9bc0-d037a4ec40c5

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Gross Profit' =
					
					COALESCE (
					    CALCULATE (
					        SUMX ( sales, sales[profit] ),
					        USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					    ),
					    0
					)
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Profit Measures
				lineageTag: 2a8cf44d-ea37-4fda-949d-d8fed5755237

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure 'MoM % Revenue Change' =
					
					DIVIDE ( [Total Revenue] - [Previous Month Revenue], [Previous Month Revenue] )
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Revenue Measures
				lineageTag: 2837d126-22ab-46b9-991e-5b635f69a98d

			measure 'Previous Year Revenue' =
					
					CALCULATE ( [Total Revenue], DATEADD ( 'Calendar'[Date], -1, YEAR ) )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: bc7bdbfb-19f6-43fc-bcb4-6203f40abaea

			measure 'YoY % Revenue Change' =
					
					DIVIDE ( [Total Revenue] - [Previous Year Revenue], [Previous Year Revenue] )
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Revenue Measures
				lineageTag: 3920825d-7679-4882-b6f0-ba37d2a354d4

			measure 'Previous Month Profit' =
					
					CALCULATE ( [Gross Profit], DATEADD ( 'Calendar'[Date], -1, MONTH ) )
				displayFolder: Profit Measures
				lineageTag: bbaf945e-201c-4a55-9504-46b3496d455e

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Previous Year Profit' =
					
					CALCULATE ( [Gross Profit], DATEADD ( 'Calendar'[Date], -1, YEAR ) )
				displayFolder: Profit Measures
				lineageTag: 147ff6ac-efbb-4be9-80e4-52afbe0a983c

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'YoY % Profit Change' =
					
					DIVIDE ( [Gross Profit] - [Previous Year Profit], [Previous Year Profit] )
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Profit Measures
				lineageTag: 00f7ecb7-5ca7-4dc9-a5db-29a674f577b8

			measure 'YTD Profit' =
					
					COALESCE ( CALCULATE ( [Gross Profit], DATESYTD ( 'Calendar'[Date] ) ), 0 )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Profit Measures
				lineageTag: 28cdf07b-37bf-49d2-aa23-e9926dc9db85

			measure 'MTD Profit' =
					
					COALESCE ( CALCULATE ( [Gross Profit], DATESMTD ( 'Calendar'[Date] ) ), 0 )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Profit Measures
				lineageTag: 990b8211-317e-4cd0-97c8-b5a48eaae1b1

			measure 'MoM % Profit Change' =
					
					DIVIDE ( [Gross Profit] - [Previous Month Profit], [Previous Month Profit] )
				displayFolder: Profit Measures
				lineageTag: 6d4999c0-f377-40e1-ab23-cabcb82d1dd5

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure '% Gap From Last Month Revenue' =
					
					DIVIDE (
					    [MTD Revenue] - [Previous Month Revenue (From MTD)],
					    [Previous Month Revenue (From MTD)]
					)
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Revenue Measures
				lineageTag: ddb99ce1-c057-4510-825e-e28bc1d7517f

			measure 'YoY % Revenue Color' =
					
					SWITCH (
					    TRUE (),
					    [YoY % Revenue Change] > 0, "#08CB00",
					    [YoY % Revenue Change] < 0, "#E7BA61",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: f31c682a-c7f3-4d91-ba17-9972f2dbf919

			measure 'YoY % Profit Color' =
					
					SWITCH (
					    TRUE (),
					    [YoY % Profit Change] > 0, "#08CB00",
					    [YoY % Profit Change] < 0, "#E7BA61",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: a989512d-9b77-4e0a-b922-0752a0b30c67

			measure '% Gap Last Month Revenue Color' =
					
					SWITCH (
					    TRUE (),
					    [% Gap From Last Month Revenue] > 0, "#08CB00",
					    [% Gap From Last Month Revenue] < 0, "#E43636",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: 0319a711-a07d-468d-b09e-39d9ffd92a2e

			measure 'MTD Profit % Display' =
					
					VAR Change = [MoM % Profit Change (From MTD)]
					VAR diff = [MTD Profit] - [Previous Month Profit (From MTD)]
					RETURN
					    IF (
					        Change > 0,
					        "Gap From Prev Month: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Month Title],
					        "Gap From Prev Month: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Month Title]
					    )
				displayFolder: Arrows
				lineageTag: 68ccbff4-d74e-4b3a-900d-c516d6aa3350

			measure 'YTD New Customers' =
					
					COALESCE (
					    CALCULATE (
					        DISTINCTCOUNT ( customers[customerId] ),
					        USERELATIONSHIP ( 'Calendar'[Date], customers[registrationDate] ),
					        DATESYTD ( 'Calendar'[Date] )
					    ),
					    0
					)
				formatString: #,0
				displayFolder: Customer Insights
				lineageTag: 69c4a58a-cdc7-4bca-a1d6-2ec946dae067

			measure 'Registered Customers Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					RETURN
					    FORMAT ( MaxDate, "MMM - yyyy" ) & "  Reg Cust (Till Date)"
				displayFolder: Titles
				lineageTag: 5867d86b-5d40-4a4e-a056-d9626ce7f31f

			measure 'Previous Month Profit (From MTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousMonthEnd =
					    EOMONTH ( MaxDate, -1 )
					VAR PreviousMonthStart =
					    DATE ( YEAR ( PreviousMonthEnd ), MONTH ( PreviousMonthEnd ), 1 )
					RETURN
					    CALCULATE (
					        [Gross Profit],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousMonthStart, PreviousMonthEnd )
					    )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Profit Measures
				lineageTag: 6f0479df-3d77-4677-aac4-8327581359d4

			measure 'MoM % Profit Change (From MTD)' =
					
					DIVIDE (
					    [MTD Profit] - [Previous Month Profit (From MTD)],
					    [Previous Month Profit (From MTD)]
					)
				displayFolder: Profit Measures
				lineageTag: ca81e886-76d3-42cc-a410-ed9553e3d4e5

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'MoM % Profit Color (From MTD)' =
					
					SWITCH (
					    TRUE (),
					    [MoM % Profit Change (From MTD)] > 0, "#08CB00",
					    [MoM % Profit Change (From MTD)] < 0, "#DE6A73",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: a11cbd56-ec7e-41f9-b34d-41202813299a

			measure 'Month Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PrevMonthDate =
					    EOMONTH ( MaxDate, -1 )
					RETURN
					    FORMAT ( PrevMonthDate, "MMM yyyy" )
				displayFolder: Titles
				lineageTag: 1a039c2d-4b68-4abd-8de0-a67e05f9132c

			measure 'MTD Revenue % Display' =
					
					VAR Change = [% Gap From Last Month Revenue]
					VAR diff = [MTD Revenue] - [Previous Month Revenue (From MTD)]
					RETURN
					    IF (
					        Change > 0,
					        "Gap From Prev Month: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Month Title],
					        "Gap From Prev Month: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Month Title]
					    )
				displayFolder: Arrows
				lineageTag: f5368ee0-225a-4e20-a9da-eaefa716840f

			measure 'Units Sold' =
					
					COALESCE (
					    CALCULATE (
					        SUMX ( sales, sales[totalQuantity] ),
					        USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] ),
					        USERELATIONSHIP ( sales[orderId], sales_items[orderId] )
					    ),
					    0
					)
				formatString: #,0
				displayFolder: Sales Measures
				lineageTag: d0f846da-1231-413e-9101-caf8a13f4093

			measure 'MTD Units Sold' =
					
					COALESCE ( CALCULATE ( [Units Sold], DATESMTD ( 'Calendar'[Date] ) ), 0 )
				formatString: #,0
				displayFolder: Sales Measures
				lineageTag: 829d61ae-a1ab-4669-91a8-808c7d7fe35b

			measure 'Previous Month Sales' =
					
					COALESCE (
					    CALCULATE ( [Units Sold], DATEADD ( 'Calendar'[Date], -1, MONTH ) ),
					    0
					)
				formatString: 0
				displayFolder: Sales Measures
				lineageTag: 3f65d61f-2e4f-4044-9154-0a59c1e2fcee

			measure 'Previous Month Sales Quantity (From MTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousMonthEnd =
					    EOMONTH ( MaxDate, -1 )
					VAR PreviousMonthStart =
					    DATE ( YEAR ( PreviousMonthEnd ), MONTH ( PreviousMonthEnd ), 1 )
					RETURN
					    CALCULATE (
					        [Units Sold],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousMonthStart, PreviousMonthEnd )
					    )
				formatString: 0
				displayFolder: Sales Measures
				lineageTag: 55283385-e465-4711-9dcd-480676b9c7d2

			measure 'MoM % Sales Quantity Change' =
					
					DIVIDE (
					    [MTD Units Sold] - [Previous Month Sales Quantity (From MTD)],
					    [Previous Month Sales Quantity (From MTD)],
					    0
					)
				displayFolder: Sales Measures
				lineageTag: 58f41da0-d720-4e8e-8df1-17ed781d7549

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'MTD Units Sold % Display' =
					
					VAR Change = [MoM % Sales Quantity Change]
					VAR diff = [MTD Units Sold] - [Previous Month Sales Quantity (From MTD)]
					RETURN
					    IF (
					        Change > 0,
					        "Gap From Prev Month: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Month Title],
					        "Gap From Prev Month: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Month Title]
					    )
				displayFolder: Arrows
				lineageTag: 71619692-71ea-4b29-99e8-1deac8fc108c

			measure 'Selected Period Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					RETURN
					    "Selected Period: " & FORMAT ( MaxDate, "MMM - yyyy" )
				displayFolder: Titles
				lineageTag: c805fa39-53be-4d1b-9f3c-cdd6df3b33a4

			measure 'Previous Year Revenue (From YTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousYearEnd =
					    DATE ( YEAR ( MaxDate ) - 1, 12, 31 )
					VAR PreviousYearStart =
					    DATE ( YEAR ( MaxDate ) - 1, 1, 1 )
					RETURN
					    CALCULATE (
					        [Total Revenue],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousYearStart, PreviousYearEnd )
					    )
				displayFolder: Revenue Measures
				lineageTag: ff0f8a5a-0874-4b4f-bc47-34b6076ccca6

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure '% Gap From Last Year Revenue' =
					
					DIVIDE (
					    [YTD Revenue] - [Previous Year Revenue (From YTD)],
					    [Previous Year Revenue (From YTD)],
					    0
					)
				displayFolder: Revenue Measures
				lineageTag: 3b199e0b-6bcd-4278-aca2-80e40a2f533f

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'YTD Revenue % Display' =
					
					VAR Change = [% Gap From Last Year Revenue]
					VAR diff = [YTD Revenue] - [Previous Year Revenue (From YTD)]
					RETURN
					    IF (
					        Change > 0,
					        "Gap From Prev Year: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Prev Year Title],
					        "Gap From Prev Year: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Prev Year Title]
					    )
				displayFolder: Arrows
				lineageTag: 65a53db5-27cb-4219-a764-cac0b2d72feb

			measure 'Prev Year Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PrevYear =
					    YEAR ( MaxDate ) - 1
					RETURN
					    PrevYear
				formatString: 0
				displayFolder: Titles
				lineageTag: f1fc0eb7-1017-48f8-9b95-9c75a1d1a6b5

			measure '% Previous Year Revenue Color' =
					
					SWITCH (
					    TRUE (),
					    [% Gap From Last Year Revenue] > 0, "#08CB00",
					    [% Gap From Last Year Revenue] < 0, "#E43636",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: 0b278ae6-cf46-4d6a-a95e-687814c38f55

			measure 'MoM % Revenue Color (From MTD)' =
					
					SWITCH (
					    TRUE (),
					    [% Gap From Last Month Revenue] > 0, "#08CB00",
					    [% Gap From Last Month Revenue] < 0, "#DE6A73",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: e75a4f11-5fec-49af-acfe-af27e0df3d58

			measure 'MoM % Units Sold Color (From MTD)' =
					
					SWITCH (
					    TRUE (),
					    [MoM % Sales Quantity Change] > 0, "#08CB00",
					    [MoM % Sales Quantity Change] < 0, "#DE6A73",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: 2d2b7232-7e85-44df-88c2-bbd4a8cfd0d1

			measure 'Previous Year Profit (From YTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousYearEnd =
					    DATE ( YEAR ( MaxDate ) - 1, 12, 31 )
					VAR PreviousYearStart =
					    DATE ( YEAR ( MaxDate ) - 1, 1, 1 )
					RETURN
					    CALCULATE (
					        [Gross Profit],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousYearStart, PreviousYearEnd )
					    )
				displayFolder: Profit Measures
				lineageTag: c0a24148-5357-4394-a087-be6e2d42b264

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure '% Gap From Last Year Profit' =
					
					DIVIDE (
					    [YTD Revenue] - [Previous Year Profit (From YTD)],
					    [Previous Year Profit (From YTD)],
					    0
					)
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Profit Measures
				lineageTag: 63dc85ff-8fdc-4c09-8621-0719054d7bef

			measure 'YTD Profit % Display' =
					
					VAR Change = [% Gap From Last Year Profit]
					VAR diff = [YTD Profit] - [Previous Year Profit (From YTD)]
					RETURN
					    IF (
					        Change > 0,
					        "Gap From Prev Year: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Prev Year Title],
					        "Gap From Prev Year: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Prev Year Title]
					    )
				displayFolder: Arrows
				lineageTag: 0a668c33-c518-4052-8db9-ef8126ef2f5d

			measure '% Previous Year Profit Color' =
					
					SWITCH (
					    TRUE (),
					    [% Gap From Last Year Profit] > 0, "#08CB00",
					    [% Gap From Last Year Profit] < 0, "#E43636",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: 9d7d0bc3-654b-4041-9879-8b7e5bf79c07

			measure COGS =
					
					CALCULATE (
					    SUMX ( sales, sales[totalCost] ),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					)
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Cost Measures
				lineageTag: f01ed1aa-09c0-48da-ae0f-a6a16d33d03c

			measure 'YoY % Revenue Change Display' =
					
					VAR Change = [YoY % Revenue Change]
					RETURN
					    IF (
					        Change > 0,
					        "Prev Year: " & FORMAT ( Change, "0.00%" ) & " ",
					        "Prev Year: " & FORMAT ( Change, "0.00%" ) & " "
					    )
				displayFolder: Arrows
				lineageTag: d9137940-2a53-4ed2-8540-7875a9c18533

			measure 'Previous Year Sales' =
					
					COALESCE (
					    CALCULATE ( [Units Sold], DATEADD ( 'Calendar'[Date], -1, YEAR ) ),
					    0
					)
				formatString: 0
				displayFolder: Sales Measures
				lineageTag: d3b69ed1-b53b-4bce-b2f2-4536c96d3cd1

			measure 'YoY % Units Sold Change' =
					
					DIVIDE ( [Units Sold] - [Previous Year Sales], [Previous Year Sales] )
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Sales Measures
				lineageTag: db6f340e-439c-43e9-8769-6d32b7da576c

			measure 'YoY % Units Sold Change Display' =
					
					VAR Change = [YoY % Units Sold Change]
					RETURN
					    IF (
					        Change > 0,
					        "Prev Year: " & FORMAT ( Change, "0.00%" ) & " ",
					        "Prev Year: " & FORMAT ( Change, "0.00%" ) & " "
					    )
				displayFolder: Arrows
				lineageTag: 7fae059c-23e4-4be9-84e2-bb6f8e365498

			measure 'YTD Units Sold' =
					
					COALESCE ( CALCULATE ( [Units Sold], DATESYTD ( 'Calendar'[Date] ) ), 0 )
				formatString: #,0
				displayFolder: Sales Measures
				lineageTag: 853ddadb-733f-4abb-ac7f-1596648aae1c

			measure 'Total Orders' =
					
					CALCULATE (
					    DISTINCTCOUNT ( sales[orderId] ),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					)
				formatString: #,0
				displayFolder: Sales Measures
				lineageTag: 823f52ac-f640-4959-a60f-6f5fa773408a

			measure 'Active Sales Team' =
					
					CALCULATE (
					    DISTINCTCOUNT ( salespeople[salespersonId] ),
					    USERELATIONSHIP ( 'Calendar'[Date], salespeople[hireDate] ),
					    FILTER ( ALL ( 'Calendar' ), 'Calendar'[Date] <= MAX ( salespeople[hireDate] ) ),
					    FILTER ( salespeople, salespeople[employmentStatus] = "Active" )
					)
				formatString: 0
				displayFolder: Sales Team Measures
				lineageTag: 4bf25781-298b-43b3-b51d-e78cc605af8a

			measure Managers =
					
					CALCULATE (
					    DISTINCTCOUNT ( managers[managerId] ),
					    CROSSFILTER ( 'Calendar'[Date], managers[hireDate], BOTH ),
					    FILTER ( ALL ( 'Calendar' ), 'Calendar'[Date] <= MAX ( 'Calendar'[Date] ) )
					)
				formatString: 0
				displayFolder: Managers Measures
				lineageTag: 220e61d0-8fe6-4216-941f-0704d49cfd17

			measure 'Achievement %' =
					
					CALCULATE (
					    DIVIDE ( [Total Revenue], SUM ( salespeople[salesTarget] ), 0 ),
					    FILTER ( salespeople, salespeople[employmentStatus] = "Active" )
					)
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Sales Team Measures
				lineageTag: 2e6fd451-55d6-484b-b946-48aab8dce35f

			measure 'Inactive Sales Team' =
					
					CALCULATE (
					    DISTINCTCOUNT ( salespeople[salespersonId] ),
					    USERELATIONSHIP ( 'Calendar'[Date], salespeople[hireDate] ),
					    FILTER ( ALL ( 'Calendar' ), 'Calendar'[Date] <= MAX ( salespeople[hireDate] ) ),
					    FILTER ( salespeople, salespeople[employmentStatus] = "Inactive" )
					)
				formatString: 0
				displayFolder: Sales Team Measures
				lineageTag: a3e577e6-4d4a-4815-bd04-263733ad75e4

			measure 'Adjusted Gross Profit' =
					
					[Gross Profit] * ( 1 + 'Percentage Adjustment'[Percentage Adjustment Value] )
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Adjusted % Numbers
				lineageTag: 64ad1ea8-6681-423c-a386-21334653e20a

			measure 'Adjusted Revenue' =
					
					SUM ( sales_items[Total Revenue (lineTotal & taxAmount)] ) * ( 1 + 'Percentage Adjustment'[Percentage Adjustment Value] )
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Adjusted % Numbers
				lineageTag: 1d4b69b9-6054-4a4d-915f-4ae63747bbe8

			measure 'Average Order Value' =
					
					CALCULATE(
					    DIVIDE([Total Revenue],COUNTROWS(sales)),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					)
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Sales Measures
				lineageTag: 03014f07-f3b8-40fe-9d0c-e819d55f3a26

			measure 'Top Performing Region | Country Title' =
					
					VAR Region =
					    SELECTEDVALUE ( salespeople[region] )
					VAR Country =
					    SELECTEDVALUE ( salespeople[country] )
					RETURN
					    "Top 20 Best Performing Salesmen In "
					        & COALESCE ( Country, Region, "All Regions" )
				displayFolder: Dynamic Titles
				lineageTag: 7db2778b-402b-4a58-8874-2363f69e415f

			measure 'Salesman Name Title' =
					
					VAR salesmanname =
					    SELECTEDVALUE ( salespeople[fullName] )
					RETURN
					    COALESCE ( salesmanname, "All Salesmen's" ) & " Achievement Against Target"
				displayFolder: Dynamic Titles
				lineageTag: f8bdd71c-b5a0-4289-b407-ba1ceda0db3c

			measure 'YoY % Profit Change Display' =
					
					VAR Change = [YoY % Profit Change]
					RETURN
					    IF (
					        Change > 0,
					        "Prev Year: " & FORMAT ( Change, "0.00%" ) & " ",
					        "Prev Year: " & FORMAT ( Change, "0.00%" ) & " "
					    )
				displayFolder: Arrows
				lineageTag: 4371bf22-9572-4ce7-97c2-07ad094ed7f4

			measure 'YoY % Units Sold Color' =
					
					SWITCH (
					    TRUE (),
					    [YoY % Units Sold Change] > 0, "#08CB00",
					    [YoY % Units Sold Change] < 0, "#E7BA61",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: 16791332-0564-4ffa-9744-d2559083a44c

			measure '% Gap From Last Year Units Sold' =
					
					DIVIDE (
					    [YTD Units Sold] - [Previous Year Units Sold (From YTD)],
					    [Previous Year Units Sold (From YTD)],
					    0
					)
				displayFolder: Sales Measures
				lineageTag: b8fbcfad-6a37-4234-802a-97265a48643a

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Previous Year Units Sold (From YTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousYearEnd =
					    DATE ( YEAR ( MaxDate ) - 1, 12, 31 )
					VAR PreviousYearStart =
					    DATE ( YEAR ( MaxDate ) - 1, 1, 1 )
					RETURN
					    CALCULATE (
					        [Units Sold],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousYearStart, PreviousYearEnd )
					    )
				formatString: 0
				displayFolder: Sales Measures
				lineageTag: 43275a90-9438-4ada-8bbb-7d72e3a912ad

			measure 'YTD Units Sold % Display' =
					
					VAR Change = [% Gap From Last Year Units Sold]
					VAR diff = [YTD Units Sold] - [Previous Year Units Sold (From YTD)]
					RETURN
					    IF (
					        Change > 0,
					        "Gap From Prev Year: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Prev Year Title],
					        "Gap From Prev Year: " & UNICHAR(10) & FORMAT ( diff, "#,0" ) & " | " & FORMAT ( Change, "0.00%" ) & "  " & [Prev Year Title]
					    )
				displayFolder: Arrows
				lineageTag: f76b27f5-7231-4e0e-afcd-679c383285ce

			measure 'Increase / Decrease (YoY)' =
					
					VAR v = [YoY % Revenue Change]
					RETURN
					    IF (
					        v > 0,
					        "YoY Increase from the previous year " & [Prev Year Title] & ".",
					        "YoY Decrease from the previous year " & [Prev Year Title] & "."
					    )
				displayFolder: Increase / Decrease
				lineageTag: 5bbd8beb-38f7-4943-9036-9aa9b54f687d

			measure 'Current Year Title' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR CurrYear =
					    YEAR ( MaxDate )
					RETURN
					    CurrYear
				formatString: 0
				displayFolder: Titles
				lineageTag: 035d2b42-d749-49ea-9e69-2fbbb78d97d4

			measure 'Average Revenue' =
					
					CALCULATE (
					    AVERAGEX ( sales, sales[totalAmount] ),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] )
					)
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Revenue Measures
				lineageTag: dccc947d-fdca-445b-8dfb-393b9a1db6ee

			measure 'Previous Year Monthly Revenue (From YTD)' =
					
					VAR MaxDate =
					    MAX ( 'Calendar'[Date] )
					VAR PreviousYearEnd =
					    DATE ( YEAR ( MaxDate ) - 1, 12, 31 )
					VAR PreviousYearStart =
					    DATE ( YEAR ( MaxDate ) - 1, 1, 1 )
					VAR PrevYearMonthlyRev =
					    CALCULATE (
					        [Total Revenue],
					        DATESBETWEEN ( 'Calendar'[Date], PreviousYearStart, PreviousYearEnd )
					    )
					RETURN
					    DIVIDE ( PrevYearMonthlyRev, 12, 0 )
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Revenue Measures
				lineageTag: 16221b09-e7e0-4f94-8ceb-dfe950504d3c

			measure 'Revenue Forecast' =
					
					1.01 * [Previous Year Monthly Revenue (From YTD)]
				displayFolder: Forecasts
				lineageTag: c4f5bc8a-1ada-4cce-8e13-d6426f03dc0b

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Revenue Forecast Total' =
					
					[Revenue Forecast] * 12
				displayFolder: Forecasts
				lineageTag: 98096f18-a755-4f38-867e-c96a89817574

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Revenue Forecast % Change' =
					
					DIVIDE (
					    [Revenue Forecast Total] - [Previous Year Revenue (From YTD)],
					    [Previous Year Revenue (From YTD)]
					)
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Forecasts
				lineageTag: f30e8503-aa59-43bd-9402-6ec47869e759

			measure 'Region | Country Title' =
					
					VAR Region =
					    SELECTEDVALUE ( salespeople[region] )
					VAR Country =
					    SELECTEDVALUE ( salespeople[country] )
					RETURN
					    COALESCE ( Country, Region, "All Regions" )
				displayFolder: Dynamic Titles
				lineageTag: 2e607d2b-d516-472d-98a0-b4a1ef445fa4

			measure 'Revenue Goal (Monthly)' =
					
					VAR GoalValue =
					    SELECTEDVALUE ( 'Revenue Goal'[Revenue Goal], 0 )
					RETURN
					    DIVIDE ( GoalValue, 12 )
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Goal Measures
				lineageTag: 8870f6cb-b060-4e93-87d3-78f4910a7624

			measure 'Revenue Goal (%)' =
					
					DIVIDE (
					    [Revenue Goal (Monthly)] - [Previous Year Monthly Revenue (From YTD)],
					    [Previous Year Monthly Revenue (From YTD)],
					    0
					)
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Goal Measures
				lineageTag: 7ab0b43b-ccf1-4228-952e-1d684cfd457b

			measure 'Revenue Goal' =
					
					SELECTEDVALUE ( 'Revenue Goal'[Revenue Goal], 0 )
				formatString: 0
				displayFolder: Goal Measures
				lineageTag: 1ecfac4e-69af-43b0-bedb-cfcf4598c1f4

			measure 'Increase / Decrease (Revenue Goal)' =
					
					VAR v = [Revenue Goal (%)] RETURN IF ( v > 0, "increase", "decrease" )
				displayFolder: Increase / Decrease
				lineageTag: 1e31455a-fda4-42b1-af68-bf1f99774805

			measure 'Dynamic Line Value' =
					
					VAR SelectedMeasure =
					    SELECTEDVALUE ( 'Measure Selection'[Measure Name], "Revenue Generated" ) // Default to Revenue if nothing selected
					RETURN
					    SWITCH (
					        SelectedMeasure,
					        "Revenue Generated", [Total Revenue],
					        "Units Sold", [Units Sold],
					        "Profit", [Gross Profit],
					        BLANK ()
					    )
				displayFolder: Dynamic Line Value
				lineageTag: bfc01906-625d-4f84-b8e3-ff849feb97f0

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Units|Revenue|Profit Region | Country Title' = ```
					
					VAR Region = SELECTEDVALUE ( salespeople[region] )
					VAR Country = SELECTEDVALUE ( salespeople[country] )
					VAR salesmanname = SELECTEDVALUE ( salespeople[fullName] )
					VAR SelectedMetric =
					    SELECTEDVALUE (
					        'Dynamic Rev, Unit, Prof, Line'[Dynamic Rev, Unit, Prof, Line Fields],
					        "Multiple Metrics"
					    )
					
					VAR CleanMetric = 
					    SUBSTITUTE( SUBSTITUTE(SelectedMetric, "'All Measures'[", ""), "]", "" )
					RETURN
					IF(
					    ISBLANK(Region & Country),
					    "MTD " & CleanMetric,
					
					    "MTD " & CleanMetric & " In " & COALESCE ( Country, Region, "All Regions" ) & " By "
					        & COALESCE ( salesmanname, "All Sales Persons" )
					)
					```
				displayFolder: Dynamic Titles
				lineageTag: a23c5c0f-1632-44a7-a437-5b4c1115e402

			measure 'Last Purchase Date' = ```
					
					VAR PurchaseDate = 
					CALCULATE(
					    MAX(sales[orderDate]),
					    USERELATIONSHIP ( 'Calendar'[Date], sales[orderDate] ),
					    REMOVEFILTERS('Calendar'[Year], 'Calendar'[Month Name], 'Calendar'[Month], 'Calendar'[Start Of Month])
					)
					
					RETURN
					FORMAT(PurchaseDate, "mmm - yyyy")
					```
				displayFolder: Customer Insights
				lineageTag: ab9d2397-aa8d-4906-84bb-4334e886a44b

			measure 'Purchase Recency' = ```
					
					    DATEDIFF([Last Purchase Date], MAX('Calendar'[Date]), DAY)
					```
				formatString: 0
				displayFolder: Customer Insights
				lineageTag: 41acaf7e-c694-4524-9289-3adefdf3f106

			measure 'Purchase Frequency' =
					
					DIVIDE(
					    COUNTROWS(sales),
					    DISTINCTCOUNT(sales[customerId]),
					    0
					)
				formatString: 0
				displayFolder: Customer Insights
				lineageTag: 28b77ecf-d62d-4ef6-92da-871469024669

			measure 'Churned Customers' = ```
					
					VAR churnperioddays = SELECTEDVALUE('Churn Period'[Value])
					VAR MaxDate = MAX('Calendar'[Date])
					VAR churnthresholddate = MaxDate - churnperioddays
					
					VAR result =
					COALESCE(
					    COUNTROWS(
					    FILTER(
					        VALUES(customers[customerId]),
					        VAR LastPurchaseDate = 
					            CALCULATE(
					                MAX(sales[orderDate]),
					                REMOVEFILTERS('Calendar')
					            )
					        VAR CustomerRegistered = 
					            CALCULATE(
					                VALUES(customers[registrationDate]),
					                REMOVEFILTERS('Calendar')
					            )
					        RETURN
					            LastPurchaseDate < ChurnThresholdDate &&
					            CustomerRegistered <= ChurnThresholdDate
					        )
					    ), 0
					)
					
					RETURN
					result
					
					```
				formatString: #,0
				displayFolder: Customer Insights
				lineageTag: eeb59580-9a7f-4ee8-bb96-ed4fb3189337

			measure 'Churned Rate' =
					
					DIVIDE([Churned Customers], [Total Customers Till Date], 0)
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Customer Insights
				lineageTag: 418c574a-5b7e-4c56-a9ff-86950bb05dd8

			measure 'Repeat Purchases' =
					
					VAR MaxDateInContext = MAX('Calendar'[Date])
					RETURN
					COALESCE(
					    COUNTROWS(
					        FILTER(
					            VALUES(customers[customerId]),
					            CALCULATE(
					                COUNTROWS(sales),
					                REMOVEFILTERS('Calendar'),
					                sales[orderdate] <= MaxDateInContext
					            ) > 1
					        )
					    ), 0
					)
				formatString: #,0
				displayFolder: Customer Insights
				lineageTag: dee33b94-ce42-42ea-a5d5-de45ae2b6329

			measure 'Selected Periods Titles' =
					
					VAR MaxDate = MAX('Calendar'[Date])
					VAR Years =
					    SELECTEDVALUE ( 'Calendar'[Year] )
					VAR Months =
					    SELECTEDVALUE ( 'Calendar'[Month Name] )
					RETURN
					IF (
					    ISBLANK( Months & Years ),
					    "Current Period: " & FORMAT( MaxDate, "mmm yyyy" ),
					    "Selected Period: " & COALESCE ( Months & " " & Years, Years )
					)
				displayFolder: Titles
				lineageTag: 78fb1b3f-2347-4c04-9f1e-c5f724839893

				annotation PBI_FormatHint = {"isText":true}

			measure '% Revenue Share' =
					
					DIVIDE( [Total Revenue], CALCULATE( [Total Revenue], ALL() ) )
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: Revenue Measures
				lineageTag: 36bae623-42ab-4aac-aac8-052d658869d2

			measure 'Last Refresh PQ' = ```
					
					"Last Refresh: " &
					FORMAT( MAX('Refresh Timestamp'[Refresh Timestamp]), "dd MMM yyyy hh:mm AM/PM")
					
					```
				displayFolder: Last Refresh
				lineageTag: de08dfd9-cb23-42b9-8850-f0077657b7c3

			measure '% Previous Year Units Sold Color' =
					
					SWITCH (
					    TRUE (),
					    [% Gap From Last Year Units Sold] > 0, "#08CB00",
					    [% Gap From Last Year Units Sold] < 0, "#E43636",
					    "#808080"
					)
				displayFolder: Colors
				lineageTag: 5e9e3dc1-e90b-40e6-a50d-08365d1d799d

			measure 'Dynamic Tooltip Title' =
					
					SWITCH(
					    TRUE(),
					
					    ISINSCOPE(sales[salesRegion]),
					        SELECTEDVALUE('Calendar'[Month Name]),
					
					    ISINSCOPE('Calendar'[Month]),
					        FORMAT(SELECTEDVALUE('Calendar'[Month]), "MMMM YYYY"),
					
					    ISINSCOPE(sales[source]),
					        SELECTEDVALUE(sales[source]),
					
					    ISINSCOPE(sales[channel]),
					        SELECTEDVALUE(sales[channel]),
					
					    "Details"
					)
				displayFolder: Dynamic Tooltip
				lineageTag: c4101f83-f7fc-40c7-bcc2-f912520eaa5e

			measure 'Customers Bought' =
					
					VAR Mtds = DATESMTD('Calendar'[Date])
					
					RETURN
					CALCULATE(
					    COUNTROWS(
					        INTERSECT(SELECTCOLUMNS(customers, "CustomerId",customers[customerId]),
					                SELECTCOLUMNS(sales, "CustomerId", sales[customerId])
					        )
					    ),
					    Mtds
					)
				formatString: 0
				displayFolder: Customer Insights
				lineageTag: 6c58ac8a-8843-4b21-9ac0-5e659b5023a4

			measure 'Customers Bought This Month' = ```
					
					    CALCULATE(
					        DISTINCTCOUNT(sales[customerId]),
					        DATESMTD('Calendar'[Date])
					    )
					```
				formatString: 0
				displayFolder: Customer Insights
				lineageTag: e92a37ec-c50a-4f5e-b992-7aa92bcdbfcd

			measure 'MTD New Customers' = ```
					
					    CALCULATE(
					        DISTINCTCOUNT(customers[customerId]),
					        DATESMTD(customers[registrationDate])
					    )
					```
				formatString: 0
				displayFolder: Customer Insights
				lineageTag: 841fd24c-f6b6-40cd-bc13-1104e4e16cbf

			partition 'All Measures' = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
						in
						    #"Removed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Date(Date)
			lineageTag: f2f649c8-594e-492c-b62d-6bb9425c4ff3

			column Date(Date)
				lineageTag: 0563cfd6-2572-486a-be49-f07fb5337c7a
				summarizeBy: none
				sourceColumn: [Value1]
				sortByColumn: 'Date(Date) Order'

				relatedColumnDetails
					groupByColumn: 'Date(Date) Fields'

				annotation SummarizationSetBy = Automatic

			column 'Date(Date) Fields'
				isHidden
				lineageTag: 1bfd69c7-ac0f-4ad6-9068-7c5b19efaf75
				summarizeBy: none
				sourceColumn: [Value2]
				sortByColumn: 'Date(Date) Order'

				extendedProperty ParameterMetadata =
						{
						  "version": 3,
						  "kind": 2
						}

				annotation SummarizationSetBy = Automatic

			column 'Date(Date) Order'
				isHidden
				formatString: 0
				lineageTag: 6f9f036c-1312-4dce-a30e-822d2eca849d
				summarizeBy: sum
				sourceColumn: [Value3]

				annotation SummarizationSetBy = Automatic

			partition Date(Date) = calculated
				mode: import
				source =
						{
						    ("Date", NAMEOF('Calendar'[Date]), 0)
						}

			annotation PBI_Id = a369cca102b64bc097c4334df3862ef0

		table 'Time Period'
			isHidden
			lineageTag: 80fc761a-7830-41e5-b3c5-5cb316afe10f

			column Label
				isHidden
				lineageTag: efa76488-0554-401b-b1f2-703988d59d86
				summarizeBy: none
				isNameInferred
				sourceColumn: [Label]

				annotation SummarizationSetBy = Automatic

			column Data
				isHidden
				formatString: 0
				lineageTag: 91ccbcae-2430-4fdb-b10f-0924fc2903fa
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Data]

				annotation SummarizationSetBy = Automatic

			partition 'Time Period' = calculated
				mode: import
				source = ```
						
						DATATABLE(
						    "Label", STRING,
						    "Data", INTEGER,
						
						    {
						        {"1W", 14},
						        {"1M", 30},
						        {"3M", 90},
						        {"6M", 180},
						        {"1Y", 365.24}
						    }
						)
						
						```

			annotation PBI_Id = 94abc87cb6524a8885ad12d694d4b3b5

		table 'Top N Products (By Revenue)'
			isHidden
			lineageTag: 16ca045a-d6fb-46f8-83da-a24b87f1d928

			column productId
				isHidden
				lineageTag: 9853dfce-0365-46c6-8218-d640711e17bb
				summarizeBy: none
				isNameInferred
				sourceColumn: sales_items[productId]
				columnOrigin: sales_items.productId

				annotation SummarizationSetBy = Automatic

			column Revenue
				isHidden
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: cda5d68c-342d-4947-9bda-50b35440bda5
				summarizeBy: none
				isNameInferred
				sourceColumn: [Revenue]

				annotation SummarizationSetBy = Automatic

			column productName
				isHidden
				lineageTag: db28527c-d4eb-48bb-a72e-7c3c89de4a59
				summarizeBy: none
				isNameInferred
				sourceColumn: sales_items[productName]
				columnOrigin: sales_items.productName

				annotation SummarizationSetBy = Automatic

			partition 'Top N Products (By Revenue)' = calculated
				mode: import
				source = ```
						
						VAR chosen = SELECTEDVALUE('Top N'[Value])
						
						RETURN
						TOPN(
						    5,
						    SUMMARIZE(
						        sales_items,
						        sales_items[productId],
						        sales_items[productName],
						        "Revenue", SUM(sales_items[lineTotal]) + SUM(sales_items[taxAmount])
						    ),
						    [Revenue],
						    DESC
						)
						
						```

			annotation PBI_Id = 881588ffcf9846f08abcc5f5573d7c8a

		table 'Top N'
			isHidden
			lineageTag: 66dd857a-8f9a-4973-91ef-4731612e9b86

			column Value
				isHidden
				formatString: 0
				lineageTag: 32459b1b-9dfd-4236-b144-1ef26310c819
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Value]

				annotation SummarizationSetBy = Automatic

			partition 'Top N' = calculated
				mode: import
				source =
						
						DATATABLE(
						    "Value", INTEGER,
						
						    {
						        {5},
						        {10},
						        {20}
						    }
						    )

			annotation PBI_Id = 4735c11f672f4ed3b4500bb4eb2852d8

		table 'Top N Products (By Sales Quantity)'
			isHidden
			lineageTag: 3dad5855-48d6-440f-bb93-420707c3fc94

			column productId
				isHidden
				lineageTag: d82d082d-eb30-4191-815f-1fcb876ea772
				summarizeBy: none
				isNameInferred
				sourceColumn: sales_items[productId]
				columnOrigin: sales_items.productId

				annotation SummarizationSetBy = Automatic

			column productName
				isHidden
				lineageTag: 824230ef-5309-450e-b3ad-b0435c5c4426
				summarizeBy: none
				isNameInferred
				sourceColumn: sales_items[productName]
				columnOrigin: sales_items.productName

				annotation SummarizationSetBy = Automatic

			column Quantity
				isHidden
				formatString: 0
				lineageTag: 2f467d28-a2ba-4c9f-824c-4f174e1a7738
				summarizeBy: none
				isNameInferred
				sourceColumn: [Quantity]

				annotation SummarizationSetBy = Automatic

			partition 'Top N Products (By Sales Quantity)' = calculated
				mode: import
				source = ```
						
						VAR chosen = SELECTEDVALUE('Top N'[Value])
						
						RETURN
						TOPN(
						    5,
						    SUMMARIZE(
						        sales_items,
						        sales_items[productId],
						        sales_items[productName],
						        "Quantity", SUM(sales_items[quantity])
						    ),
						    [Quantity],
						    DESC
						)
						
						```

			annotation PBI_Id = a1a2051909bf416d9c3c2821481e9ff1

		table 'Top N Products (By Profit)'
			isHidden
			lineageTag: b32f2e8f-5440-4605-9160-ba993937e3f8

			column productId
				isHidden
				lineageTag: 2853a873-0f63-4ce9-899a-7ae59d57822c
				summarizeBy: none
				isNameInferred
				sourceColumn: sales_items[productId]
				columnOrigin: sales_items.productId

				annotation SummarizationSetBy = Automatic

			column productName
				isHidden
				lineageTag: 990297fa-229e-4b76-af2b-3af588d590a6
				summarizeBy: none
				isNameInferred
				sourceColumn: sales_items[productName]
				columnOrigin: sales_items.productName

				annotation SummarizationSetBy = Automatic

			column Profit
				isHidden
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: d7597c22-0527-4d0c-9da9-0017badd631f
				summarizeBy: none
				isNameInferred
				sourceColumn: [Profit]

				annotation SummarizationSetBy = Automatic

			partition 'Top N Products (By Profit)' = calculated
				mode: import
				source = ```
						
						VAR chosen = SELECTEDVALUE('Top N'[Value])
						
						RETURN
						TOPN(
						    5,
						    SUMMARIZE(
						        sales_items,
						        sales_items[productId],
						        sales_items[productName],
						        "Profit", SUM(sales_items[margin])
						    ),
						    [Profit],
						    DESC
						)
						
						```

			annotation PBI_Id = 1d59bb17f5fc44f4a2fb578bed25c252

		table 'Percentage Adjustment'
			lineageTag: d262f5f0-b4cb-4f4a-aae9-10b2fcee1705

			measure 'Percentage Adjustment Value' =
					
					SELECTEDVALUE ( 'Percentage Adjustment'[Percentage Adjustment %], 0 )
				lineageTag: 7ba76e9f-0910-43fa-a62e-76bbbfd634d1

			column 'Percentage Adjustment %'
				formatString: 0%;-0%;0%
				lineageTag: 1574f6ee-7f1d-480b-8067-00349697eeec
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata =
						{
						  "version": 0
						}

				annotation SummarizationSetBy = User

			partition 'Percentage Adjustment' = calculated
				mode: import
				source = GENERATESERIES(-1, 1, 0.05)

			annotation PBI_Id = c6b66083a5b24e81b0776d1f013f5825

		table 'Revenue Goal'
			lineageTag: 9aeee978-2834-42de-a1fc-a9169665e814

			measure 'Revenue Goal Value' =
					
					SELECTEDVALUE ( 'Revenue Goal'[Revenue Goal], 50000000 )
				formatString: 0
				lineageTag: d343f4a4-9819-4ec4-8c49-c24a3d8a14c8

			column 'Revenue Goal'
				formatString: 0
				lineageTag: 0bb2e2c7-32b8-40f8-b3d8-fb5f0e1dd076
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata =
						{
						  "version": 0
						}

				annotation SummarizationSetBy = User

			partition 'Revenue Goal' = calculated
				mode: import
				source = GENERATESERIES(0, 10000000000, 1000000)

			annotation PBI_Id = 618b2e0e4c3d4bdd8d33113881a32fe1

		table 'Measure Selection'
			lineageTag: fbfb3f82-5b31-4dde-bab4-e7f533bc077c

			column 'Measure Name'
				lineageTag: 6f0ed554-00f4-4927-a599-3f2361662c07
				summarizeBy: none
				isNameInferred
				sourceColumn: [Measure Name]

				annotation SummarizationSetBy = Automatic

			column 'Measure Order'
				formatString: 0
				lineageTag: 98eb3af0-7b22-4b86-a519-d168b91ff82e
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Measure Order]

				annotation SummarizationSetBy = Automatic

			partition 'Measure Selection' = calculated
				mode: import
				source =
						DATATABLE(
						    "Measure Name", STRING,
						    "Measure Order", INTEGER,
						    {
						        {"Revenue Generated", 1},
						        {"Units Sold", 2},
						        {"Profit", 3}
						    }
						)

			annotation PBI_Id = 171733c369c646a5a1cbb20d2343e964

		table 'Dynamic Rev, Unit, Prof, Line'
			lineageTag: 7a65a05c-6ede-41c4-a95f-9ac62514c836

			column 'Dynamic Rev, Unit, Prof, Line'
				lineageTag: a5872307-ef5e-43ec-bab3-b95afe182beb
				summarizeBy: none
				sourceColumn: [Value1]
				sortByColumn: 'Dynamic Rev, Unit, Prof, Line Order'

				relatedColumnDetails
					groupByColumn: 'Dynamic Rev, Unit, Prof, Line Fields'

				annotation SummarizationSetBy = Automatic

			column 'Dynamic Rev, Unit, Prof, Line Fields'
				isHidden
				lineageTag: d440e44b-171e-42dd-a703-20c37342e71e
				summarizeBy: none
				sourceColumn: [Value2]
				sortByColumn: 'Dynamic Rev, Unit, Prof, Line Order'

				extendedProperty ParameterMetadata =
						{
						  "version": 3,
						  "kind": 2
						}

				annotation SummarizationSetBy = Automatic

			column 'Dynamic Rev, Unit, Prof, Line Order'
				isHidden
				formatString: 0
				lineageTag: e983595e-bfd1-4066-9df7-123932c586c1
				summarizeBy: sum
				sourceColumn: [Value3]

				annotation SummarizationSetBy = Automatic

			partition 'Dynamic Rev, Unit, Prof, Line' = calculated
				mode: import
				source =
						{
						    ("Units Sold", NAMEOF('All Measures'[Units Sold]), 0),
						    ("Total Revenue", NAMEOF('All Measures'[Total Revenue]), 1),
						    ("Gross Profit", NAMEOF('All Measures'[Gross Profit]), 2)
						}

			annotation PBI_Id = a00cfd54dd4847928451ff6216bbe5c8

		table 'Churn Period'
			lineageTag: 466ba10b-1a65-4640-b7ae-eee5d6fd58b8

			column Label
				lineageTag: e1924b12-7ac7-44e2-9ae1-aefbd7a39dd7
				summarizeBy: none
				isNameInferred
				sourceColumn: [Label]

				annotation SummarizationSetBy = Automatic

			column Value
				formatString: 0
				lineageTag: 864fa67d-ce3b-4e13-9767-25405d43870c
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Value]

				annotation SummarizationSetBy = Automatic

			partition 'Churn Period' = calculated
				mode: import
				source =
						
						DATATABLE(
						    "Label", STRING,
						    "Value", INTEGER,
						
						    {
						        {"1W", 14},
						        {"1M", 30},
						        {"3M", 90},
						        {"6M", 180},
						        {"1Y", 365.24}
						    }
						)

			annotation PBI_Id = b89ef4803baf4c46b17b236b8e33c486

		table 'Refresh Timestamp'
			lineageTag: 492cbb2c-40cb-497f-ba59-95ba29b82a76

			column 'Refresh Timestamp'
				dataType: dateTime
				formatString: General Date
				lineageTag: 647d0c40-df21-4149-9d96-7c3f286dc089
				summarizeBy: none
				sourceColumn: Refresh Timestamp

				annotation SummarizationSetBy = Automatic

			partition 'Refresh Timestamp' = m
				mode: import
				source =
						let
						    Source = DateTime.LocalNow()
						in
						    Source

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = DateTime

		relationship 23b2436e-cbc3-2126-3e5d-232bed8395fc
			crossFilteringBehavior: bothDirections
			fromColumn: sales.customerId
			toColumn: customers.customerId

		relationship b5eade1a-5730-7e32-282a-3a607f013e73
			fromColumn: sales_items.customerId
			toColumn: customers.customerId

		relationship 6c15cce4-3e2d-237d-a3f7-97b41f39f4d6
			fromColumn: sales.salespersonId
			toColumn: salespeople.salespersonId

		relationship 4b5d574b-5be9-0174-edf5-fcd2f318bfa0
			fromColumn: sales.managerId
			toColumn: managers.managerId

		relationship 4efab8b9-0501-7f2e-4ea6-218adcff1209
			crossFilteringBehavior: bothDirections
			fromColumn: sales_items.productId
			toColumn: products.productId

		relationship f62eeee9-4260-28e1-edec-f32b039495d0
			isActive: false
			fromColumn: sales_items.orderId
			toColumn: sales.orderId

		relationship 70425a06-f81b-28ca-e79f-3aa44cb7d745
			fromColumn: sales_items.salespersonId
			toColumn: salespeople.salespersonId

		relationship b3efdd1f-9c57-2494-d58d-dbcf89d5e27b
			fromColumn: customers.registrationDate
			toColumn: Calendar.Date

		relationship 8c6f5318-3faa-c777-7cc1-f6f1d72c923d
			isActive: false
			fromColumn: sales.orderDate
			toColumn: Calendar.Date

		relationship 3b95d146-77d0-3269-d764-1205c87e935b
			isActive: false
			fromColumn: managers.hireDate
			toColumn: Calendar.Date

		relationship 22340cab-c1eb-5266-1f04-4d0ee8ac3006
			isActive: false
			fromColumn: sales_items.orderDate
			toColumn: Calendar.Date

		relationship beb3f69c-93b9-1628-194e-0c88095e2f65
			isActive: false
			fromColumn: salespeople.hireDate
			toColumn: Calendar.Date

		cultureInfo en-US

			linguisticMetadata = {"Version":"4.1.0","Language":"en-US","Entities":{"calendar.date":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"all_measure.total_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Total Revenue"}},"State":"Generated","Terms":[{"total revenue":{"State":"Generated"}},{"total income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"total profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"total turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"total yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"aggregate revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"Revenue":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Revenue Generated":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Monetary":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.gross_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Gross Profit"}},"State":"Generated","Terms":[{"gross profit":{"State":"Generated"}},{"aggregate profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.647}},{"overall profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.647}},{"whole profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.647}},{"sum profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"gross income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"gross revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"gross turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"gross return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"gross yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale":{"Definition":{"Binding":{"ConceptualEntity":"sales"}},"State":"Generated","Terms":[{"sale":{"State":"Generated"}},{"auction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"transaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"deal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"vending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"retailing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"selling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"sale.order_id":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"orderId"}},"State":"Generated","Terms":[{"order id":{"State":"Generated"}},{"orderId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"order":{"State":"Generated","Weight":0.97}},{"order identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"directive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"demand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"sale.invoice_number":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"invoiceNumber"}},"State":"Generated","Terms":[{"invoice number":{"State":"Generated"}},{"invoiceNumber":{"Type":"Noun","State":"Generated","Weight":0.99}},{"invoice no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.order_date":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"orderDate"}},"State":"Generated","Terms":[{"order date":{"State":"Generated"}},{"orderDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"order moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"sale.order_time":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"orderTime"}},"State":"Generated","Terms":[{"order time":{"State":"Generated"}},{"orderTime":{"Type":"Noun","State":"Generated","Weight":0.99}},{"time":{"State":"Generated","Weight":0.7}},{"order duration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order interval":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"order timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"sale.customer_id":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"customerId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"customer id":{"State":"Generated"}},{"customerId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"client id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"buyer id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"patron id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"purchaser id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"sale.customer_name":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"customerName"}},"State":"Generated","Terms":[{"customer name":{"State":"Generated"}},{"customerName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer surname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"client name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"buyer name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"patron name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"sale.customer_type":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"customerType"}},"State":"Generated","Terms":[{"customer type":{"State":"Generated"}},{"customerType":{"Type":"Noun","State":"Generated","Weight":0.99}},{"type":{"State":"Generated","Weight":0.97}},{"customer category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"customer brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.customer_country":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"customerCountry"}},"State":"Generated","Terms":[{"customer country":{"State":"Generated"}},{"customerCountry":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"client country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"buyer country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"patron country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"purchaser country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"shopper country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"Country":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"sale.customer_city":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"customerCity"}},"State":"Generated","Terms":[{"customer city":{"State":"Generated"}},{"customerCity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"client city":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer city":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user city":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"buyer city":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"patron city":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"sale.customer_region":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"customerRegion"}},"State":"Generated","Terms":[{"customer region":{"State":"Generated"}},{"customerRegion":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}},{"customer province":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer district":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer zone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer continent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"client region":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer region":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user region":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"sale.salesperson_id":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"salespersonId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"salesperson id":{"State":"Generated"}},{"salespersonId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"salesperson identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.salesperson_name":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"salespersonName"}},"State":"Generated","Terms":[{"salesperson name":{"State":"Generated"}},{"salespersonName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"salesperson nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"salesperson title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"salesperson label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"salesperson tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.manager_id":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"managerId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"manager id":{"State":"Generated"}},{"managerId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"manager identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.manager_name":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"managerName"}},"State":"Generated","Terms":[{"manager name":{"State":"Generated"}},{"managerName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"manager nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"manager title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"manager label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"manager tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.sales_region":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"salesRegion"}},"State":"Generated","Terms":[{"sales region":{"State":"Generated"}},{"sale region":{"Type":"Noun","State":"Generated","Weight":0.78}},{"salesRegion":{"Type":"Noun","State":"Generated","Weight":0.99}},{"sale location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}},{"sale province":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale district":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale zone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale continent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"Region":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"sale.sales_country":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"salesCountry"}},"State":"Generated","Terms":[{"sales country":{"State":"Generated"}},{"sale country":{"Type":"Noun","State":"Generated","Weight":0.78}},{"salesCountry":{"Type":"Noun","State":"Generated","Weight":0.99}},{"sale nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}}]},"sale.sales_city":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"salesCity"}},"State":"Generated","Terms":[{"sales city":{"State":"Generated"}},{"sale city":{"Type":"Noun","State":"Generated","Weight":0.78}},{"salesCity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"sale location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.order_status":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"orderStatus"}},"State":"Generated","Terms":[{"order status":{"State":"Generated"}},{"orderStatus":{"Type":"Noun","State":"Generated","Weight":0.99}},{"status":{"State":"Generated","Weight":0.97}},{"order category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"order condition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"order class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"order grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.payment_method":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"paymentMethod"}},"State":"Generated","Terms":[{"payment method":{"State":"Generated"}},{"paymentMethod":{"Type":"Noun","State":"Generated","Weight":0.99}},{"method":{"State":"Generated","Weight":0.97}},{"payment technique":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"payment system":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"payment manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"payment mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"technique":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"system":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"payment way":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"payment process":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.payment_status":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"paymentStatus"}},"State":"Generated","Terms":[{"payment status":{"State":"Generated"}},{"paymentStatus":{"Type":"Noun","State":"Generated","Weight":0.99}},{"status":{"State":"Generated","Weight":0.97}},{"payment category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"payment importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"payment prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"payment prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"payment condition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"payment class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"payment grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.payment_term":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"paymentTerms"}},"State":"Generated","Terms":[{"payment term":{"State":"Generated"}},{"paymentTerms":{"Type":"Noun","State":"Generated","Weight":0.99}},{"term":{"State":"Generated","Weight":0.97}},{"payment tenure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"payment duration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tenure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"duration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"payment period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"payment stretch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"payment span":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"payment stint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"stretch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"span":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"sale.shipping_method":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"shippingMethod"}},"State":"Generated","Terms":[{"shipping method":{"State":"Generated"}},{"shippingMethod":{"Type":"Noun","State":"Generated","Weight":0.99}},{"method":{"State":"Generated","Weight":0.97}},{"shipping technique":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"shipping system":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"shipping manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"shipping mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"technique":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"system":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"shipping way":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"shipping process":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.shipping_city":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"shippingCity"}},"State":"Generated","Terms":[{"shipping city":{"State":"Generated"}},{"shippingCity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"shipping location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"shipping metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.shipping_country":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"shippingCountry"}},"State":"Generated","Terms":[{"shipping country":{"State":"Generated"}},{"shippingCountry":{"Type":"Noun","State":"Generated","Weight":0.99}},{"shipping nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}}]},"sale.billing_city":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"billingCity"}},"State":"Generated","Terms":[{"billing city":{"State":"Generated"}},{"billingCity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"billing location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"billing metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.billing_country":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"billingCountry"}},"State":"Generated","Terms":[{"billing country":{"State":"Generated"}},{"billingCountry":{"Type":"Noun","State":"Generated","Weight":0.99}},{"billing nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}}]},"sale.item_count":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"itemCount"}},"State":"Generated","Terms":[{"item count":{"State":"Generated"}},{"itemCount":{"Type":"Noun","State":"Generated","Weight":0.99}},{"item amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"element count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"entry count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"article count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"object count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"piece count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"token count":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"sale.total_quantity":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"totalQuantity"}},"State":"Generated","Terms":[{"total quantity":{"State":"Generated"}},{"totalQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"aggregate quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.subtotal":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"subtotal"}},"State":"Generated","Terms":[{"subtotal":{"State":"Generated"}}]},"sale.tax_amount":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"taxAmount"}},"State":"Generated","Terms":[{"tax amount":{"State":"Generated"}},{"taxAmount":{"Type":"Noun","State":"Generated","Weight":0.99}},{"tax quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax expanse":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax sum":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"tax total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"tax aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.shipping_cost":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"shippingCost"}},"State":"Generated","Terms":[{"shipping cost":{"State":"Generated"}},{"shippingCost":{"Type":"Noun","State":"Generated","Weight":0.99}},{"cost":{"State":"Generated","Weight":0.97}},{"shipping price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"shipping charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"shipping rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"shipping fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"shipping total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"shipping expenditure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"expenditure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"shipping budget":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"sale.total_amount":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"totalAmount"}},"State":"Generated","Terms":[{"total amount":{"State":"Generated"}},{"totalAmount":{"Type":"Noun","State":"Generated","Weight":0.99}},{"aggregate amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total expanse":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total sum":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.total_cost":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"totalCost"}},"State":"Generated","Terms":[{"total cost":{"State":"Generated"}},{"totalCost":{"Type":"Noun","State":"Generated","Weight":0.99}},{"cost":{"State":"Generated","Weight":0.97}},{"aggregate cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"total expenditure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"sale.profit":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"profit"}},"State":"Generated","Terms":[{"profit":{"State":"Generated"}},{"income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"advantage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"gain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"benefit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"reward":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"good":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"sale.profit_margin":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"profitMargin"}},"State":"Generated","Terms":[{"profit margin":{"State":"Generated"}},{"profitMargin":{"Type":"Noun","State":"Generated","Weight":0.99}},{"profit boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"profit perimeter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"profit periphery":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"profit border":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"profit brim":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"profit sideline":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"profit edge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"profit verge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"profit fringe":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"profit side":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.commission":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"commission"}},"State":"Generated","Terms":[{"commission":{"State":"Generated"}},{"instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"assignment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"directive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"contract":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"warrant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"payment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"cut":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"sale.currency":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"currency"}},"State":"Generated","Terms":[{"currency":{"State":"Generated"}},{"money":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"coinage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"exchange":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cash":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"prevalence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"popularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"vogue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"circulation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"commonness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"acceptance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"sale.exchange_rate":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"exchangeRate"}},"State":"Generated","Terms":[{"exchange rate":{"State":"Generated"}},{"exchangeRate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"rate":{"State":"Generated","Weight":0.97}},{"exchange degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"exchange frequency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"exchange percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"exchange ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"exchange quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"exchange amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"exchange proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.note":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"notes"}},"State":"Generated","Terms":[{"note":{"State":"Generated"}},{"memo":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"memorandum":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"reminder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"letter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"message":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"communication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"annotation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"addendum":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"commentary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"footnote":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"sale.ship_date":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"shipDate"}},"State":"Generated","Terms":[{"ship date":{"State":"Generated"}},{"shipDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"ship moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"ship period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"sale.estimated_delivery":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"estimatedDelivery"}},"State":"Generated","Terms":[{"estimated delivery":{"State":"Generated"}},{"estimatedDelivery":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"delivery":{"State":"Generated","Weight":0.97}},{"estimated distribution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"estimated conveyance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"estimated carriage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"distribution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"conveyance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"carriage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"estimated transfer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"estimated transport":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"estimated sending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"estimated provision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}],"SemanticType":"Time"},"sale.actual_delivery":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"actualDelivery"}},"State":"Generated","Terms":[{"actual delivery":{"State":"Generated"}},{"actualDelivery":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"delivery":{"State":"Generated","Weight":0.97}},{"real delivery":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"existent delivery":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"tangible delivery":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"actual distribution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"actual conveyance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"actual carriage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"distribution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"conveyance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"carriage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"actual transfer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}],"SemanticType":"Time"},"sale.carrier":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"carrier"}},"State":"Generated","Terms":[{"carrier":{"State":"Generated"}},{"transporter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"hauler":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"carter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"shipper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"exporter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"importer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"transferor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"sale.return_reason":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"returnReason"}},"State":"Generated","Terms":[{"return reason":{"State":"Generated"}},{"returnReason":{"Type":"Noun","State":"Generated","Weight":0.99}},{"reason":{"State":"Generated","Weight":0.97}},{"return motivation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"return intention":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"motivation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"intention":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"return aim":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return motive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return cause":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return purpose":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return object":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sale.source":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"source"}},"State":"Generated","Terms":[{"source":{"State":"Generated"}},{"basis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"font":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"birthplace":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"foundation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cause":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"spring":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cradle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"home":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"informant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"spokesperson":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"Order Source":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"sale.channel":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"channel"}},"State":"Generated","Terms":[{"channel":{"State":"Generated"}},{"station":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"network":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"conduit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"waterway":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"canal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"strait":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"passage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"Sales Channel":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"sales_item":{"Definition":{"Binding":{"ConceptualEntity":"sales_items"}},"State":"Generated","Terms":[{"sales item":{"State":"Generated"}},{"sale item":{"Type":"Noun","State":"Generated","Weight":0.78}},{"sales_items":{"Type":"Noun","State":"Generated","Weight":0.99}},{"item":{"State":"Generated","Weight":0.97}},{"sale product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"sale entry":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"entry":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"sale article":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale object":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale token":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"sales_item.line_item_id":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"lineItemId"}},"State":"Generated","Terms":[{"line item id":{"State":"Generated"}},{"id":{"State":"Generated","Weight":0.97}},{"lineItemId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"item":{"State":"Generated","Weight":0.97}},{"line item":{"State":"Generated","Weight":0.97}},{"item id":{"State":"Generated","Weight":0.97}},{"line item identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"line item identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"line item identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"line product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"line element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"line entry":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"item identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"item identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"item identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"line item credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}],"NameType":"Identifier"},"sales_item.order_id":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"orderId"}},"State":"Generated","Terms":[{"order id":{"State":"Generated"}},{"orderId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"order":{"State":"Generated","Weight":0.97}},{"order identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"directive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"demand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"sales_item.invoice_number":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"invoiceNumber"}},"State":"Generated","Terms":[{"invoice number":{"State":"Generated"}},{"invoiceNumber":{"Type":"Noun","State":"Generated","Weight":0.99}},{"invoice no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sales_item.order_date":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"orderDate"}},"State":"Generated","Terms":[{"order date":{"State":"Generated"}},{"orderDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"order moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"order period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"sales_item.customer_id":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"customerId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"customer id":{"State":"Generated"}},{"customerId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"client id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"buyer id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"patron id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"purchaser id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"sales_item.salesperson_id":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"salespersonId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"salesperson id":{"State":"Generated"}},{"salespersonId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"salesperson identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sales_item.product_id":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"productId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product id":{"State":"Generated"}},{"productId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"merchandise id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"sales_item.sku":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"sku"}},"State":"Generated","Terms":[{"sku":{"State":"Generated"}}]},"sales_item.product_name":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"productName"}},"State":"Generated","Terms":[{"product name":{"State":"Generated"}},{"productName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"item name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"merchandise name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"sales_item.category":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"category"}},"State":"Generated","Terms":[{"category":{"State":"Generated"}},{"classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"sales_item.subcategory":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"subcategory"}},"State":"Generated","Terms":[{"subcategory":{"State":"Generated"}}]},"sales_item.brand":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"brand"}},"State":"Generated","Terms":[{"brand":{"State":"Generated"}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"marque":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"make":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"trademark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"style":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"strain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cast":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"marker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"sales_item.quantity":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"quantity"}},"State":"Generated","Terms":[{"quantity":{"State":"Generated"}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"sales_item.unit_price":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"unitPrice"}},"State":"Generated","Terms":[{"unit price":{"State":"Generated"}},{"unitPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"module price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"element price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"entity price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"group price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"component price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"constituent price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"item price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"part price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"section price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"unit value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sales_item.cost_price":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"costPrice"}},"State":"Generated","Terms":[{"cost price":{"State":"Generated"}},{"costPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"cost value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sales_item.discount_percent":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"discountPercent"}},"State":"Generated","Terms":[{"discount percent":{"State":"Generated"}},{"discountPercent":{"Type":"Noun","State":"Generated","Weight":0.99}},{"discount percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"discount ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"discount percentile":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"discount part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"discount proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"discount fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"sales_item.discount_amount":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"discountAmount"}},"State":"Generated","Terms":[{"discount amount":{"State":"Generated"}},{"discountAmount":{"Type":"Noun","State":"Generated","Weight":0.99}},{"discount quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"discount volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"discount expanse":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"discount extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"discount sum":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"discount total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"discount aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sales_item.line_total":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"lineTotal"}},"State":"Generated","Terms":[{"line total":{"State":"Generated"}},{"lineTotal":{"Type":"Noun","State":"Generated","Weight":0.99}},{"line aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"line overall":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sales_item.tax_amount":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"taxAmount"}},"State":"Generated","Terms":[{"tax amount":{"State":"Generated"}},{"taxAmount":{"Type":"Noun","State":"Generated","Weight":0.99}},{"tax quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax expanse":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax sum":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"tax total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"tax aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"sales_item.warehouse":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"warehouse"}},"State":"Generated","Terms":[{"warehouse":{"State":"Generated"}},{"granary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"storeroom":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"hayloft":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"silo":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"barn":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"depository":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"depot":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"stockroom":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"repository":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"storehouse":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"sales_item.margin":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"margin"}},"State":"Generated","Terms":[{"margin":{"State":"Generated"}},{"boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"perimeter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"periphery":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"border":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"brim":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"sideline":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"edge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"verge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"fringe":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"side":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"sales_item.margin_percent":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"marginPercent"}},"State":"Generated","Terms":[{"margin percent":{"State":"Generated"}},{"marginPercent":{"Type":"Noun","State":"Generated","Weight":0.99}},{"margin percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"margin ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"margin percentile":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"margin part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"margin proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"margin fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"sales_item.tax_rate":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"taxRate"}},"State":"Generated","Terms":[{"tax rate":{"State":"Generated"}},{"taxRate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"rate":{"State":"Generated","Weight":0.97}},{"tax degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax frequency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tax quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"tax proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"tax speed":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product":{"Definition":{"Binding":{"ConceptualEntity":"products"}},"State":"Generated","Terms":[{"product":{"State":"Generated"}},{"artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"product.product_id":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"productId"}},"State":"Generated","Terms":[{"product id":{"State":"Generated"}},{"id":{"State":"Generated","Weight":0.97}},{"productId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"merchandise id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"NameType":"Identifier"},"product.sku":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"sku"}},"State":"Generated","Terms":[{"sku":{"State":"Generated"}}]},"product.barcode":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"barcode"}},"State":"Generated","Terms":[{"barcode":{"State":"Generated"}}]},"product.product_name":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"productName"}},"State":"Generated","Terms":[{"product name":{"State":"Generated"}},{"name":{"State":"Generated","Weight":0.97}},{"productName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"item name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"merchandise name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"Product":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}],"NameType":"Name"},"product.description":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"description"}},"State":"Generated","Terms":[{"description":{"State":"Generated"}},{"appearance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"descriptor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"explanation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"specification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"account":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"overview":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"report":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"product.category":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"category"}},"State":"Generated","Terms":[{"category":{"State":"Generated"}},{"classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"product.subcategory":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"subcategory"}},"State":"Generated","Terms":[{"subcategory":{"State":"Generated"}}]},"product.brand":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"brand"}},"State":"Generated","Terms":[{"brand":{"State":"Generated"}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"marque":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"make":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"trademark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"style":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"strain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cast":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"marker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"product.manufacturer":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"manufacturer"}},"State":"Generated","Terms":[{"manufacturer":{"State":"Generated"}},{"builder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"producer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"constructer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"creator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"industrialist":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"maker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"firm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"product.unit_price":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"unitPrice"}},"State":"Generated","Terms":[{"unit price":{"State":"Generated"}},{"unitPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"module price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"element price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"entity price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"group price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"component price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"constituent price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"item price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"part price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"section price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"unit value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product.cost_price":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"costPrice"}},"State":"Generated","Terms":[{"cost price":{"State":"Generated"}},{"costPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"cost value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cost outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product.msrp":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"msrp"}},"State":"Generated","Terms":[{"msrp":{"State":"Generated"}}]},"product.supplier":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"supplier"}},"State":"Generated","Terms":[{"supplier":{"State":"Generated"}},{"dealer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"contractor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"provider":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"trader":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"seller":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"purveyor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"broker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"merchant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"product.supplier_sku":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"supplierSku"}},"State":"Generated","Terms":[{"supplier sku":{"State":"Generated"}},{"supplierSku":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"product.weight":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"weight"}},"State":"Generated","Terms":[{"weight":{"State":"Generated"}},{"heaviness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"weightiness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"heft":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"encumbrance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"burden":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"load":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.weight_unit":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"weightUnit"}},"State":"Generated","Terms":[{"weight unit":{"State":"Generated"}},{"weightUnit":{"Type":"Noun","State":"Generated","Weight":0.99}},{"unit":{"State":"Generated","Weight":0.97}},{"weight module":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"weight element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"weight entity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"module":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"entity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"weight group":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"weight component":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"weight constituent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"weight item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"product.dimension":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"dimensions"}},"State":"Generated","Terms":[{"dimension":{"State":"Generated"}},{"measurement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"length":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"height":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"width":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"breadth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"aspect":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"facet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"feature":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"factor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.dimension_unit":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"dimensionUnit"}},"State":"Generated","Terms":[{"dimension unit":{"State":"Generated"}},{"dimensionUnit":{"Type":"Noun","State":"Generated","Weight":0.99}},{"unit":{"State":"Generated","Weight":0.97}},{"dimension module":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dimension element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dimension entity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"module":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"element":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"entity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"dimension group":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dimension component":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dimension constituent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dimension item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"product.color":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"color"}},"State":"Generated","Terms":[{"color":{"State":"Generated"}},{"hue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"tint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"shade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"dye":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"paint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"pigment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"product.size":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"size"}},"State":"Generated","Terms":[{"size":{"State":"Generated"}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"scope":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.material":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"material"}},"State":"Generated","Terms":[{"material":{"State":"Generated"}},{"physical":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"substantial":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"solid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"central":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"substantive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.stock_quantity":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"stockQuantity"}},"State":"Generated","Terms":[{"stock quantity":{"State":"Generated"}},{"stockQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"inventory quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"stock extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"stock magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"stock amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"stock number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"stock measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"stock size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"stock capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"stock mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product.reserved_quantity":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"reservedQuantity"}},"State":"Generated","Terms":[{"reserved quantity":{"State":"Generated"}},{"reservedQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"reserved extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"reserved magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"reserved amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reserved number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reserved measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reserved size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reserved capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reserved mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product.available_quantity":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"availableQuantity"}},"State":"Generated","Terms":[{"available quantity":{"State":"Generated"}},{"availableQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"available extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"available magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"available amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"available number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"available measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"available size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"available capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"available mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product.reorder_level":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"reorderLevel"}},"State":"Generated","Terms":[{"reorder level":{"State":"Generated"}},{"reorderLevel":{"Type":"Noun","State":"Generated","Weight":0.99}},{"level":{"State":"Generated","Weight":0.97}},{"reorder threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"reorder amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"reorder grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"reorder point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"reorder rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"reorder tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"product.reorder_quantity":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"reorderQuantity"}},"State":"Generated","Terms":[{"reorder quantity":{"State":"Generated"}},{"reorderQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"reorder extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"reorder magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"reorder amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reorder number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reorder measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reorder size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reorder capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"reorder mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"product.min_order_quantity":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"minOrderQuantity"}},"State":"Generated","Terms":[{"min order quantity":{"State":"Generated"}},{"minOrderQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"order quantity":{"State":"Generated","Weight":0.97}},{"minimum order quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"min order extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"min order magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"order extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"order magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"min order amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"min order number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"min order measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"min order size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"min order capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"product.max_order_quantity":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"maxOrderQuantity"}},"State":"Generated","Terms":[{"max order quantity":{"State":"Generated"}},{"maxOrderQuantity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"order quantity":{"State":"Generated","Weight":0.97}},{"maximum order quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"max order extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"max order magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"order extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"order magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"max order amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"max order number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"max order measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"max order size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"max order capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"product.warehouse":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"warehouse"}},"State":"Generated","Terms":[{"warehouse":{"State":"Generated"}},{"granary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"storeroom":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"hayloft":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"silo":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"barn":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"depository":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"depot":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"stockroom":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"repository":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"storehouse":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"product.aisle":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"aisle"}},"State":"Generated","Terms":[{"aisle":{"State":"Generated"}},{"passageway":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"gangway":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"walkway":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"corridor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"lane":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"passage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"product.shelf":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"shelf"}},"State":"Generated","Terms":[{"shelf":{"State":"Generated"}},{"ledge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"sill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"bookshelf":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mantelpiece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"projection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mantelshelf":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"layer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"ridge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"step":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.bin":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"bin"}},"State":"Generated","Terms":[{"bin":{"State":"Generated"}},{"basket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"container":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"holder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"silo":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"tub":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"case":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"vat":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"wastebasket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"dustbin":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"product.warranty_month":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"warrantyMonths"}},"State":"Generated","Terms":[{"warranty month":{"State":"Generated"}},{"warrantyMonths":{"Type":"Noun","State":"Generated","Weight":0.99}},{"warranty mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}}]},"product.return_policy":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"returnPolicy"}},"State":"Generated","Terms":[{"return policy":{"State":"Generated"}},{"returnPolicy":{"Type":"Noun","State":"Generated","Weight":0.99}},{"policy":{"State":"Generated","Weight":0.97}},{"return strategy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"return procedure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"return dogma":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"strategy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"procedure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"dogma":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"return rule":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return plan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"return program":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rule":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"product.is_active":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"isActive"}},"State":"Generated","Terms":[{"is active":{"State":"Generated"}},{"isActive":{"Type":"Noun","State":"Generated","Weight":0.99}},{"active":{"State":"Generated","Weight":0.97}},{"dynamic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"functioning":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"effective":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"operating":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"working":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.is_featured":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"isFeatured"}},"State":"Generated","Terms":[{"is featured":{"State":"Generated"}},{"isFeatured":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"product.is_on_sale":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"isOnSale"}},"State":"Generated","Terms":[{"is on sale":{"State":"Generated"}},{"isOnSale":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"product.rating":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"rating"}},"State":"Generated","Terms":[{"rating":{"State":"Generated"}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"evaluation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"score":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"ranking":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"sailor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"seaman":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"hand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"product.review_count":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"reviewCount"}},"State":"Generated","Terms":[{"review count":{"State":"Generated"}},{"reviewCount":{"Type":"Noun","State":"Generated","Weight":0.99}},{"review amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"product.tag":{"Definition":{"Binding":{"ConceptualEntity":"products","ConceptualProperty":"tags"}},"State":"Generated","Terms":[{"tag":{"State":"Generated"}},{"device":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"ticket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"tab":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"docket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"chip":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"customer":{"Definition":{"Binding":{"ConceptualEntity":"customers"}},"State":"Generated","Terms":[{"customer":{"State":"Generated"}},{"client":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"consumer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"user":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"buyer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"patron":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"purchaser":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"shopper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"customer.customer_id":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"customerId"}},"State":"Generated","Terms":[{"customer id":{"State":"Generated"}},{"id":{"State":"Generated","Weight":0.97}},{"customerId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"customer identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"client id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"consumer id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"user id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"buyer id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"patron id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"purchaser id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}],"NameType":"Identifier"},"customer.customer_type":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"customerType"}},"State":"Generated","Terms":[{"customer type":{"State":"Generated"}},{"customerType":{"Type":"Noun","State":"Generated","Weight":0.99}},{"type":{"State":"Generated","Weight":0.97}},{"customer category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"customer brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"customer.first_name":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"firstName"}},"State":"Generated","Terms":[{"first name":{"State":"Generated"}},{"firstName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"first nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"1st name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"customer.last_name":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"lastName"}},"State":"Generated","Terms":[{"last name":{"State":"Generated"}},{"lastName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"last nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"end name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"final name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"closing name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"concluding name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"finishing name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"former name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"customer.company_name":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"companyName"}},"State":"Generated","Terms":[{"company name":{"State":"Generated"}},{"companyName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"company":{"State":"Generated","Weight":0.97}},{"co":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"corp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"corporation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"corps":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"employer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"enterprise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"company nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"company title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"company label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"company tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"customer.full_name":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"fullName"}},"State":"Generated","Terms":[{"full name":{"State":"Generated"}},{"fullName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"full nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full surname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"complete name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"entire name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"whole name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"full given name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"customer.culture":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"culture"}},"State":"Generated","Terms":[{"culture":{"State":"Generated"}},{"ethos":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"philosophy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"art, music, and literature":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"customer.email":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"email"}},"State":"Generated","Terms":[{"email":{"State":"Generated"}},{"correspondence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"message":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"communication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"customer.phone":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"phone"}},"State":"Generated","Terms":[{"phone":{"State":"Generated"}},{"handset":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"receiver":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"headset":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"telephone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mobile":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"customer.address":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"address"}},"State":"Generated","Terms":[{"address":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"residence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"customer.city":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"city"}},"State":"Generated","Terms":[{"city":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"customer.region":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"region"}},"State":"Generated","Terms":[{"region":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}},{"province":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"district":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"zone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"continent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"customer.country":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"country"}},"State":"Generated","Terms":[{"country":{"State":"Generated"}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"customer.postal_code":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"postalCode"}},"State":"Generated","Terms":[{"postal code":{"State":"Generated"}},{"postalCode":{"Type":"Noun","State":"Generated","Weight":0.99}},{"postal id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"postal key":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"customer.registration_date":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"registrationDate"}},"State":"Generated","Terms":[{"registration date":{"State":"Generated"}},{"registrationDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"registration moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"registration period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"customer.loyalty_point":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"loyaltyPoints"}},"State":"Generated","Terms":[{"loyalty point":{"State":"Generated"}},{"loyaltyPoints":{"Type":"Noun","State":"Generated","Weight":0.99}},{"point":{"State":"Generated","Weight":0.97}},{"loyalty opinion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"loyalty fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"loyalty idea":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"loyalty argument":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"loyalty topic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"opinion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"idea":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"argument":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"topic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"customer.credit_limit":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"creditLimit"}},"State":"Generated","Terms":[{"credit limit":{"State":"Generated"}},{"creditLimit":{"Type":"Noun","State":"Generated","Weight":0.99}},{"limit":{"State":"Generated","Weight":0.97}},{"credit boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"credit perimeter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"perimeter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"credit bound":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"credit border":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"credit edge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"credit frontier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"bound":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"border":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"customer.customer_segment":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"customerSegment"}},"State":"Generated","Terms":[{"customer segment":{"State":"Generated"}},{"customerSegment":{"Type":"Noun","State":"Generated","Weight":0.99}},{"segment":{"State":"Generated","Weight":0.97}},{"customer division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"customer subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"customer section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer sector":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer bit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer fragment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"customer.preferred_contact":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"preferredContact"}},"State":"Generated","Terms":[{"preferred contact":{"State":"Generated"}},{"preferredContact":{"Type":"Noun","State":"Generated","Weight":0.99}},{"contact":{"State":"Generated","Weight":0.97}},{"preferred connection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"preferred interaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"connection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"interaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"preferred phone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"preferred telephone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"preferred communication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"preferred e-mail":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"preferred link":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"preferred reach":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"customer.lifetime_value":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"lifetimeValue"}},"State":"Generated","Terms":[{"lifetime value":{"State":"Generated"}},{"lifetimeValue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"lifetime assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"lifetime worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lifetime price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lifetime cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lifetime charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lifetime rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lifetime importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"lifetime significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"lifetime usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"lifetime consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"customer.industry":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"industry"}},"State":"Generated","Terms":[{"industry":{"State":"Generated"}},{"commerce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"production":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"manufacturing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"business":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"engineering":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"diligence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"productiveness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"conscientiousness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"activity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"customer.tax_id":{"Definition":{"Binding":{"ConceptualEntity":"customers","ConceptualProperty":"taxId"}},"State":"Generated","Terms":[{"tax id":{"State":"Generated"}},{"taxId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"tax":{"State":"Generated","Weight":0.97}},{"tax identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"tax identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"tax identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"tax credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"duty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"levy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"toll":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"due":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"excise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"tariff":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"salesperson":{"Definition":{"Binding":{"ConceptualEntity":"salespeople"}},"State":"Generated","Terms":[{"salesperson":{"State":"Generated"}},{"salesclerk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"floorwalker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"seller":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"vender":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"vendor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"retailer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"wholesaler":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"dealer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"hawker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"purveyor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"salesperson.salesperson_id":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"salespersonId"}},"State":"Generated","Terms":[{"salesperson id":{"State":"Generated"}},{"id":{"State":"Generated","Weight":0.97}},{"salespersonId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"salesperson identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesperson credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"NameType":"Identifier"},"salesperson.first_name":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"firstName"}},"State":"Generated","Terms":[{"first name":{"State":"Generated"}},{"firstName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"first nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"1st name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"salesperson.last_name":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"lastName"}},"State":"Generated","Terms":[{"last name":{"State":"Generated"}},{"lastName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"last nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"end name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"final name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"closing name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"concluding name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"finishing name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"former name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"salesperson.full_name":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"fullName"}},"State":"Generated","Terms":[{"full name":{"State":"Generated"}},{"name":{"State":"Generated","Weight":0.97}},{"fullName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"full nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full surname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"complete name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"entire name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"whole name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"full given name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"Enter Salesman Name":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Salesman Name":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}],"NameType":"Name"},"salesperson.culture":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"culture"}},"State":"Generated","Terms":[{"culture":{"State":"Generated"}},{"ethos":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"philosophy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"art, music, and literature":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"salesperson.email":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"email"}},"State":"Generated","Terms":[{"email":{"State":"Generated"}},{"correspondence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"message":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"communication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"salesperson.phone":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"phone"}},"State":"Generated","Terms":[{"phone":{"State":"Generated"}},{"handset":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"receiver":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"headset":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"telephone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mobile":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"salesperson.hire_date":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"hireDate"}},"State":"Generated","Terms":[{"hire date":{"State":"Generated"}},{"hireDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"hire moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"hire period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"salesperson.region":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"region"}},"State":"Generated","Terms":[{"region":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}},{"province":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"district":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"zone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"continent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"salesperson.country":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"country"}},"State":"Generated","Terms":[{"country":{"State":"Generated"}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"salesperson.city":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"city"}},"State":"Generated","Terms":[{"city":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"salesperson.manager_id":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"managerId"}},"State":"Generated","Terms":[{"manager id":{"State":"Generated"}},{"managerId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"manager identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"salesperson.manager_name":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"managerName"}},"State":"Generated","Terms":[{"manager name":{"State":"Generated"}},{"managerName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"manager nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"manager title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"manager label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"manager tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"salesperson.commission_rate":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"commissionRate"}},"State":"Generated","Terms":[{"commission rate":{"State":"Generated"}},{"commissionRate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"rate":{"State":"Generated","Weight":0.97}},{"commission degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"commission frequency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"commission percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"commission ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"commission quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"commission amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"commission proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"salesperson.performance_rating":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"performanceRating"}},"State":"Generated","Terms":[{"performance rating":{"State":"Generated"}},{"performanceRating":{"Type":"Noun","State":"Generated","Weight":0.99}},{"performance assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"performance evaluation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"performance score":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance ranking":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance sailor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"performance seaman":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"performance hand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"salesperson.years_experience":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"yearsExperience"}},"State":"Generated","Terms":[{"years experience":{"State":"Generated"}},{"year experience":{"Type":"Noun","State":"Generated","Weight":0.78}},{"yearsExperience":{"Type":"Noun","State":"Generated","Weight":0.99}},{"experience":{"State":"Generated","Weight":0.97}},{"year knowledge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year involvement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year skill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year familiarity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year knowhow":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year capability":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year proficiency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"knowledge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"involvement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"skill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"salesperson.sales_target":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"salesTarget"}},"State":"Generated","Terms":[{"sales target":{"State":"Generated"}},{"sale target":{"Type":"Noun","State":"Generated","Weight":0.78}},{"salesTarget":{"Type":"Noun","State":"Generated","Weight":0.99}},{"target":{"State":"Generated","Weight":0.97}},{"sale focus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sale objective":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"focus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"objective":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"salesperson.achievement_percent":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"achievementPercent"}},"State":"Generated","Terms":[{"achievement percent":{"State":"Generated"}},{"achievementPercent":{"Type":"Noun","State":"Generated","Weight":0.99}},{"achievement percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"achievement ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"achievement percentile":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"achievement part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"achievement proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"achievement fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"salesperson.employment_status":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"employmentStatus"}},"State":"Generated","Terms":[{"employment status":{"State":"Generated"}},{"employmentStatus":{"Type":"Noun","State":"Generated","Weight":0.99}},{"status":{"State":"Generated","Weight":0.97}},{"employment category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"employment importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"employment prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"employment prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"employment condition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"employment class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"employment grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"salesperson.language_spoken":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"languagesSpoken"}},"State":"Generated","Terms":[{"language spoken":{"State":"Generated"}},{"languagesSpoken":{"Type":"Noun","State":"Generated","Weight":0.99}},{"idiom spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"lingo spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"dialect spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"patois spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"tongue spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"vernacular spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"argot spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"jargon spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"speech spoken":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.451}}]},"salesperson.certification":{"Definition":{"Binding":{"ConceptualEntity":"salespeople","ConceptualProperty":"certifications"}},"State":"Generated","Terms":[{"certification":{"State":"Generated"}},{"documentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"authorization":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"accreditation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"endorsement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"guarantee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"warranty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"manager":{"Definition":{"Binding":{"ConceptualEntity":"managers"}},"State":"Generated","Terms":[{"manager":{"State":"Generated"}},{"director":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"administrator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"supervisor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"leader":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"boss":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"executive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"chief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"superior":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"manager.manager_id":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"managerId"}},"State":"Generated","Terms":[{"manager id":{"State":"Generated"}},{"id":{"State":"Generated","Weight":0.97}},{"managerId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"manager identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"manager credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"NameType":"Identifier"},"manager.first_name":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"firstName"}},"State":"Generated","Terms":[{"first name":{"State":"Generated"}},{"name":{"State":"Generated","Weight":0.97}},{"firstName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"first nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"first tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"1st name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"NameType":"Name"},"manager.last_name":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"lastName"}},"State":"Generated","Terms":[{"last name":{"State":"Generated"}},{"name":{"State":"Generated","Weight":0.97}},{"lastName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"last nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"last tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"end name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"final name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"closing name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"concluding name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"finishing name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"former name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"NameType":"Name"},"manager.full_name":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"fullName"}},"State":"Generated","Terms":[{"full name":{"State":"Generated"}},{"name":{"State":"Generated","Weight":0.97}},{"fullName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"full nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"full surname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"complete name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"entire name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"whole name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"full given name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}],"NameType":"Name"},"manager.culture":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"culture"}},"State":"Generated","Terms":[{"culture":{"State":"Generated"}},{"ethos":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"philosophy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"art, music, and literature":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"manager.email":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"email"}},"State":"Generated","Terms":[{"email":{"State":"Generated"}},{"correspondence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"message":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"communication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"manager.phone":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"phone"}},"State":"Generated","Terms":[{"phone":{"State":"Generated"}},{"handset":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"receiver":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"headset":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"telephone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mobile":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"manager.region":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"region"}},"State":"Generated","Terms":[{"region":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}},{"province":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"district":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"zone":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"continent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"manager.country":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"country"}},"State":"Generated","Terms":[{"country":{"State":"Generated"}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"manager.city":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"city"}},"State":"Generated","Terms":[{"city":{"State":"Generated"}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"manager.hire_date":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"hireDate"}},"State":"Generated","Terms":[{"hire date":{"State":"Generated"}},{"hireDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"hire moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"hire period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"manager.department":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"department"}},"State":"Generated","Terms":[{"department":{"State":"Generated"}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"branch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"sector":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"responsibility":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"specialty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"realm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"sphere":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"manager.performance_rating":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"performanceRating"}},"State":"Generated","Terms":[{"performance rating":{"State":"Generated"}},{"performanceRating":{"Type":"Noun","State":"Generated","Weight":0.99}},{"performance assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"performance evaluation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"performance score":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance ranking":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"performance sailor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"performance seaman":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"performance hand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"manager.years_experience":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"yearsExperience"}},"State":"Generated","Terms":[{"years experience":{"State":"Generated"}},{"year experience":{"Type":"Noun","State":"Generated","Weight":0.78}},{"yearsExperience":{"Type":"Noun","State":"Generated","Weight":0.99}},{"experience":{"State":"Generated","Weight":0.97}},{"year knowledge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year involvement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year skill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year familiarity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year knowhow":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year capability":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year proficiency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"knowledge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"involvement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"skill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"manager.report_to":{"Definition":{"Binding":{"ConceptualEntity":"managers","ConceptualProperty":"reportsTo"}},"State":"Generated","Terms":[{"report to":{"State":"Generated"}},{"reportsTo":{"Type":"Noun","State":"Generated","Weight":0.99}},{"information to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"commentary to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"description to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"presentation to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"statement to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"forecast to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"account to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"narrative to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"paper to":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"calendar":{"Definition":{"Binding":{"ConceptualEntity":"Calendar"}},"State":"Generated","Terms":[{"calendar":{"State":"Generated"}},{"almanac":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"datebook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"agenda":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"logbook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"diary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"schedule":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"all_measure":{"Definition":{"Binding":{"ConceptualEntity":"All Measures"}},"State":"Generated","Terms":[{"all measure":{"State":"Generated"}},{"measure":{"State":"Generated","Weight":0.97}},{"all degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"all quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"all quota":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"all extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quota":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"all amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"all portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"all ration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.total_customers_till_date":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Total Customers Till Date"}},"State":"Generated","Terms":[{"total customers till date":{"State":"Generated"}},{"till date":{"State":"Generated","Weight":0.97}},{"customers till date":{"State":"Generated","Weight":0.97}},{"customers":{"State":"Generated","Weight":0.97}},{"total customers":{"State":"Generated","Weight":0.97}},{"till moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"till period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"total customer till moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"customer till moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"aggregate customer till date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"overall customer till date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"total customer till period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"customer till period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"aggregate customer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall customer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"all_measure.MTD_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MTD Revenue"}},"State":"Generated","Terms":[{"MTD revenue":{"State":"Generated"}},{"mtd income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"mtd turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"mtd yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.YTD_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD Revenue"}},"State":"Generated","Terms":[{"YTD revenue":{"State":"Generated"}},{"ytd income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"ytd turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"ytd yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"year to date revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.48}}]},"all_measure.prev_month_revenue_PREVIOUSMONTH":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Prev Month Revenue (PREVIOUSMONTH)"}},"State":"Generated","Terms":[{"prev month revenue (PREVIOUSMONTH)":{"State":"Generated"}},{"prev month revenue":{"State":"Generated","Weight":0.75}}]},"all_measure.previous_month_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Revenue"}},"State":"Generated","Terms":[{"previous month revenue":{"State":"Generated"}},{"month revenue":{"State":"Generated","Weight":0.97}},{"previous month income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"month income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"previous month turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"previous month yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"month turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"previous mth revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"mth revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"all_measure.previous_month_revenue_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Revenue (From MTD)"}},"State":"Generated","Terms":[{"previous month revenue (from MTD)":{"State":"Generated"}},{"previous month revenue":{"State":"Generated","Weight":0.75}}]},"all_measure.previous_month_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Title"}},"State":"Generated","Terms":[{"previous month title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"previous month designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"previous month name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"previous month award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"previous month call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"previous month heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"previous month label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"all_measure.current_month_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Current Month Title"}},"State":"Generated","Terms":[{"current month title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"current month designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"current month name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current month award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current month call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current month heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current month label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"all_measure.total_cost":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Total Cost"}},"State":"Generated","Terms":[{"total cost":{"State":"Generated"}},{"cost":{"State":"Generated","Weight":0.97}},{"aggregate cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"total expenditure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"all_measure.MoM__revenue_change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Revenue Change"}},"State":"Generated","Terms":[{"MoM % revenue change":{"State":"Generated"}},{"mom percentage revenue change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"mom % income change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"mom pct revenue change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mom % turnover change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mom % yield change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mom % revenue alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % revenue modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % revenue variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % revenue transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % revenue revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"all_measure.previous_year_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Revenue"}},"State":"Generated","Terms":[{"previous year revenue":{"State":"Generated"}},{"year revenue":{"State":"Generated","Weight":0.97}},{"previous year income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"year income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"previous year turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"previous year yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"year turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"year yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"previous yr revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"yr revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"all_measure.YoY__revenue_change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Revenue Change"}},"State":"Generated","Terms":[{"YoY % revenue change":{"State":"Generated"}},{"yoy percentage revenue change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"yoy % income change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"yoy pct revenue change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % turnover change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % yield change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % revenue alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % revenue modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % revenue variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % revenue transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % revenue revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"all_measure.previous_month_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Profit"}},"State":"Generated","Terms":[{"previous month profit":{"State":"Generated"}},{"month profit":{"State":"Generated","Weight":0.97}},{"previous mth profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"mth profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"previous month income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"month income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"previous month turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"previous month return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"previous month yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"month turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"month return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"month yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.previous_year_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Profit"}},"State":"Generated","Terms":[{"previous year profit":{"State":"Generated"}},{"year profit":{"State":"Generated","Weight":0.97}},{"previous yr profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"yr profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"previous year income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"year income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"previous year turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"previous year return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"previous year yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"year turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"year return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"year yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.YoY__profit_change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Profit Change"}},"State":"Generated","Terms":[{"YoY % profit change":{"State":"Generated"}},{"yoy percentage profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"yoy pct profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % profit alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"all_measure.YTD_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD Profit"}},"State":"Generated","Terms":[{"YTD profit":{"State":"Generated"}},{"ytd income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ytd turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ytd return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ytd yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"year to date profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.48}},{"ytd advantage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"ytd gain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"ytd benefit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"ytd use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"ytd reward":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"all_measure.MTD_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MTD Profit"}},"State":"Generated","Terms":[{"MTD profit":{"State":"Generated"}},{"mtd income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"mtd turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mtd return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mtd yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mtd advantage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"mtd gain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"mtd benefit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"mtd use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"mtd reward":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"mtd good":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"all_measure.MoM__profit_change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Profit Change"}},"State":"Generated","Terms":[{"MoM % profit change":{"State":"Generated"}},{"mom percentage profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"mom pct profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mom % profit alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mom % profit amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"all_measure.gap_from_last_month_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Gap From Last Month Revenue"}},"State":"Generated","Terms":[{"% gap from last month revenue":{"State":"Generated"}}]},"all_measure.YoY__revenue_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Revenue Color"}},"State":"Generated","Terms":[{"YoY % revenue color":{"State":"Generated"}},{"yoy percentage revenue color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"yoy % income color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"yoy pct revenue color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % turnover color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % yield color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % revenue hue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % revenue tint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % revenue shade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % revenue dye":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % revenue paint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"all_measure.YoY__profit_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Profit Color"}},"State":"Generated","Terms":[{"YoY % profit color":{"State":"Generated"}},{"yoy percentage profit color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"yoy pct profit color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yoy % profit hue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"yoy % profit tint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % profit shade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % profit dye":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % profit paint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"yoy % profit pigment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"all_measure.gap_last_month_revenue_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Gap Last Month Revenue Color"}},"State":"Generated","Terms":[{"% gap last month revenue color":{"State":"Generated"}}]},"all_measure.MTD_profit__display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MTD Profit % Display"}},"State":"Generated","Terms":[{"MTD profit % display":{"State":"Generated"}},{"mtd profit percentage display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"mtd profit pct display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mtd profit % exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd profit % presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd profit % demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd profit % spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd profit % ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd profit % pageant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd profit % show":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"mtd profit % parade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"all_measure.new_customers":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD New Customers"}},"State":"Generated","Terms":[{"new customers":{"State":"Generated"}},{"customers":{"State":"Generated","Weight":0.97}},{"new clientele":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"new patron":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"new client":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"new consumer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"new punter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"clientele":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"patron":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"client":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"consumer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"punter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"all_measure.registered_customers_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Registered Customers Title"}},"State":"Generated","Terms":[{"registered customers title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"customers title":{"State":"Generated","Weight":0.97}},{"registered customer designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"customer designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"registered customer name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"registered customer award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"registered customer call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"registered customer heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"registered customer label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"customer award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"customer call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.previous_month_profit_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Profit (From MTD)"}},"State":"Generated","Terms":[{"previous month profit (from MTD)":{"State":"Generated"}},{"previous month profit":{"State":"Generated","Weight":0.75}}]},"all_measure.MoM__profit_change_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Profit Change (From MTD)"}},"State":"Generated","Terms":[{"MoM % profit change (from MTD)":{"State":"Generated"}},{"MoM % profit change":{"State":"Generated","Weight":0.75}}]},"all_measure.MoM__profit_color_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Profit Color (From MTD)"}},"State":"Generated","Terms":[{"MoM % profit color (from MTD)":{"State":"Generated"}},{"MoM % profit color":{"State":"Generated","Weight":0.75}}]},"all_measure.month_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Month Title"}},"State":"Generated","Terms":[{"month title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"month designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"month award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"mth title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"all_measure.MTD_revenue__display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MTD Revenue % Display"}},"State":"Generated","Terms":[{"MTD revenue % display":{"State":"Generated"}},{"mtd income % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"mtd revenue percentage display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"mtd turnover % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mtd yield % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mtd revenue pct display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"mtd revenue % exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd revenue % presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd revenue % demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd revenue % spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mtd revenue % ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"all_measure.units_sold":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Units Sold"}},"State":"Generated","Terms":[{"units sold":{"State":"Generated"}},{"unit sold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}}]},"all_measure.MTD_units_sold":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MTD Units Sold"}},"State":"Generated","Terms":[{"MTD units sold":{"State":"Generated"}},{"mtd unit sold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.846}}]},"all_measure.previous_month_sales":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Sales"}},"State":"Generated","Terms":[{"previous month sales":{"State":"Generated"}},{"sales":{"State":"Generated","Weight":0.97}},{"month sales":{"State":"Generated","Weight":0.97}},{"previous month sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"month sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"previous mth sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"mth sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"all_measure.previous_month_sales_quantity_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Month Sales Quantity (From MTD)"}},"State":"Generated","Terms":[{"previous month sales quantity (from MTD)":{"State":"Generated"}},{"previous month sales quantity":{"State":"Generated","Weight":0.75}}]},"all_measure.MoM__sales_quantity_change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Sales Quantity Change"}},"State":"Generated","Terms":[{"MoM % sales quantity change":{"State":"Generated"}},{"mom percentage sale quantity change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"mom pct sale quantity change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"mom % sale quantity change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"mom % sale quantity alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mom % sale quantity modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mom % sale quantity variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mom % sale quantity transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mom % sale quantity revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mom % sale quantity conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mom % sale quantity adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}}]},"all_measure.MTD_units_sold__display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MTD Units Sold % Display"}},"State":"Generated","Terms":[{"MTD units sold % display":{"State":"Generated"}},{"mtd unit sold % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.693}},{"mtd unit sold percentage display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"mtd unit sold pct display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"mtd unit sold % exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mtd unit sold % presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mtd unit sold % demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mtd unit sold % spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mtd unit sold % ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mtd unit sold % pageant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"mtd unit sold % show":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"all_measure.selected_period_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Selected Period Title"}},"State":"Generated","Terms":[{"selected period title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"period title":{"State":"Generated","Weight":0.97}},{"selected period designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"period designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"selected period name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"selected period award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"selected period call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"selected period heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"selected period label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"period award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.previous_year_revenue_from_YTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Revenue (From YTD)"}},"State":"Generated","Terms":[{"previous year revenue (from YTD)":{"State":"Generated"}},{"previous year revenue":{"State":"Generated","Weight":0.75}}]},"all_measure.gap_from_last_year_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Gap From Last Year Revenue"}},"State":"Generated","Terms":[{"% gap from last year revenue":{"State":"Generated"}}]},"all_measure.YTD_revenue__display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD Revenue % Display"}},"State":"Generated","Terms":[{"YTD revenue % display":{"State":"Generated"}},{"ytd income % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"ytd revenue percentage display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"ytd turnover % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"ytd yield % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"ytd revenue pct display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"ytd revenue % exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"year to date revenue % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd revenue % presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd revenue % demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd revenue % spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"all_measure.prev_year_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Prev Year Title"}},"State":"Generated","Terms":[{"prev year title":{"State":"Generated"}},{"prev year designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"prev year name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"prev year award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"prev year call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"prev year heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"prev year label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"prev yr title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}}]},"all_measure.previous_year_revenue_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Previous Year Revenue Color"}},"State":"Generated","Terms":[{"% previous year revenue color":{"State":"Generated"}},{"percentage previous year revenue color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"% previous yr revenue color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"% previous year income color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"pct previous year revenue color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"% previous year turnover color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"% previous year yield color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"% previous year revenue hue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"% previous year revenue tint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"% previous year revenue shade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"% previous year revenue dye":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"all_measure.MoM__revenue_color_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Revenue Color (From MTD)"}},"State":"Generated","Terms":[{"MoM % revenue color (from MTD)":{"State":"Generated"}},{"MoM % revenue color":{"State":"Generated","Weight":0.75}}]},"all_measure.MoM__units_sold_color_from_MTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"MoM % Units Sold Color (From MTD)"}},"State":"Generated","Terms":[{"MoM % units sold color (from MTD)":{"State":"Generated"}},{"MoM % units sold color":{"State":"Generated","Weight":0.75}}]},"datedate":{"Definition":{"Binding":{"ConceptualEntity":"Date(Date)"}},"State":"Generated","Terms":[{"date(date)":{"State":"Generated"}},{"moment (date)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"date( moment )":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"period (date)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"date( period )":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"datedate.datedate":{"Definition":{"Binding":{"ConceptualEntity":"Date(Date)","ConceptualProperty":"Date(Date)"}},"State":"Generated","Terms":[{"date(date)":{"State":"Generated"}},{"date(date) name":{"State":"Generated"}},{"date":{"State":"Generated","Weight":0.75}},{"moment (date)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"date( moment )":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"period (date)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"date( period )":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}],"NameType":"Name"},"datedate.datedate_field":{"Definition":{"Binding":{"ConceptualEntity":"Date(Date)","ConceptualProperty":"Date(Date) Fields"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"date(date) field":{"State":"Generated"}},{"moment (date) field":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"date( moment ) field":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"period (date) field":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"date( period ) field":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"date(date) arena":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"date(date) turf":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"date(date) ground":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"date(date) pitch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"date(date) park":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"date(date) meadow":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.494}}]},"datedate.datedate_order":{"Definition":{"Binding":{"ConceptualEntity":"Date(Date)","ConceptualProperty":"Date(Date) Order"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"date(date) order":{"State":"Generated"}},{"moment (date) order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"date( moment ) order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"period (date) order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"date( period ) order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"date(date) instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"date(date) direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"date(date) edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"date(date) command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"date(date) directive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"date(date) demand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"time_period":{"Definition":{"Binding":{"ConceptualEntity":"Time Period"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"time period":{"State":"Generated"}},{"period":{"State":"Generated","Weight":0.97}},{"duration period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"interval period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"moment period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"timetable period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"time era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"time epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"time age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"time_period.label":{"Definition":{"Binding":{"ConceptualEntity":"Time Period","ConceptualProperty":"Label"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"label":{"State":"Generated"}},{"sticker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"decal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"name tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.571}}]},"time_period.data":{"Definition":{"Binding":{"ConceptualEntity":"Time Period","ConceptualProperty":"Data"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"data":{"State":"Generated"}},{"information":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"info":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"statistic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"document":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"figure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"record":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"sales_item.total_revenue_lineTotal__taxAmount":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"Total Revenue (lineTotal & taxAmount)"}},"State":"Generated","Terms":[{"total revenue (lineTotal & taxAmount)":{"State":"Generated"}},{"total revenue":{"State":"Generated","Weight":0.75}}]},"all_measure.previous_year_profit_from_YTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Profit (From YTD)"}},"State":"Generated","Terms":[{"previous year profit (from YTD)":{"State":"Generated"}},{"previous year profit":{"State":"Generated","Weight":0.75}}]},"all_measure.gap_from_last_year_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Gap From Last Year Profit"}},"State":"Generated","Terms":[{"% gap from last year profit":{"State":"Generated"}}]},"all_measure.YTD_profit__display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD Profit % Display"}},"State":"Generated","Terms":[{"YTD profit % display":{"State":"Generated"}},{"ytd profit percentage display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"ytd profit pct display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"ytd profit % exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"year to date profit % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd profit % presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd profit % demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd profit % spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd profit % ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd profit % pageant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ytd profit % show":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"all_measure.previous_year_profit_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Previous Year Profit Color"}},"State":"Generated","Terms":[{"% previous year profit color":{"State":"Generated"}},{"percentage previous year profit color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"% previous yr profit color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"pct previous year profit color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"% previous year profit hue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"% previous year profit tint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"% previous year profit shade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"% previous year profit dye":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"% previous year profit paint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"% previous year profit pigment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"all_measure.cogs":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"COGS"}},"State":"Generated","Terms":[{"cogs":{"State":"Generated"}},{"mechanism":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"device":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"workings":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"works":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cogwheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"gearwheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"flywheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"component":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"gear":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.YoY__revenue_change_display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Revenue Change Display"}},"State":"Generated","Terms":[{"YoY % revenue change display":{"State":"Generated"}},{"yoy percentage revenue change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"yoy % income change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"yoy pct revenue change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yoy % turnover change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yoy % yield change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yoy % revenue change exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % revenue change presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % revenue change demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % revenue change spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % revenue change ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}}]},"top_n_products_by_revenue":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Revenue)"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"top n products (by revenue)":{"State":"Generated"}},{"top n product (by revenue)":{"Type":"Noun","State":"Generated","Weight":0.78}}]},"top_n_products_by_revenue.product_id":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Revenue)","ConceptualProperty":"productId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product id":{"State":"Generated"}},{"productId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"merchandise id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n_products_by_revenue.revenue":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Revenue)","ConceptualProperty":"Revenue"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"revenue":{"State":"Generated"}},{"income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"top_n_products_by_revenue.product_name":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Revenue)","ConceptualProperty":"productName"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product name":{"State":"Generated"}},{"productName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"item name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"merchandise name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n":{"Definition":{"Binding":{"ConceptualEntity":"Top N"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"top n":{"State":"Generated"}},{"n":{"State":"Generated","Weight":0.97}},{"best n":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"first n":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"leading n":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"maximum n":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"peak n":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"upper n":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n.value":{"Definition":{"Binding":{"ConceptualEntity":"Top N","ConceptualProperty":"Value"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"value":{"State":"Generated"}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"meaning":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"merit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"top_n_products_by_sales_quantity":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Sales Quantity)"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"top n products (by sales quantity)":{"State":"Generated"}},{"top n product (by sale quantity)":{"Type":"Noun","State":"Generated","Weight":0.78}}]},"top_n_products_by_sales_quantity.product_id":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Sales Quantity)","ConceptualProperty":"productId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product id":{"State":"Generated"}},{"productId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"merchandise id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n_products_by_sales_quantity.product_name":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Sales Quantity)","ConceptualProperty":"productName"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product name":{"State":"Generated"}},{"productName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"item name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"merchandise name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n_products_by_sales_quantity.quantity":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Sales Quantity)","ConceptualProperty":"Quantity"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"quantity":{"State":"Generated"}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"top_n_products_by_profit":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Profit)"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"top n products (by profit)":{"State":"Generated"}},{"top n product (by profit)":{"Type":"Noun","State":"Generated","Weight":0.78}}]},"top_n_products_by_profit.product_id":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Profit)","ConceptualProperty":"productId"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product id":{"State":"Generated"}},{"productId":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"product credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"merchandise id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n_products_by_profit.product_name":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Profit)","ConceptualProperty":"productName"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"product name":{"State":"Generated"}},{"productName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"artifact name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"item name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"merchandise name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"produce name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"top_n_products_by_profit.profit":{"Definition":{"Binding":{"ConceptualEntity":"Top N Products (By Profit)","ConceptualProperty":"Profit"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"profit":{"State":"Generated"}},{"income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"advantage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"gain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"benefit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"reward":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"good":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.previous_year_sales":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Sales"}},"State":"Generated","Terms":[{"previous year sales":{"State":"Generated"}},{"sales":{"State":"Generated","Weight":0.97}},{"year sales":{"State":"Generated","Weight":0.97}},{"previous year sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"year sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"previous yr sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"yr sale":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"all_measure.YoY__units_sold_change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Units Sold Change"}},"State":"Generated","Terms":[{"YoY % units sold change":{"State":"Generated"}},{"yoy % unit sold change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.693}},{"yoy percentage unit sold change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"yoy pct unit sold change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yoy % unit sold alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}}]},"all_measure.YoY__units_sold_change_display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Units Sold Change Display"}},"State":"Generated","Terms":[{"YoY % units sold change display":{"State":"Generated"}}]},"all_measure.YTD_units_sold":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD Units Sold"}},"State":"Generated","Terms":[{"YTD units sold":{"State":"Generated"}},{"ytd unit sold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.846}},{"year to date unit sold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.498}}]},"all_measure.total_orders":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Total Orders"}},"State":"Generated","Terms":[{"total orders":{"State":"Generated"}},{"orders":{"State":"Generated","Weight":0.97}},{"aggregate order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total guideline":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total preparation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"total direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"guideline":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"preparation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"Orders Delivered":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.active_sales_team":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Active Sales Team"}},"State":"Generated","Terms":[{"active sales team":{"State":"Generated"}},{"team":{"State":"Generated","Weight":0.97}},{"sales team":{"State":"Generated","Weight":0.97}},{"active sale team":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"sale team":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"active sale lineup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"sale lineup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"active sale side":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"active sale squad":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"active sale crew":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"active sale club":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"lineup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"sale side":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.managers":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Managers"}},"State":"Generated","Terms":[{"managers":{"State":"Generated"}},{"director":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"administrator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"supervisor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"leader":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"boss":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"executive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"chief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"superior":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"all_measure.achievement_":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Achievement %"}},"State":"Generated","Terms":[{"achievement %":{"State":"Generated"}},{"achievement percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"achievement pct":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.inactive_sales_team":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Inactive Sales Team"}},"State":"Generated","Terms":[{"inactive sales team":{"State":"Generated"}},{"team":{"State":"Generated","Weight":0.97}},{"sales team":{"State":"Generated","Weight":0.97}},{"inactive sale team":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"sale team":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"inactive sale lineup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"sale lineup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"inactive sale side":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"inactive sale squad":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"inactive sale crew":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"inactive sale club":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"lineup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"sale side":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"calendar.start_of_quarter":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Start Of Quarter"}},"State":"Generated","Terms":[{"start of quarter":{"State":"Generated"}},{"start":{"State":"Generated","Weight":0.97}},{"start of qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.677}},{"twitch of quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"jump of quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"jerk of quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"flinch of quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"jolt of quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"twitch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"jump":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"jerk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"flinch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}],"SemanticType":"Time"},"calendar.start_of_month":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Start Of Month"}},"State":"Generated","Terms":[{"start of month":{"State":"Generated"}},{"start":{"State":"Generated","Weight":0.97}},{"start of mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"twitch of month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"jump of month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"jerk of month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"flinch of month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"jolt of month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"twitch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"jump":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"jerk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"flinch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}],"SemanticType":"Time"},"calendar.quarter":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Quarter"}},"State":"Generated","Terms":[{"quarter":{"State":"Generated"}},{"qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}}]},"calendar.year":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Year"}},"State":"Generated","Terms":[{"year":{"State":"Generated"}},{"yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"calendar.month":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Month"}},"State":"Generated","Terms":[{"month":{"State":"Generated"}},{"mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"calendar.quarter_name":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Quarter Name"}},"State":"Generated","Terms":[{"quarter name":{"State":"Generated"}},{"quarter nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"quarter title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"quarter label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"quarter tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"qtr name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.667}}]},"calendar.week":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Week"}},"State":"Generated","Terms":[{"week":{"State":"Generated"}}]},"calendar.weekday":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Weekday"}},"State":"Generated","Terms":[{"weekday":{"State":"Generated"}},{"ordinary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"standard":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"basic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"routine":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"calendar.day_num":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Day Num"}},"State":"Generated","Terms":[{"day num":{"State":"Generated"}},{"day number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"calendar.month_name":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Month Name"}},"State":"Generated","Terms":[{"month name":{"State":"Generated"}},{"month nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"mth name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"Month":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"calendar.day_name":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Day Name"}},"State":"Generated","Terms":[{"day name":{"State":"Generated"}},{"day nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"day title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"day label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"day tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.adjusted_gross_profit":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Adjusted Gross Profit"}},"State":"Generated","Terms":[{"adjusted gross profit":{"State":"Generated"}},{"adjusted aggregate profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.657}},{"adjusted overall profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.657}},{"adjusted whole profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.657}},{"adjusted sum profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"adjusted total profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"adjusted gross income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"adjusted gross revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"adjusted gross turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"adjusted gross return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"adjusted gross yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"all_measure.adjusted_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Adjusted Revenue"}},"State":"Generated","Terms":[{"adjusted revenue":{"State":"Generated"}},{"adjusted income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"adjusted profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"adjusted turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"adjusted yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"percentage_adjustment":{"Definition":{"Binding":{"ConceptualEntity":"Percentage Adjustment"}},"State":"Generated","Terms":[{"percentage adjustment":{"State":"Generated"}},{"adjustment":{"State":"Generated","Weight":0.97}},{"percentage alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"percentage modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"percentage regulation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"percentage correction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"percentage amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"percentage variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"regulation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"correction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"percentage_adjustment.percentage_adjustment_":{"Definition":{"Binding":{"ConceptualEntity":"Percentage Adjustment","ConceptualProperty":"Percentage Adjustment %"}},"State":"Generated","Terms":[{"percentage adjustment %":{"State":"Generated"}},{"percentage adjustment percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"percentage adjustment pct":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"percentage_adjustment.percentage_adjustment_value":{"Definition":{"Binding":{"ConceptualEntity":"Percentage Adjustment","ConceptualProperty":"Percentage Adjustment Value"}},"State":"Generated","Terms":[{"percentage adjustment value":{"State":"Generated"}},{"adjustment value":{"State":"Generated","Weight":0.97}},{"percentage adjustment assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"adjustment assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"percentage adjustment worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"percentage adjustment price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"percentage adjustment cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"percentage adjustment charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"percentage adjustment rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"adjustment worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"adjustment price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"adjustment cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.average_order_value":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Average Order Value"}},"State":"Generated","Terms":[{"average order value":{"State":"Generated"}},{"order value":{"State":"Generated","Weight":0.97}},{"average order assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"order assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"average order worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"average order price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"average order cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"average order charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"average order rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"order worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"order price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"order cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"Avg Order Value":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.top_performing_region__country_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Top Performing Region | Country Title"}},"State":"Generated","Terms":[{"top performing region | country title":{"State":"Generated"}}]},"all_measure.salesman_name_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Salesman Name Title"}},"State":"Generated","Terms":[{"salesman name title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"name title":{"State":"Generated","Weight":0.97}},{"salesman name designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"name designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"salesman name name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"salesman name award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"salesman name call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"salesman name heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"salesman name label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"name name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"name award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.YoY__profit_change_display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Profit Change Display"}},"State":"Generated","Terms":[{"YoY % profit change display":{"State":"Generated"}},{"yoy percentage profit change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"yoy pct profit change display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yoy % profit change exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % profit change presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % profit change demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % profit change spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % profit change ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % profit change pageant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % profit change show":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"yoy % profit change parade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"all_measure.YoY__units_sold_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YoY % Units Sold Color"}},"State":"Generated","Terms":[{"YoY % units sold color":{"State":"Generated"}},{"yoy % unit sold color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.693}},{"yoy percentage unit sold color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"yoy pct unit sold color":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yoy % unit sold hue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"yoy % unit sold tint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"yoy % unit sold shade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"yoy % unit sold dye":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"yoy % unit sold paint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"yoy % unit sold pigment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"all_measure.gap_from_last_year_units_sold":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Gap From Last Year Units Sold"}},"State":"Generated","Terms":[{"% gap from last year units sold":{"State":"Generated"}}]},"all_measure.previous_year_units_sold_from_YTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Units Sold (From YTD)"}},"State":"Generated","Terms":[{"previous year units sold (from YTD)":{"State":"Generated"}},{"previous year units sold":{"State":"Generated","Weight":0.75}}]},"all_measure.YTD_units_sold__display":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"YTD Units Sold % Display"}},"State":"Generated","Terms":[{"YTD units sold % display":{"State":"Generated"}},{"ytd unit sold % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.693}},{"ytd unit sold percentage display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"ytd unit sold pct display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"year to date unit sold % display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.528}},{"ytd unit sold % exhibition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"ytd unit sold % presentation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"ytd unit sold % demonstration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"ytd unit sold % spectacle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"ytd unit sold % ceremony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"ytd unit sold % pageant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}}]},"all_measure.increase___decrease_YoY":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Increase / Decrease (YoY)"}},"State":"Generated","Terms":[{"increase / decrease (YoY)":{"State":"Generated"}},{"increase / decrease":{"State":"Generated","Weight":0.75}},{"increase":{"State":"Generated","Weight":0.97}},{"increase decrease ( YoY )":{"State":"Generated","Weight":0.97}},{"decrease (YoY)":{"State":"Generated","Weight":0.97}},{"growth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"intensification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"escalation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"proliferation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"expansion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"multiplication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"buildup":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"upsurge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"surge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"rise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"all_measure.current_year_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Current Year Title"}},"State":"Generated","Terms":[{"current year title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"year title":{"State":"Generated","Weight":0.97}},{"current year designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"year designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"current year name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current year award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current year call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current year heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"current year label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"year name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"year award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.average_revenue":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Average Revenue"}},"State":"Generated","Terms":[{"average revenue":{"State":"Generated"}},{"average income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"average profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"average turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"average yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.previous_year_monthly_revenue_from_YTD":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Previous Year Monthly Revenue (From YTD)"}},"State":"Generated","Terms":[{"previous year monthly revenue (from YTD)":{"State":"Generated"}},{"previous year monthly revenue":{"State":"Generated","Weight":0.75}}]},"all_measure.revenue_forecast":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Revenue Forecast"}},"State":"Generated","Terms":[{"revenue forecast":{"State":"Generated"}},{"forecast":{"State":"Generated","Weight":0.97}},{"revenue prediction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"revenue projection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"prediction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"projection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"revenue report":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"revenue estimate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"report":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"estimate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"income forecast":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"profit forecast":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"all_measure.revenue_forecast_total":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Revenue Forecast Total"}},"State":"Generated","Terms":[{"revenue forecast total":{"State":"Generated"}},{"forecast total":{"State":"Generated","Weight":0.97}},{"revenue forecast aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"revenue forecast overall":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"forecast aggregate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"forecast overall":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"income forecast total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"revenue prediction total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"revenue projection total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"prediction total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"projection total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"profit forecast total":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}]},"all_measure.revenue_forecast__change":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Revenue Forecast % Change"}},"State":"Generated","Terms":[{"revenue forecast % change":{"State":"Generated"}},{"income forecast % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"revenue prediction % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"revenue projection % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"revenue forecast percentage change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"profit forecast % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"turnover forecast % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yield forecast % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"revenue report % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"revenue estimate % change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"revenue forecast pct change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"all_measure.region__country_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Region | Country Title"}},"State":"Generated","Terms":[{"region | country title":{"State":"Generated"}},{"region | country designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"region | country name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"region | country award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"region | country call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"region | country heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"region | country label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"location | country title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.686}},{"province | country title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"region | nation title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"region | location title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}}]},"all_measure.revenue_goal_monthly":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Revenue Goal (Monthly)"}},"State":"Generated","Terms":[{"revenue goal (monthly)":{"State":"Generated"}},{"revenue goal":{"State":"Generated","Weight":0.75}},{"income goal (monthly)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"profit goal (monthly)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"turnover goal (monthly)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"yield goal (monthly)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}}]},"all_measure.revenue_goal":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Revenue Goal (%)"}},"State":"Generated","Terms":[{"revenue goal":{"State":"Generated"}},{"revenue goal (%)":{"State":"Generated"}},{"goal":{"State":"Generated","Weight":0.97}},{"income goal (%)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"income goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"profit goal (%)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"turnover goal (%)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"yield goal (%)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"profit goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"turnover goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"yield goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"revenue goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}],"Units":["percentage","%"]},"all_measure.revenue_goal1":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Revenue Goal"}},"State":"Generated","Terms":[{"revenue goal":{"State":"Generated"}},{"goal":{"State":"Generated","Weight":0.97}},{"income goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"profit goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"turnover goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"yield goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"revenue goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"revenue box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"revenue area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"all_measure.increase___decrease_revenue_goal":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Increase / Decrease (Revenue Goal)"}},"State":"Generated","Terms":[{"increase / decrease (revenue goal)":{"State":"Generated"}},{"increase / decrease":{"State":"Generated","Weight":0.75}},{"increase":{"State":"Generated","Weight":0.97}},{"increase decrease ( revenue goal )":{"State":"Generated","Weight":0.97}},{"decrease (revenue goal)":{"State":"Generated","Weight":0.97}},{"decrease ( income goal)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"decrease ( profit goal)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"decrease ( turnover goal)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"decrease ( yield goal)":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"growth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"intensification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"escalation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"proliferation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"expansion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"multiplication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"all_measure.dynamic_line_value":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Dynamic Line Value"}},"State":"Generated","Terms":[{"dynamic line value":{"State":"Generated"}},{"line value":{"State":"Generated","Weight":0.97}},{"dynamic line assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"line assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"dynamic line worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"dynamic line price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"dynamic line cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"dynamic line charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"dynamic line rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"line worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"line price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"line cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.unitsrevenueprofit_region__country_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Units|Revenue|Profit Region | Country Title"}},"State":"Generated","Terms":[{"units|revenue|profit region | country title":{"State":"Generated"}}]},"all_measure.last_purchase_date":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Last Purchase Date"}},"State":"Generated","Terms":[{"last purchase date":{"State":"Generated"}},{"purchase date":{"State":"Generated","Weight":0.97}},{"last purchase moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"purchase moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"last purchase period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"purchase period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"end purchase date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"final purchase date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"closing purchase date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"concluding purchase date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"finishing purchase date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"former purchase date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}]},"revenue_goal":{"Definition":{"Binding":{"ConceptualEntity":"Revenue Goal"}},"State":"Generated","Terms":[{"revenue goal":{"State":"Generated","Weight":0.87}},{"goal":{"State":"Generated","Weight":0.8439}},{"income goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"profit goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"turnover goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"yield goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"revenue goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"revenue box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"revenue area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"revenue_goal.revenue_goal":{"Definition":{"Binding":{"ConceptualEntity":"Revenue Goal","ConceptualProperty":"Revenue Goal"}},"State":"Generated","Terms":[{"revenue goal":{"State":"Generated"}},{"goal":{"State":"Generated","Weight":0.97}},{"income goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"profit goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"turnover goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"yield goal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"revenue goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"goalmouth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"revenue box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"revenue area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"area":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"revenue_goal.revenue_goal_value":{"Definition":{"Binding":{"ConceptualEntity":"Revenue Goal","ConceptualProperty":"Revenue Goal Value"}},"State":"Generated","Terms":[{"revenue goal value":{"State":"Generated"}},{"goal value":{"State":"Generated","Weight":0.97}},{"income goal value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"profit goal value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"turnover goal value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"yield goal value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"revenue goal assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"goal assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"revenue goal worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"revenue goal price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"revenue goal cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"revenue goal charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"measure_selection":{"Definition":{"Binding":{"ConceptualEntity":"Measure Selection"}},"State":"Generated","Terms":[{"measure selection":{"State":"Generated"}},{"selection":{"State":"Generated","Weight":0.97}},{"measure assortment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure collection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure mixture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure medley":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure miscellany":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"assortment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"collection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mixture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"measure_selection.measure_name":{"Definition":{"Binding":{"ConceptualEntity":"Measure Selection","ConceptualProperty":"Measure Name"}},"State":"Generated","Terms":[{"measure name":{"State":"Generated"}},{"measure":{"State":"Generated","Weight":0.97}},{"measure nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"measure title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"measure label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"measure tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quota":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"ration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"measure_selection.measure_order":{"Definition":{"Binding":{"ConceptualEntity":"Measure Selection","ConceptualProperty":"Measure Order"}},"State":"Generated","Terms":[{"measure order":{"State":"Generated"}},{"order":{"State":"Generated","Weight":0.97}},{"measure instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"measure edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"measure command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"measure directive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"measure demand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"measure mandate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"dynamic_rev_unit_prof_line":{"Definition":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line"}},"State":"Generated","Terms":[{"dynamic rev, unit, prof, line":{"State":"Generated"}}]},"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line":{"Definition":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line","ConceptualProperty":"Dynamic Rev, Unit, Prof, Line"}},"State":"Generated","Terms":[{"dynamic rev, unit, prof, line":{"State":"Generated"}},{"dynamic rev, unit, prof, line name":{"State":"Generated"}}],"NameType":"Name"},"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line_field":{"Definition":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line","ConceptualProperty":"Dynamic Rev, Unit, Prof, Line Fields"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"dynamic rev, unit, prof, line field":{"State":"Generated"}}]},"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line_order":{"Definition":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line","ConceptualProperty":"Dynamic Rev, Unit, Prof, Line Order"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"dynamic rev, unit, prof, line order":{"State":"Generated"}}]},"all_measure.purchase_recency":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Purchase Recency"}},"State":"Generated","Terms":[{"purchase recency":{"State":"Generated"}}]},"all_measure.purchase_frequency":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Purchase Frequency"}},"State":"Generated","Terms":[{"purchase frequency":{"State":"Generated"}},{"frequency":{"State":"Generated","Weight":0.97}},{"purchase incidence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"purchase occurrence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"purchase regularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"incidence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"occurrence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"regularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"purchase rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.churned_customers":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Churned Customers"}},"State":"Generated","Terms":[{"churned customers":{"State":"Generated"}},{"customers":{"State":"Generated","Weight":0.97}},{"churned clientele":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned patron":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned client":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned consumer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned punter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"clientele":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"patron":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"client":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"consumer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"punter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"all_measure.churned_rate":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Churned Rate"}},"State":"Generated","Terms":[{"churned rate":{"State":"Generated"}},{"rate":{"State":"Generated","Weight":0.97}},{"churned degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned frequency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"churned quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"churned amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"churned proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.repeat_purchases":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Repeat Purchases"}},"State":"Generated","Terms":[{"repeat purchases":{"State":"Generated"}},{"purchases":{"State":"Generated","Weight":0.97}},{"repeat procurement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"repeat consumption":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"procurement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"consumption":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"repeat acquisition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"acquisition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"repeat foothold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"repeat toehold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"foothold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"toehold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"all_measure.selected_periods_titles":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Selected Periods Titles"}},"State":"Generated","Terms":[{"selected periods titles":{"State":"Generated"}},{"titles":{"State":"Generated","Weight":0.97}},{"periods titles":{"State":"Generated","Weight":0.97}},{"selected period designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"period designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"selected period name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"selected period heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"selected period label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"period name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"period heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"period label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"selected period championship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"churn_period":{"Definition":{"Binding":{"ConceptualEntity":"Churn Period"}},"State":"Generated","Terms":[{"churn period":{"State":"Generated"}},{"period":{"State":"Generated","Weight":0.97}},{"churn era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"churn epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"churn age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"churn stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"churn phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"churn_period.label":{"Definition":{"Binding":{"ConceptualEntity":"Churn Period","ConceptualProperty":"Label"}},"State":"Generated","Terms":[{"label":{"State":"Generated"}},{"sticker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"decal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"name tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.571}}]},"churn_period.value":{"Definition":{"Binding":{"ConceptualEntity":"Churn Period","ConceptualProperty":"Value"}},"State":"Generated","Terms":[{"value":{"State":"Generated"}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"meaning":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"merit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.revenue_share":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Revenue Share"}},"State":"Generated","Terms":[{"% revenue share":{"State":"Generated"}},{"percentage revenue share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"% income share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"pct revenue share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"% profit share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"% turnover share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"% yield share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"% revenue part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"% revenue portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"% revenue segment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"% revenue cut":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"all_measure.last_refresh_PQ":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Last Refresh PQ"}},"State":"Generated","Terms":[{"last refresh PQ":{"State":"Generated"}},{"PQ":{"State":"Generated","Weight":0.97}},{"refresh PQ":{"State":"Generated","Weight":0.97}},{"end refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"final refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"closing refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"concluding refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"finishing refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"former refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"latest refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"latter refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"past refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"remaining refresh pq":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}]},"refresh_timestamp":{"Definition":{"Binding":{"ConceptualEntity":"Refresh Timestamp"}},"State":"Generated","Terms":[{"refresh timestamp":{"State":"Generated","Weight":0.87}},{"timestamp":{"State":"Generated","Weight":0.8439}}]},"refresh_timestamp.refresh_timestamp":{"Definition":{"Binding":{"ConceptualEntity":"Refresh Timestamp","ConceptualProperty":"Refresh Timestamp"}},"State":"Generated","Terms":[{"refresh timestamp":{"State":"Generated"}},{"date":{"State":"Generated","Weight":0.7}},{"timestamp":{"State":"Generated","Weight":0.97}}],"SemanticType":"Time"},"all_measure.previous_year_units_sold_color":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"% Previous Year Units Sold Color"}},"State":"Generated","Terms":[{"% previous year units sold color":{"State":"Generated"}}]},"sale.shipping_address":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"shippingAddress"}},"State":"Generated","Terms":[{"shipping address":{"State":"Generated"}},{"shippingAddress":{"Type":"Noun","State":"Generated","Weight":0.99}},{"shipping location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping residence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"shipping contact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"shipping place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.billing_address":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"billingAddress"}},"State":"Generated","Terms":[{"billing address":{"State":"Generated"}},{"billingAddress":{"Type":"Noun","State":"Generated","Weight":0.99}},{"billing location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing residence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"billing contact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"billing place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.return_requested":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"returnRequested"}},"State":"Generated","Terms":[{"return requested":{"State":"Generated"}},{"returnRequested":{"Type":"Noun","State":"Generated","Weight":0.99}},{"reappearance requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"reoccurrence requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"homecoming requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"arrival requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"revenue requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"profit requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"yield requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"gain requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"benefit requested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"sale.tracking_number":{"Definition":{"Binding":{"ConceptualEntity":"sales","ConceptualProperty":"trackingNumber"}},"State":"Generated","Terms":[{"tracking number":{"State":"Generated"}},{"trackingNumber":{"Type":"Noun","State":"Generated","Weight":0.99}},{"tracking no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sales_item.barcode":{"Definition":{"Binding":{"ConceptualEntity":"sales_items","ConceptualProperty":"barcode"}},"State":"Generated","Terms":[{"barcode":{"State":"Generated"}}]},"all_measure.dynamic_tooltip_title":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Dynamic Tooltip Title"}},"State":"Generated","Terms":[{"dynamic tooltip title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"tooltip title":{"State":"Generated","Weight":0.97}},{"dynamic tooltip designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"tooltip designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dynamic tooltip name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"dynamic tooltip award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"dynamic tooltip call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"dynamic tooltip heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"dynamic tooltip label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"tooltip name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"tooltip award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.customers_bought":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Customers Bought"}},"State":"Generated","Terms":[{"customers bought":{"State":"Generated"}},{"clientele bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"patron bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"client bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"consumer bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"punter bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"regular bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"custom bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"trade bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"business bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"following bought":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.customers_bought_this_month":{"Definition":{"Binding":{"ConceptualEntity":"All Measures","ConceptualProperty":"Customers Bought This Month"}},"State":"Generated","Terms":[{"customers bought this month":{"State":"Generated"}},{"customer bought this mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"clientele bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"patron bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"client bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"consumer bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"punter bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"regular bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"custom bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trade bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"business bought this month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"Custs Bought This Month":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]}},"Relationships":{"revenue_goal_has_all_measure_increase___decrease_revenue_goal":{"Binding":{"ConceptualEntity":"Revenue Goal"},"State":"Generated","Roles":{"revenue_goal":{"Target":{"Entity":"revenue_goal"}},"all_measure.increase___decrease_revenue_goal":{"Target":{"Entity":"all_measure.increase___decrease_revenue_goal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"revenue_goal"},"Object":{"Role":"all_measure.increase___decrease_revenue_goal"}},"State":"Generated","Weight":0.99,"ID":"revenue_goals_have_increase___decrease_revenue_goal"}]},"revenue_goal_has_all_measure_revenue_goal1":{"Binding":{"ConceptualEntity":"Revenue Goal"},"State":"Generated","Roles":{"revenue_goal":{"Target":{"Entity":"revenue_goal"}},"all_measure.revenue_goal1":{"Target":{"Entity":"all_measure.revenue_goal1"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"revenue_goal"},"Object":{"Role":"all_measure.revenue_goal1"}},"State":"Generated","Weight":0.99,"ID":"revenue_goals_have_revenue_goal"}]},"sale_has_all_measure_revenue_goal":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.revenue_goal":{"Target":{"Entity":"all_measure.revenue_goal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.revenue_goal"}},"State":"Generated","Weight":0.99,"ID":"sales_have_revenue_goal"}]},"revenue_goal_has_all_measure_revenue_goal":{"Binding":{"ConceptualEntity":"Revenue Goal"},"State":"Generated","Roles":{"revenue_goal":{"Target":{"Entity":"revenue_goal"}},"all_measure.revenue_goal":{"Target":{"Entity":"all_measure.revenue_goal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"revenue_goal"},"Object":{"Role":"all_measure.revenue_goal"}},"State":"Generated","Weight":0.99,"ID":"revenue_goals_have_revenue_goal1"}]},"revenue_goal_has_all_measure_revenue_goal_monthly":{"Binding":{"ConceptualEntity":"Revenue Goal"},"State":"Generated","Roles":{"revenue_goal":{"Target":{"Entity":"revenue_goal"}},"all_measure.revenue_goal_monthly":{"Target":{"Entity":"all_measure.revenue_goal_monthly"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"revenue_goal"},"Object":{"Role":"all_measure.revenue_goal_monthly"}},"State":"Generated","Weight":0.99,"ID":"revenue_goals_have_revenue_goal_monthly"}]},"salesperson_has_all_measure_region__country_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.region__country_title":{"Target":{"Entity":"all_measure.region__country_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.region__country_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_region__country_title"}]},"sale_has_all_measure_revenue_forecast__change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.revenue_forecast__change":{"Target":{"Entity":"all_measure.revenue_forecast__change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.revenue_forecast__change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_revenue_forecast__change"}]},"sale_has_all_measure_revenue_forecast_total":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.revenue_forecast_total":{"Target":{"Entity":"all_measure.revenue_forecast_total"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.revenue_forecast_total"}},"State":"Generated","Weight":0.99,"ID":"sales_have_revenue_forecast_total"}]},"sale_has_all_measure_revenue_forecast":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.revenue_forecast":{"Target":{"Entity":"all_measure.revenue_forecast"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.revenue_forecast"}},"State":"Generated","Weight":0.99,"ID":"sales_have_revenue_forecast"}]},"sale_has_all_measure_previous_year_monthly_revenue_from_YTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_monthly_revenue_from_YTD":{"Target":{"Entity":"all_measure.previous_year_monthly_revenue_from_YTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_monthly_revenue_from_YTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_monthly_revenue_from_YTD"}]},"sale_has_all_measure_average_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.average_revenue":{"Target":{"Entity":"all_measure.average_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.average_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have_average_revenue"}]},"calendar_has_all_measure_current_year_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.current_year_title":{"Target":{"Entity":"all_measure.current_year_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.current_year_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_current_year_title"}]},"sale_has_all_measure_increase___decrease_YoY":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.increase___decrease_YoY":{"Target":{"Entity":"all_measure.increase___decrease_YoY"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.increase___decrease_YoY"}},"State":"Generated","Weight":0.99,"ID":"sales_have_increase___decrease_YoY"}]},"calendar_has_all_measure_increase___decrease_YoY":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.increase___decrease_YoY":{"Target":{"Entity":"all_measure.increase___decrease_YoY"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.increase___decrease_YoY"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_increase___decrease_YoY"}]},"sale_has_all_measure_YTD_units_sold__display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YTD_units_sold__display":{"Target":{"Entity":"all_measure.YTD_units_sold__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YTD_units_sold__display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YTD_units_sold__display"}]},"calendar_has_all_measure_YTD_units_sold__display":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.YTD_units_sold__display":{"Target":{"Entity":"all_measure.YTD_units_sold__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.YTD_units_sold__display"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_YTD_units_sold__display"}]},"sale_has_all_measure_previous_year_units_sold_from_YTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_units_sold_from_YTD":{"Target":{"Entity":"all_measure.previous_year_units_sold_from_YTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_units_sold_from_YTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_units_sold_from_YTD"}]},"sale_has_all_measure_gap_from_last_year_units_sold":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.gap_from_last_year_units_sold":{"Target":{"Entity":"all_measure.gap_from_last_year_units_sold"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.gap_from_last_year_units_sold"}},"State":"Generated","Weight":0.99,"ID":"sales_have__gap_from_last_year_units_sold"}]},"sale_has_all_measure_YoY__units_sold_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__units_sold_color":{"Target":{"Entity":"all_measure.YoY__units_sold_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__units_sold_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__units_sold_color"}]},"sale_has_all_measure_YoY__profit_change_display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__profit_change_display":{"Target":{"Entity":"all_measure.YoY__profit_change_display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__profit_change_display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__profit_change_display"}]},"salesperson_has_all_measure_salesman_name_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.salesman_name_title":{"Target":{"Entity":"all_measure.salesman_name_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.salesman_name_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_salesman_name_title"}]},"salesperson_has_all_measure_top_performing_region__country_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.top_performing_region__country_title":{"Target":{"Entity":"all_measure.top_performing_region__country_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.top_performing_region__country_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_top_performing_region__country_title"}]},"sale_has_all_measure_average_order_value":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.average_order_value":{"Target":{"Entity":"all_measure.average_order_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.average_order_value"}},"State":"Generated","Weight":0.99,"ID":"sales_have_average_order_value"}]},"percentage_adjustment_has_percentage_adjustment_value":{"Binding":{"ConceptualEntity":"Percentage Adjustment"},"State":"Generated","Roles":{"percentage_adjustment":{"Target":{"Entity":"percentage_adjustment"}},"percentage_adjustment.percentage_adjustment_value":{"Target":{"Entity":"percentage_adjustment.percentage_adjustment_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"percentage_adjustment"},"Object":{"Role":"percentage_adjustment.percentage_adjustment_value"}},"State":"Generated","Weight":0.99,"ID":"percentage_adjustments_have_percentage_adjustment_value"}]},"percentage_adjustment_has_percentage_adjustment_":{"Binding":{"ConceptualEntity":"Percentage Adjustment"},"State":"Generated","Roles":{"percentage_adjustment":{"Target":{"Entity":"percentage_adjustment"}},"percentage_adjustment.percentage_adjustment_":{"Target":{"Entity":"percentage_adjustment.percentage_adjustment_"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"percentage_adjustment"},"Object":{"Role":"percentage_adjustment.percentage_adjustment_"}},"State":"Generated","Weight":0.99,"ID":"percentage_adjustments_have_percentage_adjustment_"}]},"sales_item_has_all_measure_adjusted_revenue":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"all_measure.adjusted_revenue":{"Target":{"Entity":"all_measure.adjusted_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"all_measure.adjusted_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_adjusted_revenue"}]},"percentage_adjustment_has_all_measure_adjusted_revenue":{"Binding":{"ConceptualEntity":"Percentage Adjustment"},"State":"Generated","Roles":{"percentage_adjustment":{"Target":{"Entity":"percentage_adjustment"}},"all_measure.adjusted_revenue":{"Target":{"Entity":"all_measure.adjusted_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"percentage_adjustment"},"Object":{"Role":"all_measure.adjusted_revenue"}},"State":"Generated","Weight":0.99,"ID":"percentage_adjustments_have_adjusted_revenue"}]},"sale_has_all_measure_adjusted_gross_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.adjusted_gross_profit":{"Target":{"Entity":"all_measure.adjusted_gross_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.adjusted_gross_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_adjusted_gross_profit"}]},"percentage_adjustment_has_all_measure_adjusted_gross_profit":{"Binding":{"ConceptualEntity":"Percentage Adjustment"},"State":"Generated","Roles":{"percentage_adjustment":{"Target":{"Entity":"percentage_adjustment"}},"all_measure.adjusted_gross_profit":{"Target":{"Entity":"all_measure.adjusted_gross_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"percentage_adjustment"},"Object":{"Role":"all_measure.adjusted_gross_profit"}},"State":"Generated","Weight":0.99,"ID":"percentage_adjustments_have_adjusted_gross_profit"}]},"calendar_has_day_name":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_name":{"Target":{"Entity":"calendar.day_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_name"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_names"}]},"calendar_has_month_name":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.month_name":{"Target":{"Entity":"calendar.month_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.month_name"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_month_names"}]},"calendar_has_day_num":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_num":{"Target":{"Entity":"calendar.day_num"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_num"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_nums"}]},"calendar_has_weekday":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.weekday":{"Target":{"Entity":"calendar.weekday"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.weekday"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_weekdays"}]},"calendar_has_week":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.week":{"Target":{"Entity":"calendar.week"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.week"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_weeks"}]},"calendar_has_quarter_name":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.quarter_name":{"Target":{"Entity":"calendar.quarter_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.quarter_name"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_quarter_names"}]},"calendar_has_month":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.month":{"Target":{"Entity":"calendar.month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.month"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_months"}]},"calendar_has_year":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.year":{"Target":{"Entity":"calendar.year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.year"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_years"}]},"calendar_has_quarter":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.quarter":{"Target":{"Entity":"calendar.quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.quarter"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_quarters"}]},"calendar_has_start_of_month":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.start_of_month":{"Target":{"Entity":"calendar.start_of_month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.start_of_month"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_start_of_month"}]},"calendar_has_start_of_quarter":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.start_of_quarter":{"Target":{"Entity":"calendar.start_of_quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.start_of_quarter"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_start_of_quarter"}]},"salesperson_has_all_measure_inactive_sales_team":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.inactive_sales_team":{"Target":{"Entity":"all_measure.inactive_sales_team"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.inactive_sales_team"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_inactive_sales_team"}]},"salesperson_has_all_measure_achievement_":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.achievement_":{"Target":{"Entity":"all_measure.achievement_"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.achievement_"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_achievement_"}]},"sale_has_all_measure_achievement_":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.achievement_":{"Target":{"Entity":"all_measure.achievement_"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.achievement_"}},"State":"Generated","Weight":0.99,"ID":"sales_have_achievement_"}]},"manager_has_all_measure_managers":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"all_measure.managers":{"Target":{"Entity":"all_measure.managers"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"all_measure.managers"}},"State":"Generated","Weight":0.99,"ID":"managers_have_managers"}]},"salesperson_has_all_measure_active_sales_team":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.active_sales_team":{"Target":{"Entity":"all_measure.active_sales_team"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.active_sales_team"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_active_sales_team"}]},"sale_has_all_measure_total_orders":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.total_orders":{"Target":{"Entity":"all_measure.total_orders"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.total_orders"}},"State":"Generated","Weight":0.99,"ID":"sales_have_total_orders"}]},"sale_has_all_measure_YTD_units_sold":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YTD_units_sold":{"Target":{"Entity":"all_measure.YTD_units_sold"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YTD_units_sold"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YTD_units_sold"}]},"sale_has_all_measure_YoY__units_sold_change_display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__units_sold_change_display":{"Target":{"Entity":"all_measure.YoY__units_sold_change_display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__units_sold_change_display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__units_sold_change_display"}]},"sale_has_all_measure_YoY__units_sold_change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__units_sold_change":{"Target":{"Entity":"all_measure.YoY__units_sold_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__units_sold_change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__units_sold_change"}]},"sale_has_all_measure_previous_year_sales":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_sales":{"Target":{"Entity":"all_measure.previous_year_sales"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_sales"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_sales"}]},"sale_has_all_measure_YoY__revenue_change_display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__revenue_change_display":{"Target":{"Entity":"all_measure.YoY__revenue_change_display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__revenue_change_display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__revenue_change_display"}]},"sale_has_all_measure_cogs":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.cogs":{"Target":{"Entity":"all_measure.cogs"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.cogs"}},"State":"Generated","Weight":0.99,"ID":"sales_have_cogs"}]},"sale_has_all_measure_previous_year_profit_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_profit_color":{"Target":{"Entity":"all_measure.previous_year_profit_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_profit_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have__previous_year_profit_color"}]},"sale_has_all_measure_YTD_profit__display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YTD_profit__display":{"Target":{"Entity":"all_measure.YTD_profit__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YTD_profit__display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YTD_profit__display"}]},"calendar_has_all_measure_YTD_profit__display":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.YTD_profit__display":{"Target":{"Entity":"all_measure.YTD_profit__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.YTD_profit__display"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_YTD_profit__display"}]},"sale_has_all_measure_gap_from_last_year_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.gap_from_last_year_profit":{"Target":{"Entity":"all_measure.gap_from_last_year_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.gap_from_last_year_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have__gap_from_last_year_profit"}]},"sale_has_all_measure_previous_year_profit_from_YTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_profit_from_YTD":{"Target":{"Entity":"all_measure.previous_year_profit_from_YTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_profit_from_YTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_profit_from_YTD"}]},"sales_item_has_total_revenue_lineTotal__taxAmount":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.total_revenue_lineTotal__taxAmount":{"Target":{"Entity":"sales_item.total_revenue_lineTotal__taxAmount"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.total_revenue_lineTotal__taxAmount"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_total_revenue_lineTotal__taxAmount"},{"Adjective":{"Subject":{"Role":"sales_item"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"sales_item.total_revenue_lineTotal__taxAmount"}},"State":"Generated","Weight":0.99,"ID":"total_revenue_lineTotal__taxAmount_indicates_how_expensive_sales_items_are"}]},"datedate_has_datedate":{"Binding":{"ConceptualEntity":"Date(Date)"},"State":"Generated","Roles":{"datedate":{"Target":{"Entity":"datedate"}},"datedate.datedate":{"Target":{"Entity":"datedate.datedate"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"datedate"},"Object":{"Role":"datedate.datedate"}},"State":"Generated","Weight":0.99,"ID":"datedate_have_datedate"},{"Name":{"Subject":{"Role":"datedate"},"Name":{"Role":"datedate.datedate"}},"State":"Generated","Weight":0.99,"ID":"datedate_are_names_IDs_of_datedate"}]},"sale_has_all_measure_MoM__units_sold_color_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__units_sold_color_from_MTD":{"Target":{"Entity":"all_measure.MoM__units_sold_color_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__units_sold_color_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__units_sold_color_from_MTD"}]},"sale_has_all_measure_MoM__revenue_color_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__revenue_color_from_MTD":{"Target":{"Entity":"all_measure.MoM__revenue_color_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__revenue_color_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__revenue_color_from_MTD"}]},"sale_has_all_measure_previous_year_revenue_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_revenue_color":{"Target":{"Entity":"all_measure.previous_year_revenue_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_revenue_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have__previous_year_revenue_color"}]},"calendar_has_all_measure_prev_year_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.prev_year_title":{"Target":{"Entity":"all_measure.prev_year_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.prev_year_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_prev_year_title"}]},"sale_has_all_measure_YTD_revenue__display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YTD_revenue__display":{"Target":{"Entity":"all_measure.YTD_revenue__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YTD_revenue__display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YTD_revenue__display"}]},"calendar_has_all_measure_YTD_revenue__display":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.YTD_revenue__display":{"Target":{"Entity":"all_measure.YTD_revenue__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.YTD_revenue__display"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_YTD_revenue__display"}]},"sale_has_all_measure_gap_from_last_year_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.gap_from_last_year_revenue":{"Target":{"Entity":"all_measure.gap_from_last_year_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.gap_from_last_year_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have__gap_from_last_year_revenue"}]},"sale_has_all_measure_previous_year_revenue_from_YTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_revenue_from_YTD":{"Target":{"Entity":"all_measure.previous_year_revenue_from_YTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_revenue_from_YTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_revenue_from_YTD"}]},"calendar_has_all_measure_selected_period_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.selected_period_title":{"Target":{"Entity":"all_measure.selected_period_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.selected_period_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_selected_period_title"}]},"sale_has_all_measure_MTD_units_sold__display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MTD_units_sold__display":{"Target":{"Entity":"all_measure.MTD_units_sold__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MTD_units_sold__display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MTD_units_sold__display"}]},"calendar_has_all_measure_MTD_units_sold__display":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.MTD_units_sold__display":{"Target":{"Entity":"all_measure.MTD_units_sold__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.MTD_units_sold__display"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_MTD_units_sold__display"}]},"sale_has_all_measure_MoM__sales_quantity_change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__sales_quantity_change":{"Target":{"Entity":"all_measure.MoM__sales_quantity_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__sales_quantity_change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__sales_quantity_change"}]},"sale_has_all_measure_previous_month_sales_quantity_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_month_sales_quantity_from_MTD":{"Target":{"Entity":"all_measure.previous_month_sales_quantity_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_month_sales_quantity_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_month_sales_quantity_from_MTD"}]},"sale_has_all_measure_previous_month_sales":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_month_sales":{"Target":{"Entity":"all_measure.previous_month_sales"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_month_sales"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_month_sales"}]},"sale_has_all_measure_MTD_units_sold":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MTD_units_sold":{"Target":{"Entity":"all_measure.MTD_units_sold"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MTD_units_sold"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MTD_units_sold"}]},"sale_has_all_measure_units_sold":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.units_sold":{"Target":{"Entity":"all_measure.units_sold"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.units_sold"}},"State":"Generated","Weight":0.99,"ID":"sales_have_units_sold"}]},"sale_has_all_measure_MTD_revenue__display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MTD_revenue__display":{"Target":{"Entity":"all_measure.MTD_revenue__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MTD_revenue__display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MTD_revenue__display"}]},"calendar_has_all_measure_MTD_revenue__display":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.MTD_revenue__display":{"Target":{"Entity":"all_measure.MTD_revenue__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.MTD_revenue__display"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_MTD_revenue__display"}]},"calendar_has_all_measure_month_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.month_title":{"Target":{"Entity":"all_measure.month_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.month_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_month_title"}]},"sale_has_all_measure_MoM__profit_color_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__profit_color_from_MTD":{"Target":{"Entity":"all_measure.MoM__profit_color_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__profit_color_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__profit_color_from_MTD"}]},"sale_has_all_measure_MoM__profit_change_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__profit_change_from_MTD":{"Target":{"Entity":"all_measure.MoM__profit_change_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__profit_change_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__profit_change_from_MTD"}]},"sale_has_all_measure_previous_month_profit_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_month_profit_from_MTD":{"Target":{"Entity":"all_measure.previous_month_profit_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_month_profit_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_month_profit_from_MTD"}]},"calendar_has_all_measure_registered_customers_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.registered_customers_title":{"Target":{"Entity":"all_measure.registered_customers_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.registered_customers_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_registered_customers_title"}]},"customer_has_all_measure_new_customers":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"all_measure.new_customers":{"Target":{"Entity":"all_measure.new_customers"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"all_measure.new_customers"}},"State":"Generated","Weight":0.99,"ID":"customers_have_new_customers"}]},"sale_has_all_measure_MTD_profit__display":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MTD_profit__display":{"Target":{"Entity":"all_measure.MTD_profit__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MTD_profit__display"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MTD_profit__display"}]},"calendar_has_all_measure_MTD_profit__display":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.MTD_profit__display":{"Target":{"Entity":"all_measure.MTD_profit__display"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.MTD_profit__display"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_MTD_profit__display"}]},"sale_has_all_measure_gap_last_month_revenue_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.gap_last_month_revenue_color":{"Target":{"Entity":"all_measure.gap_last_month_revenue_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.gap_last_month_revenue_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have__gap_last_month_revenue_color"}]},"sale_has_all_measure_YoY__profit_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__profit_color":{"Target":{"Entity":"all_measure.YoY__profit_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__profit_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__profit_color"}]},"sale_has_all_measure_YoY__revenue_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__revenue_color":{"Target":{"Entity":"all_measure.YoY__revenue_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__revenue_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__revenue_color"}]},"sale_has_all_measure_gap_from_last_month_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.gap_from_last_month_revenue":{"Target":{"Entity":"all_measure.gap_from_last_month_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.gap_from_last_month_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have__gap_from_last_month_revenue"}]},"sale_has_all_measure_MoM__profit_change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__profit_change":{"Target":{"Entity":"all_measure.MoM__profit_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__profit_change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__profit_change"}]},"sale_has_all_measure_MTD_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MTD_profit":{"Target":{"Entity":"all_measure.MTD_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MTD_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MTD_profit"}]},"sale_has_all_measure_YTD_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YTD_profit":{"Target":{"Entity":"all_measure.YTD_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YTD_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YTD_profit"}]},"sale_has_all_measure_YoY__profit_change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__profit_change":{"Target":{"Entity":"all_measure.YoY__profit_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__profit_change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__profit_change"}]},"sale_has_all_measure_previous_year_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_profit":{"Target":{"Entity":"all_measure.previous_year_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_profit"}]},"sale_has_all_measure_previous_month_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_month_profit":{"Target":{"Entity":"all_measure.previous_month_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_month_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_month_profit"}]},"sale_has_all_measure_YoY__revenue_change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YoY__revenue_change":{"Target":{"Entity":"all_measure.YoY__revenue_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YoY__revenue_change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YoY__revenue_change"}]},"sale_has_all_measure_previous_year_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_revenue":{"Target":{"Entity":"all_measure.previous_year_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_year_revenue"}]},"sale_has_all_measure_MoM__revenue_change":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MoM__revenue_change":{"Target":{"Entity":"all_measure.MoM__revenue_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MoM__revenue_change"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MoM__revenue_change"}]},"sale_has_all_measure_total_cost":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.total_cost":{"Target":{"Entity":"all_measure.total_cost"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.total_cost"}},"State":"Generated","Weight":0.99,"ID":"sales_have_total_cost"},{"Adjective":{"Subject":{"Role":"sale"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"all_measure.total_cost"}},"State":"Generated","Weight":0.99,"ID":"total_cost_indicates_how_expensive_sales_are"}]},"calendar_has_all_measure_current_month_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.current_month_title":{"Target":{"Entity":"all_measure.current_month_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.current_month_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_current_month_title"}]},"calendar_has_all_measure_previous_month_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.previous_month_title":{"Target":{"Entity":"all_measure.previous_month_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.previous_month_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_previous_month_title"}]},"sale_has_all_measure_previous_month_revenue_from_MTD":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_month_revenue_from_MTD":{"Target":{"Entity":"all_measure.previous_month_revenue_from_MTD"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_month_revenue_from_MTD"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_month_revenue_from_MTD"}]},"sale_has_all_measure_previous_month_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_month_revenue":{"Target":{"Entity":"all_measure.previous_month_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_month_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have_previous_month_revenue"}]},"sale_has_all_measure_prev_month_revenue_PREVIOUSMONTH":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.prev_month_revenue_PREVIOUSMONTH":{"Target":{"Entity":"all_measure.prev_month_revenue_PREVIOUSMONTH"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.prev_month_revenue_PREVIOUSMONTH"}},"State":"Generated","Weight":0.99,"ID":"sales_have_prev_month_revenue_PREVIOUSMONTH"}]},"sale_has_all_measure_YTD_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.YTD_revenue":{"Target":{"Entity":"all_measure.YTD_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.YTD_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have_YTD_revenue"}]},"sale_has_all_measure_MTD_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.MTD_revenue":{"Target":{"Entity":"all_measure.MTD_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.MTD_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have_MTD_revenue"}]},"customer_has_all_measure_total_customers_till_date":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"all_measure.total_customers_till_date":{"Target":{"Entity":"all_measure.total_customers_till_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"all_measure.total_customers_till_date"}},"State":"Generated","Weight":0.99,"ID":"customers_have_total_customers_till_date"}]},"manager_has_report_to":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.report_to":{"Target":{"Entity":"manager.report_to"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.report_to"}},"State":"Generated","Weight":0.99,"ID":"managers_have_report_to"},{"Verb":{"Subject":{"Role":"manager"},"Verbs":[{"report":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"to":{"State":"Generated"}}],"Object":{"Role":"manager.report_to"}}]},"State":"Generated","Weight":0.95,"ID":"managers_report_to_report_to"}]},"manager_has_years_experience":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.years_experience":{"Target":{"Entity":"manager.years_experience"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.years_experience"}},"State":"Generated","Weight":0.99,"ID":"managers_have_years_experiences"}]},"manager_has_performance_rating":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.performance_rating":{"Target":{"Entity":"manager.performance_rating"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.performance_rating"}},"State":"Generated","Weight":0.99,"ID":"managers_have_performance_rating"}]},"manager_has_department":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.department":{"Target":{"Entity":"manager.department"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.department"}},"State":"Generated","Weight":0.99,"ID":"managers_have_departments"}]},"manager_has_hire_date":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.hire_date":{"Target":{"Entity":"manager.hire_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.hire_date"}},"State":"Generated","Weight":0.99,"ID":"managers_have_hire_dates"}]},"manager_has_city":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.city":{"Target":{"Entity":"manager.city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.city"}},"State":"Generated","Weight":0.99,"ID":"managers_have_cities"}]},"manager_has_country":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.country":{"Target":{"Entity":"manager.country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.country"}},"State":"Generated","Weight":0.99,"ID":"managers_have_countries"}]},"manager_has_region":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.region":{"Target":{"Entity":"manager.region"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.region"}},"State":"Generated","Weight":0.99,"ID":"managers_have_regions"}]},"manager_has_phone":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.phone":{"Target":{"Entity":"manager.phone"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.phone"}},"State":"Generated","Weight":0.99,"ID":"managers_have_phones"}]},"manager_has_email":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.email":{"Target":{"Entity":"manager.email"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.email"}},"State":"Generated","Weight":0.99,"ID":"managers_have_emails"}]},"manager_has_culture":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.culture":{"Target":{"Entity":"manager.culture"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.culture"}},"State":"Generated","Weight":0.99,"ID":"managers_have_cultures"}]},"manager_has_full_name":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.full_name":{"Target":{"Entity":"manager.full_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.full_name"}},"State":"Generated","Weight":0.99,"ID":"managers_have_full_names"},{"Name":{"Subject":{"Role":"manager"},"Name":{"Role":"manager.full_name"}},"State":"Generated","Weight":0.99,"ID":"full_names_are_names_IDs_of_managers"}]},"manager_has_last_name":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.last_name":{"Target":{"Entity":"manager.last_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.last_name"}},"State":"Generated","Weight":0.99,"ID":"managers_have_last_names"},{"Name":{"Subject":{"Role":"manager"},"Name":{"Role":"manager.last_name"}},"State":"Generated","Weight":0.99,"ID":"last_names_are_names_IDs_of_managers"}]},"manager_has_first_name":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.first_name":{"Target":{"Entity":"manager.first_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.first_name"}},"State":"Generated","Weight":0.99,"ID":"managers_have_first_names"},{"Name":{"Subject":{"Role":"manager"},"Name":{"Role":"manager.first_name"}},"State":"Generated","Weight":0.99,"ID":"first_names_are_names_IDs_of_managers"}]},"manager_has_manager_id":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.manager_id":{"Target":{"Entity":"manager.manager_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"manager.manager_id"}},"State":"Generated","Weight":0.99,"ID":"managers_have_manager_ids"},{"Name":{"Subject":{"Role":"manager"},"Name":{"Role":"manager.manager_id"}},"State":"Generated","Weight":0.99,"ID":"manager_ids_are_names_IDs_of_managers"}]},"salesperson_has_certification":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.certification":{"Target":{"Entity":"salesperson.certification"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.certification"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_certifications"}]},"salesperson_has_language_spoken":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.language_spoken":{"Target":{"Entity":"salesperson.language_spoken"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.language_spoken"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_language_spoken"}]},"salesperson_has_employment_status":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.employment_status":{"Target":{"Entity":"salesperson.employment_status"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.employment_status"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_employment_statuses"}]},"salesperson_has_achievement_percent":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.achievement_percent":{"Target":{"Entity":"salesperson.achievement_percent"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.achievement_percent"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_achievement_percent"}]},"salesperson_has_sales_target":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.sales_target":{"Target":{"Entity":"salesperson.sales_target"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.sales_target"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_sales_targets"},{"Adjective":{"Subject":{"Role":"salesperson"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"salesperson.sales_target"}},"State":"Generated","Weight":0.99,"ID":"sales_target_indicates_how_expensive_salespeople_are"}]},"salesperson_has_years_experience":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.years_experience":{"Target":{"Entity":"salesperson.years_experience"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.years_experience"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_years_experiences"}]},"salesperson_has_performance_rating":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.performance_rating":{"Target":{"Entity":"salesperson.performance_rating"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.performance_rating"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_performance_rating"}]},"salesperson_has_commission_rate":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.commission_rate":{"Target":{"Entity":"salesperson.commission_rate"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.commission_rate"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_commission_rates"}]},"salesperson_has_manager_name":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.manager_name":{"Target":{"Entity":"salesperson.manager_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.manager_name"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_manager_names"}]},"salesperson_has_manager_id":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.manager_id":{"Target":{"Entity":"salesperson.manager_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.manager_id"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_manager_ids"}]},"salesperson_has_city":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.city":{"Target":{"Entity":"salesperson.city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.city"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_cities"}]},"salesperson_has_country":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.country":{"Target":{"Entity":"salesperson.country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.country"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_countries"}]},"salesperson_has_region":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.region":{"Target":{"Entity":"salesperson.region"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.region"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_regions"}]},"salesperson_has_hire_date":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.hire_date":{"Target":{"Entity":"salesperson.hire_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.hire_date"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_hire_dates"}]},"salesperson_has_phone":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.phone":{"Target":{"Entity":"salesperson.phone"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.phone"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_phones"}]},"salesperson_has_email":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.email":{"Target":{"Entity":"salesperson.email"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.email"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_emails"}]},"salesperson_has_culture":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.culture":{"Target":{"Entity":"salesperson.culture"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.culture"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_cultures"}]},"salesperson_has_full_name":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.full_name":{"Target":{"Entity":"salesperson.full_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.full_name"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_full_names"},{"Name":{"Subject":{"Role":"salesperson"},"Name":{"Role":"salesperson.full_name"}},"State":"Generated","Weight":0.99,"ID":"full_names_are_names_IDs_of_salespeople"}]},"salesperson_has_last_name":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.last_name":{"Target":{"Entity":"salesperson.last_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.last_name"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_last_names"}]},"salesperson_has_first_name":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.first_name":{"Target":{"Entity":"salesperson.first_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.first_name"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_first_names"}]},"salesperson_has_salesperson_id":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.salesperson_id":{"Target":{"Entity":"salesperson.salesperson_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"salesperson.salesperson_id"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_salesperson_ids"},{"Name":{"Subject":{"Role":"salesperson"},"Name":{"Role":"salesperson.salesperson_id"}},"State":"Generated","Weight":0.99,"ID":"salesperson_ids_are_names_IDs_of_salespeople"}]},"customer_has_tax_id":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.tax_id":{"Target":{"Entity":"customer.tax_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.tax_id"}},"State":"Generated","Weight":0.99,"ID":"customers_have_tax_ids"}]},"customer_has_industry":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.industry":{"Target":{"Entity":"customer.industry"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.industry"}},"State":"Generated","Weight":0.99,"ID":"customers_have_industries"}]},"customer_has_lifetime_value":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.lifetime_value":{"Target":{"Entity":"customer.lifetime_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.lifetime_value"}},"State":"Generated","Weight":0.99,"ID":"customers_have_lifetime_values"}]},"customer_has_preferred_contact":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.preferred_contact":{"Target":{"Entity":"customer.preferred_contact"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.preferred_contact"}},"State":"Generated","Weight":0.99,"ID":"customers_have_preferred_contacts"}]},"customer_has_customer_segment":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.customer_segment":{"Target":{"Entity":"customer.customer_segment"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.customer_segment"}},"State":"Generated","Weight":0.99,"ID":"customers_have_customer_segments"}]},"customer_has_credit_limit":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.credit_limit":{"Target":{"Entity":"customer.credit_limit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.credit_limit"}},"State":"Generated","Weight":0.99,"ID":"customers_have_credit_limits"}]},"customer_has_loyalty_point":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.loyalty_point":{"Target":{"Entity":"customer.loyalty_point"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.loyalty_point"}},"State":"Generated","Weight":0.99,"ID":"customers_have_loyalty_points"}]},"customer_has_registration_date":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.registration_date":{"Target":{"Entity":"customer.registration_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.registration_date"}},"State":"Generated","Weight":0.99,"ID":"customers_have_registration_dates"}]},"customer_has_postal_code":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.postal_code":{"Target":{"Entity":"customer.postal_code"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.postal_code"}},"State":"Generated","Weight":0.99,"ID":"customers_have_postal_codes"}]},"customer_has_country":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.country":{"Target":{"Entity":"customer.country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.country"}},"State":"Generated","Weight":0.99,"ID":"customers_have_countries"}]},"customer_has_region":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.region":{"Target":{"Entity":"customer.region"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.region"}},"State":"Generated","Weight":0.99,"ID":"customers_have_regions"}]},"customer_has_city":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.city":{"Target":{"Entity":"customer.city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.city"}},"State":"Generated","Weight":0.99,"ID":"customers_have_cities"}]},"customer_has_address":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.address":{"Target":{"Entity":"customer.address"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.address"}},"State":"Generated","Weight":0.99,"ID":"customers_have_addresses"}]},"customer_has_phone":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.phone":{"Target":{"Entity":"customer.phone"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.phone"}},"State":"Generated","Weight":0.99,"ID":"customers_have_phones"}]},"customer_has_email":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.email":{"Target":{"Entity":"customer.email"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.email"}},"State":"Generated","Weight":0.99,"ID":"customers_have_emails"}]},"customer_has_culture":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.culture":{"Target":{"Entity":"customer.culture"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.culture"}},"State":"Generated","Weight":0.99,"ID":"customers_have_cultures"}]},"customer_has_full_name":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.full_name":{"Target":{"Entity":"customer.full_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.full_name"}},"State":"Generated","Weight":0.99,"ID":"customers_have_full_names"}]},"customer_has_company_name":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.company_name":{"Target":{"Entity":"customer.company_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.company_name"}},"State":"Generated","Weight":0.99,"ID":"customers_have_company_names"}]},"customer_has_last_name":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.last_name":{"Target":{"Entity":"customer.last_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.last_name"}},"State":"Generated","Weight":0.99,"ID":"customers_have_last_names"}]},"customer_has_first_name":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.first_name":{"Target":{"Entity":"customer.first_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.first_name"}},"State":"Generated","Weight":0.99,"ID":"customers_have_first_names"}]},"customer_has_customer_type":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.customer_type":{"Target":{"Entity":"customer.customer_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.customer_type"}},"State":"Generated","Weight":0.99,"ID":"customers_have_customer_types"}]},"customer_has_customer_id":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.customer_id":{"Target":{"Entity":"customer.customer_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"customer.customer_id"}},"State":"Generated","Weight":0.99,"ID":"customers_have_customer_ids"},{"Name":{"Subject":{"Role":"customer"},"Name":{"Role":"customer.customer_id"}},"State":"Generated","Weight":0.99,"ID":"customer_ids_are_names_IDs_of_customers"}]},"product_has_tag":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.tag":{"Target":{"Entity":"product.tag"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.tag"}},"State":"Generated","Weight":0.99,"ID":"products_have_tags"}]},"product_has_review_count":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.review_count":{"Target":{"Entity":"product.review_count"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.review_count"}},"State":"Generated","Weight":0.99,"ID":"products_have_review_counts"}]},"product_has_rating":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.rating":{"Target":{"Entity":"product.rating"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.rating"}},"State":"Generated","Weight":0.99,"ID":"products_have_rating"}]},"product_has_is_on_sale":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.is_on_sale":{"Target":{"Entity":"product.is_on_sale"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.is_on_sale"}},"State":"Generated","Weight":0.99,"ID":"products_have_is_on_sale"},{"Verb":{"Subject":{"Role":"product"},"Verbs":[{"is":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"on":{"State":"Generated"}}],"Object":{"Role":"product.is_on_sale"}}]},"State":"Generated","Weight":0.95,"ID":"products_is_on_is_on_sale"}]},"product_has_is_featured":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.is_featured":{"Target":{"Entity":"product.is_featured"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.is_featured"}},"State":"Generated","Weight":0.99,"ID":"products_have_is_featured"}]},"product_has_is_active":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.is_active":{"Target":{"Entity":"product.is_active"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.is_active"}},"State":"Generated","Weight":0.99,"ID":"products_have_is_actives"}]},"product_has_return_policy":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.return_policy":{"Target":{"Entity":"product.return_policy"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.return_policy"}},"State":"Generated","Weight":0.99,"ID":"products_have_return_policies"}]},"product_has_warranty_month":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.warranty_month":{"Target":{"Entity":"product.warranty_month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.warranty_month"}},"State":"Generated","Weight":0.99,"ID":"products_have_warranty_months"}]},"product_has_bin":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.bin":{"Target":{"Entity":"product.bin"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.bin"}},"State":"Generated","Weight":0.99,"ID":"products_have_bins"}]},"product_has_shelf":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.shelf":{"Target":{"Entity":"product.shelf"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.shelf"}},"State":"Generated","Weight":0.99,"ID":"products_have_shelves"}]},"product_has_aisle":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.aisle":{"Target":{"Entity":"product.aisle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.aisle"}},"State":"Generated","Weight":0.99,"ID":"products_have_aisles"}]},"product_has_warehouse":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.warehouse":{"Target":{"Entity":"product.warehouse"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.warehouse"}},"State":"Generated","Weight":0.99,"ID":"products_have_warehouses"}]},"product_has_max_order_quantity":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.max_order_quantity":{"Target":{"Entity":"product.max_order_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.max_order_quantity"}},"State":"Generated","Weight":0.99,"ID":"products_have_max_order_quantities"}]},"product_has_min_order_quantity":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.min_order_quantity":{"Target":{"Entity":"product.min_order_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.min_order_quantity"}},"State":"Generated","Weight":0.99,"ID":"products_have_min_order_quantities"}]},"product_has_reorder_quantity":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.reorder_quantity":{"Target":{"Entity":"product.reorder_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.reorder_quantity"}},"State":"Generated","Weight":0.99,"ID":"products_have_reorder_quantities"}]},"product_has_reorder_level":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.reorder_level":{"Target":{"Entity":"product.reorder_level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.reorder_level"}},"State":"Generated","Weight":0.99,"ID":"products_have_reorder_levels"}]},"product_has_available_quantity":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.available_quantity":{"Target":{"Entity":"product.available_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.available_quantity"}},"State":"Generated","Weight":0.99,"ID":"products_have_available_quantities"}]},"product_has_reserved_quantity":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.reserved_quantity":{"Target":{"Entity":"product.reserved_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.reserved_quantity"}},"State":"Generated","Weight":0.99,"ID":"products_have_reserved_quantities"}]},"product_has_stock_quantity":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.stock_quantity":{"Target":{"Entity":"product.stock_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.stock_quantity"}},"State":"Generated","Weight":0.99,"ID":"products_have_stock_quantities"}]},"product_has_material":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.material":{"Target":{"Entity":"product.material"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.material"}},"State":"Generated","Weight":0.99,"ID":"products_have_materials"}]},"product_has_size":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.size":{"Target":{"Entity":"product.size"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.size"}},"State":"Generated","Weight":0.99,"ID":"products_have_sizes"}]},"product_has_color":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.color":{"Target":{"Entity":"product.color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.color"}},"State":"Generated","Weight":0.99,"ID":"products_have_colors"}]},"product_has_dimension_unit":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.dimension_unit":{"Target":{"Entity":"product.dimension_unit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.dimension_unit"}},"State":"Generated","Weight":0.99,"ID":"products_have_dimension_units"}]},"product_has_dimension":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.dimension":{"Target":{"Entity":"product.dimension"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.dimension"}},"State":"Generated","Weight":0.99,"ID":"products_have_dimensions"}]},"product_has_weight_unit":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.weight_unit":{"Target":{"Entity":"product.weight_unit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.weight_unit"}},"State":"Generated","Weight":0.99,"ID":"products_have_weight_units"}]},"product_has_weight":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.weight":{"Target":{"Entity":"product.weight"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.weight"}},"State":"Generated","Weight":0.99,"ID":"products_have_weights"},{"Adjective":{"Subject":{"Role":"product"},"Adjectives":[{"heavy":{"State":"Generated"}}],"Antonyms":[{"light":{"State":"Generated"}}],"Measurement":{"Role":"product.weight"}},"State":"Generated","Weight":0.99,"ID":"weight_indicates_how_heavy_products_are"}]},"product_has_supplier_sku":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.supplier_sku":{"Target":{"Entity":"product.supplier_sku"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.supplier_sku"}},"State":"Generated","Weight":0.99,"ID":"products_have_supplier_skus"}]},"product_has_supplier":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.supplier":{"Target":{"Entity":"product.supplier"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.supplier"}},"State":"Generated","Weight":0.99,"ID":"products_have_suppliers"},{"Verb":{"Subject":{"Role":"product.supplier"},"Verbs":[{"supply":{"State":"Generated"}}],"Object":{"Role":"product"}},"State":"Generated","Weight":0.75,"ID":"suppliers_supply_products"},{"Attribute":{"Subject":{"Role":"product.supplier"},"Object":{"Role":"product"}},"State":"Generated","Weight":0.99,"ID":"suppliers_have_products"}]},"product_has_msrp":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.msrp":{"Target":{"Entity":"product.msrp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.msrp"}},"State":"Generated","Weight":0.99,"ID":"products_have_msrps"}]},"product_has_cost_price":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.cost_price":{"Target":{"Entity":"product.cost_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.cost_price"}},"State":"Generated","Weight":0.99,"ID":"products_have_cost_prices"},{"Adjective":{"Subject":{"Role":"product"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"product.cost_price"}},"State":"Generated","Weight":0.99,"ID":"cost_price_indicates_how_expensive_products_are"}]},"product_has_unit_price":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.unit_price":{"Target":{"Entity":"product.unit_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.unit_price"}},"State":"Generated","Weight":0.99,"ID":"products_have_unit_prices"},{"Adjective":{"Subject":{"Role":"product"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"product.unit_price"}},"State":"Generated","Weight":0.99,"ID":"unit_price_indicates_how_expensive_products_are"}]},"product_has_manufacturer":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.manufacturer":{"Target":{"Entity":"product.manufacturer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.manufacturer"}},"State":"Generated","Weight":0.99,"ID":"products_have_manufacturers"},{"Verb":{"Subject":{"Role":"product.manufacturer"},"Verbs":[{"manufacture":{"State":"Generated"}}],"Object":{"Role":"product"}},"State":"Generated","Weight":0.75,"ID":"manufacturers_manufacture_products"},{"Attribute":{"Subject":{"Role":"product.manufacturer"},"Object":{"Role":"product"}},"State":"Generated","Weight":0.99,"ID":"manufacturers_have_products"}]},"product_has_brand":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.brand":{"Target":{"Entity":"product.brand"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.brand"}},"State":"Generated","Weight":0.99,"ID":"products_have_brands"}]},"product_has_subcategory":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.subcategory":{"Target":{"Entity":"product.subcategory"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.subcategory"}},"State":"Generated","Weight":0.99,"ID":"products_have_subcategories"}]},"product_has_category":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.category":{"Target":{"Entity":"product.category"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.category"}},"State":"Generated","Weight":0.99,"ID":"products_have_categories"}]},"product_has_description":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.description":{"Target":{"Entity":"product.description"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.description"}},"State":"Generated","Weight":0.99,"ID":"products_have_descriptions"}]},"product_has_product_name":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.product_name":{"Target":{"Entity":"product.product_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.product_name"}},"State":"Generated","Weight":0.99,"ID":"products_have_product_names"},{"Name":{"Subject":{"Role":"product"},"Name":{"Role":"product.product_name"}},"State":"Generated","Weight":0.99,"ID":"product_names_are_names_IDs_of_products"}]},"product_has_barcode":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.barcode":{"Target":{"Entity":"product.barcode"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.barcode"}},"State":"Generated","Weight":0.99,"ID":"products_have_barcodes"}]},"product_has_sku":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.sku":{"Target":{"Entity":"product.sku"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.sku"}},"State":"Generated","Weight":0.99,"ID":"products_have_skus"}]},"product_has_product_id":{"Binding":{"ConceptualEntity":"products"},"State":"Generated","Roles":{"product":{"Target":{"Entity":"product"}},"product.product_id":{"Target":{"Entity":"product.product_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"product.product_id"}},"State":"Generated","Weight":0.99,"ID":"products_have_product_ids"},{"Name":{"Subject":{"Role":"product"},"Name":{"Role":"product.product_id"}},"State":"Generated","Weight":0.99,"ID":"product_ids_are_names_IDs_of_products"}]},"sales_item_has_tax_rate":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.tax_rate":{"Target":{"Entity":"sales_item.tax_rate"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.tax_rate"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_tax_rates"}]},"sales_item_has_margin_percent":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.margin_percent":{"Target":{"Entity":"sales_item.margin_percent"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.margin_percent"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_margin_percent"}]},"sales_item_has_margin":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.margin":{"Target":{"Entity":"sales_item.margin"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.margin"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_margins"}]},"sales_item_has_warehouse":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.warehouse":{"Target":{"Entity":"sales_item.warehouse"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.warehouse"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_warehouses"}]},"sales_item_has_tax_amount":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.tax_amount":{"Target":{"Entity":"sales_item.tax_amount"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.tax_amount"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_tax_amounts"}]},"sales_item_has_line_total":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.line_total":{"Target":{"Entity":"sales_item.line_total"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.line_total"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_line_totals"}]},"sales_item_has_discount_amount":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.discount_amount":{"Target":{"Entity":"sales_item.discount_amount"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.discount_amount"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_discount_amounts"}]},"sales_item_has_discount_percent":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.discount_percent":{"Target":{"Entity":"sales_item.discount_percent"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.discount_percent"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_discount_percent"}]},"sales_item_has_cost_price":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.cost_price":{"Target":{"Entity":"sales_item.cost_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.cost_price"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_cost_prices"},{"Adjective":{"Subject":{"Role":"sales_item"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"sales_item.cost_price"}},"State":"Generated","Weight":0.99,"ID":"cost_price_indicates_how_expensive_sales_items_are"}]},"sales_item_has_unit_price":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.unit_price":{"Target":{"Entity":"sales_item.unit_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.unit_price"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_unit_prices"},{"Adjective":{"Subject":{"Role":"sales_item"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"sales_item.unit_price"}},"State":"Generated","Weight":0.99,"ID":"unit_price_indicates_how_expensive_sales_items_are"}]},"sales_item_has_quantity":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.quantity":{"Target":{"Entity":"sales_item.quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.quantity"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_quantities"}]},"sales_item_has_brand":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.brand":{"Target":{"Entity":"sales_item.brand"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.brand"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_brands"}]},"sales_item_has_subcategory":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.subcategory":{"Target":{"Entity":"sales_item.subcategory"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.subcategory"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_subcategories"}]},"sales_item_has_category":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.category":{"Target":{"Entity":"sales_item.category"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.category"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_categories"}]},"sales_item_has_product_name":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.product_name":{"Target":{"Entity":"sales_item.product_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.product_name"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_product_names"}]},"sales_item_has_sku":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.sku":{"Target":{"Entity":"sales_item.sku"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.sku"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_skus"}]},"sales_item_has_order_date":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.order_date":{"Target":{"Entity":"sales_item.order_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.order_date"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_order_dates"}]},"sales_item_has_invoice_number":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.invoice_number":{"Target":{"Entity":"sales_item.invoice_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.invoice_number"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_invoice_numbers"}]},"sales_item_has_order_id":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.order_id":{"Target":{"Entity":"sales_item.order_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.order_id"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_order_ids"}]},"sales_item_has_line_item_id":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.line_item_id":{"Target":{"Entity":"sales_item.line_item_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.line_item_id"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_line_item_ids"},{"Name":{"Subject":{"Role":"sales_item"},"Name":{"Role":"sales_item.line_item_id"}},"State":"Generated","Weight":0.99,"ID":"line_item_ids_are_names_IDs_of_sales_items"}]},"sale_has_channel":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.channel":{"Target":{"Entity":"sale.channel"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.channel"}},"State":"Generated","Weight":0.99,"ID":"sales_have_channels"}]},"sale_has_source":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.source":{"Target":{"Entity":"sale.source"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.source"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sources"}]},"sale_has_return_reason":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.return_reason":{"Target":{"Entity":"sale.return_reason"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.return_reason"}},"State":"Generated","Weight":0.99,"ID":"sales_have_return_reasons"}]},"sale_has_carrier":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.carrier":{"Target":{"Entity":"sale.carrier"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.carrier"}},"State":"Generated","Weight":0.99,"ID":"sales_have_carriers"},{"Verb":{"Subject":{"Role":"sale.carrier"},"Verbs":[{"carry":{"State":"Generated"}}],"Object":{"Role":"sale"}},"State":"Generated","Weight":0.75,"ID":"carriers_carry_sales"},{"Attribute":{"Subject":{"Role":"sale.carrier"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"carriers_have_sales"}]},"sale_has_actual_delivery":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.actual_delivery":{"Target":{"Entity":"sale.actual_delivery"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.actual_delivery"}},"State":"Generated","Weight":0.99,"ID":"sales_have_actual_deliveries"}]},"sale_has_estimated_delivery":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.estimated_delivery":{"Target":{"Entity":"sale.estimated_delivery"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.estimated_delivery"}},"State":"Generated","Weight":0.99,"ID":"sales_have_estimated_deliveries"}]},"sale_has_ship_date":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.ship_date":{"Target":{"Entity":"sale.ship_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.ship_date"}},"State":"Generated","Weight":0.99,"ID":"sales_have_ship_dates"}]},"sale_has_note":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.note":{"Target":{"Entity":"sale.note"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.note"}},"State":"Generated","Weight":0.99,"ID":"sales_have_notes"}]},"sale_has_exchange_rate":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.exchange_rate":{"Target":{"Entity":"sale.exchange_rate"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.exchange_rate"}},"State":"Generated","Weight":0.99,"ID":"sales_have_exchange_rates"}]},"sale_has_currency":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.currency":{"Target":{"Entity":"sale.currency"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.currency"}},"State":"Generated","Weight":0.99,"ID":"sales_have_currencies"}]},"sale_has_commission":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.commission":{"Target":{"Entity":"sale.commission"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.commission"}},"State":"Generated","Weight":0.99,"ID":"sales_have_commissions"}]},"sale_has_profit_margin":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.profit_margin":{"Target":{"Entity":"sale.profit_margin"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.profit_margin"}},"State":"Generated","Weight":0.99,"ID":"sales_have_profit_margins"}]},"sale_has_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.profit":{"Target":{"Entity":"sale.profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_profits"}]},"sale_has_total_cost":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.total_cost":{"Target":{"Entity":"sale.total_cost"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.total_cost"}},"State":"Generated","Weight":0.99,"ID":"sales_have_total_costs"},{"Adjective":{"Subject":{"Role":"sale"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"sale.total_cost"}},"State":"Generated","Weight":0.99,"ID":"total_cost_indicates_how_expensive_sales_are1"}]},"sale_has_total_amount":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.total_amount":{"Target":{"Entity":"sale.total_amount"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.total_amount"}},"State":"Generated","Weight":0.99,"ID":"sales_have_total_amounts"}]},"sale_has_shipping_cost":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_cost":{"Target":{"Entity":"sale.shipping_cost"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.shipping_cost"}},"State":"Generated","Weight":0.99,"ID":"sales_have_shipping_costs"},{"Adjective":{"Subject":{"Role":"sale"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"sale.shipping_cost"}},"State":"Generated","Weight":0.99,"ID":"shipping_cost_indicates_how_expensive_sales_are"}]},"sale_has_tax_amount":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.tax_amount":{"Target":{"Entity":"sale.tax_amount"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.tax_amount"}},"State":"Generated","Weight":0.99,"ID":"sales_have_tax_amounts"}]},"sale_has_subtotal":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.subtotal":{"Target":{"Entity":"sale.subtotal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.subtotal"}},"State":"Generated","Weight":0.99,"ID":"sales_have_subtotals"}]},"sale_has_total_quantity":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.total_quantity":{"Target":{"Entity":"sale.total_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.total_quantity"}},"State":"Generated","Weight":0.99,"ID":"sales_have_total_quantities"}]},"sale_has_item_count":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.item_count":{"Target":{"Entity":"sale.item_count"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.item_count"}},"State":"Generated","Weight":0.99,"ID":"sales_have_item_counts"}]},"sale_has_billing_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.billing_country":{"Target":{"Entity":"sale.billing_country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.billing_country"}},"State":"Generated","Weight":0.99,"ID":"sales_have_billing_countries"}]},"sale_has_billing_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.billing_city":{"Target":{"Entity":"sale.billing_city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.billing_city"}},"State":"Generated","Weight":0.99,"ID":"sales_have_billing_cities"}]},"sale_has_shipping_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_country":{"Target":{"Entity":"sale.shipping_country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.shipping_country"}},"State":"Generated","Weight":0.99,"ID":"sales_have_shipping_countries"}]},"sale_has_shipping_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_city":{"Target":{"Entity":"sale.shipping_city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.shipping_city"}},"State":"Generated","Weight":0.99,"ID":"sales_have_shipping_cities"}]},"sale_has_shipping_method":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_method":{"Target":{"Entity":"sale.shipping_method"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.shipping_method"}},"State":"Generated","Weight":0.99,"ID":"sales_have_shipping_methods"}]},"sale_has_payment_term":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.payment_term":{"Target":{"Entity":"sale.payment_term"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.payment_term"}},"State":"Generated","Weight":0.99,"ID":"sales_have_payment_terms"}]},"sale_has_payment_status":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.payment_status":{"Target":{"Entity":"sale.payment_status"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.payment_status"}},"State":"Generated","Weight":0.99,"ID":"sales_have_payment_statuses"}]},"sale_has_payment_method":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.payment_method":{"Target":{"Entity":"sale.payment_method"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.payment_method"}},"State":"Generated","Weight":0.99,"ID":"sales_have_payment_methods"}]},"sale_has_order_status":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.order_status":{"Target":{"Entity":"sale.order_status"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.order_status"}},"State":"Generated","Weight":0.99,"ID":"sales_have_order_statuses"}]},"sale_has_sales_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sales_city":{"Target":{"Entity":"sale.sales_city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.sales_city"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sales_cities"}]},"sale_has_sales_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sales_country":{"Target":{"Entity":"sale.sales_country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.sales_country"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sales_countries"}]},"sale_has_sales_region":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sales_region":{"Target":{"Entity":"sale.sales_region"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.sales_region"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sales_regions"}]},"sale_has_manager_name":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.manager_name":{"Target":{"Entity":"sale.manager_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.manager_name"}},"State":"Generated","Weight":0.99,"ID":"sales_have_manager_names"}]},"sale_has_salesperson_name":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.salesperson_name":{"Target":{"Entity":"sale.salesperson_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.salesperson_name"}},"State":"Generated","Weight":0.99,"ID":"sales_have_salesperson_names"}]},"sale_has_customer_region":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_region":{"Target":{"Entity":"sale.customer_region"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.customer_region"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customer_regions"}]},"sale_has_customer_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_city":{"Target":{"Entity":"sale.customer_city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.customer_city"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customer_cities"}]},"sale_has_customer_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_country":{"Target":{"Entity":"sale.customer_country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.customer_country"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customer_countries"}]},"sale_has_customer_type":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_type":{"Target":{"Entity":"sale.customer_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.customer_type"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customer_types"}]},"sale_has_customer_name":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_name":{"Target":{"Entity":"sale.customer_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.customer_name"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customer_names"}]},"sale_has_order_time":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.order_time":{"Target":{"Entity":"sale.order_time"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.order_time"}},"State":"Generated","Weight":0.99,"ID":"sales_have_order_times"}]},"sale_has_order_date":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.order_date":{"Target":{"Entity":"sale.order_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.order_date"}},"State":"Generated","Weight":0.99,"ID":"sales_have_order_dates"}]},"sale_has_invoice_number":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.invoice_number":{"Target":{"Entity":"sale.invoice_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.invoice_number"}},"State":"Generated","Weight":0.99,"ID":"sales_have_invoice_numbers"}]},"sale_has_order_id":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.order_id":{"Target":{"Entity":"sale.order_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.order_id"}},"State":"Generated","Weight":0.99,"ID":"sales_have_order_ids"}]},"sale_has_all_measure_gross_profit":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.gross_profit":{"Target":{"Entity":"all_measure.gross_profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.gross_profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_gross_profit"}]},"sale_has_all_measure_total_revenue":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.total_revenue":{"Target":{"Entity":"all_measure.total_revenue"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.total_revenue"}},"State":"Generated","Weight":0.99,"ID":"sales_have_total_revenue"}]},"calendar_has_date":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.date":{"Target":{"Entity":"calendar.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.date"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_dates"}]},"sale_in_billing_address":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.billing_address":{"Target":{"Entity":"sale.billing_address"}}},"SemanticSlots":{"Where":{"Role":"sale.billing_address"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.billing_address"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_billing_addresses"}]},"sale_in_shipping_address":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_address":{"Target":{"Entity":"sale.shipping_address"}}},"SemanticSlots":{"Where":{"Role":"sale.shipping_address"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.shipping_address"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_shipping_addresses"}]},"salesperson_in_all_measure_unitsrevenueprofit_region__country_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.unitsrevenueprofit_region__country_title":{"Target":{"Entity":"all_measure.unitsrevenueprofit_region__country_title"}}},"SemanticSlots":{"Where":{"Role":"all_measure.unitsrevenueprofit_region__country_title"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"salesperson"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"all_measure.unitsrevenueprofit_region__country_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_are_in_unitsrevenueprofit_region__country_title"}]},"dynamic_rev_unit_prof_line_in_all_measure_unitsrevenueprofit_region__country_title":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line"},"State":"Generated","Roles":{"dynamic_rev_unit_prof_line":{"Target":{"Entity":"dynamic_rev_unit_prof_line"}},"all_measure.unitsrevenueprofit_region__country_title":{"Target":{"Entity":"all_measure.unitsrevenueprofit_region__country_title"}}},"SemanticSlots":{"Where":{"Role":"all_measure.unitsrevenueprofit_region__country_title"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"dynamic_rev_unit_prof_line"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"all_measure.unitsrevenueprofit_region__country_title"}},"State":"Generated","Weight":0.99,"ID":"dynamic_rev_unit_prof_lines_are_in_unitsrevenueprofit_region__country_title"}]},"salesperson_in_all_measure_region__country_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.region__country_title":{"Target":{"Entity":"all_measure.region__country_title"}}},"SemanticSlots":{"Where":{"Role":"all_measure.region__country_title"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"salesperson"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"all_measure.region__country_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_are_in_region__country_title"}]},"salesperson_in_all_measure_top_performing_region__country_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.top_performing_region__country_title":{"Target":{"Entity":"all_measure.top_performing_region__country_title"}}},"SemanticSlots":{"Where":{"Role":"all_measure.top_performing_region__country_title"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"salesperson"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"all_measure.top_performing_region__country_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_are_in_top_performing_region__country_title"}]},"manager_in_city":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.city":{"Target":{"Entity":"manager.city"}}},"SemanticSlots":{"Where":{"Role":"manager.city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"manager"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"manager.city"}},"State":"Generated","Weight":0.99,"ID":"managers_are_in_cities"}]},"manager_in_country":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.country":{"Target":{"Entity":"manager.country"}}},"SemanticSlots":{"Where":{"Role":"manager.country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"manager"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"manager.country"}},"State":"Generated","Weight":0.99,"ID":"managers_are_in_countries"}]},"manager_in_region":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.region":{"Target":{"Entity":"manager.region"}}},"SemanticSlots":{"Where":{"Role":"manager.region"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"manager"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"manager.region"}},"State":"Generated","Weight":0.99,"ID":"managers_are_in_regions"}]},"salesperson_in_city":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.city":{"Target":{"Entity":"salesperson.city"}}},"SemanticSlots":{"Where":{"Role":"salesperson.city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"salesperson"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"salesperson.city"}},"State":"Generated","Weight":0.99,"ID":"salespeople_are_in_cities"}]},"salesperson_in_country":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.country":{"Target":{"Entity":"salesperson.country"}}},"SemanticSlots":{"Where":{"Role":"salesperson.country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"salesperson"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"salesperson.country"}},"State":"Generated","Weight":0.99,"ID":"salespeople_are_in_countries"}]},"salesperson_in_region":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.region":{"Target":{"Entity":"salesperson.region"}}},"SemanticSlots":{"Where":{"Role":"salesperson.region"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"salesperson"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"salesperson.region"}},"State":"Generated","Weight":0.99,"ID":"salespeople_are_in_regions"}]},"customer_in_country":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.country":{"Target":{"Entity":"customer.country"}}},"SemanticSlots":{"Where":{"Role":"customer.country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"customer"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"customer.country"}},"State":"Generated","Weight":0.99,"ID":"customers_are_in_countries"}]},"customer_in_region":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.region":{"Target":{"Entity":"customer.region"}}},"SemanticSlots":{"Where":{"Role":"customer.region"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"customer"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"customer.region"}},"State":"Generated","Weight":0.99,"ID":"customers_are_in_regions"}]},"customer_in_city":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.city":{"Target":{"Entity":"customer.city"}}},"SemanticSlots":{"Where":{"Role":"customer.city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"customer"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"customer.city"}},"State":"Generated","Weight":0.99,"ID":"customers_are_in_cities"}]},"customer_in_address":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"customer.address":{"Target":{"Entity":"customer.address"}}},"SemanticSlots":{"Where":{"Role":"customer.address"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"customer"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"customer.address"}},"State":"Generated","Weight":0.99,"ID":"customers_are_in_addresses"}]},"sale_in_billing_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.billing_country":{"Target":{"Entity":"sale.billing_country"}}},"SemanticSlots":{"Where":{"Role":"sale.billing_country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.billing_country"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_billing_countries"}]},"sale_in_billing_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.billing_city":{"Target":{"Entity":"sale.billing_city"}}},"SemanticSlots":{"Where":{"Role":"sale.billing_city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.billing_city"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_billing_cities"}]},"sale_in_shipping_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_country":{"Target":{"Entity":"sale.shipping_country"}}},"SemanticSlots":{"Where":{"Role":"sale.shipping_country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.shipping_country"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_shipping_countries"}]},"sale_in_shipping_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_city":{"Target":{"Entity":"sale.shipping_city"}}},"SemanticSlots":{"Where":{"Role":"sale.shipping_city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.shipping_city"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_shipping_cities"}]},"sale_in_sales_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sales_city":{"Target":{"Entity":"sale.sales_city"}}},"SemanticSlots":{"Where":{"Role":"sale.sales_city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.sales_city"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_sales_cities"}]},"sale_in_sales_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sales_country":{"Target":{"Entity":"sale.sales_country"}}},"SemanticSlots":{"Where":{"Role":"sale.sales_country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.sales_country"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_sales_countries"}]},"sale_in_sales_region":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sales_region":{"Target":{"Entity":"sale.sales_region"}}},"SemanticSlots":{"Where":{"Role":"sale.sales_region"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.sales_region"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_sales_regions"}]},"sale_in_customer_region":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_region":{"Target":{"Entity":"sale.customer_region"}}},"SemanticSlots":{"Where":{"Role":"sale.customer_region"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.customer_region"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_customer_regions"}]},"sale_in_customer_city":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_city":{"Target":{"Entity":"sale.customer_city"}}},"SemanticSlots":{"Where":{"Role":"sale.customer_city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.customer_city"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_customer_cities"}]},"sale_in_customer_country":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.customer_country":{"Target":{"Entity":"sale.customer_country"}}},"SemanticSlots":{"Where":{"Role":"sale.customer_country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"sale.customer_country"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_customer_countries"}]},"manager_is_hired_on_hire_date":{"Binding":{"ConceptualEntity":"managers"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"manager.hire_date":{"Target":{"Entity":"manager.hire_date"}}},"SemanticSlots":{"When":{"Role":"manager.hire_date"}},"Phrasings":[{"Verb":{"Verbs":[{"hire":{"State":"Generated"}}],"Object":{"Role":"manager"}},"State":"Generated","Weight":0.9,"ID":"managers_are_hired_on_hire_dates"}]},"salesperson_is_hired_on_hire_date":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"salesperson.hire_date":{"Target":{"Entity":"salesperson.hire_date"}}},"SemanticSlots":{"When":{"Role":"salesperson.hire_date"}},"Phrasings":[{"Verb":{"Verbs":[{"hire":{"State":"Generated"}}],"Object":{"Role":"salesperson"}},"State":"Generated","Weight":0.9,"ID":"salespeople_are_hired_on_hire_dates"}]},"sales_item_is_ordered_on_order_date":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.order_date":{"Target":{"Entity":"sales_item.order_date"}}},"SemanticSlots":{"When":{"Role":"sales_item.order_date"}},"Phrasings":[{"Verb":{"Verbs":[{"order":{"State":"Generated"}}],"Object":{"Role":"sales_item"}},"State":"Generated","Weight":0.9,"ID":"sales_items_are_ordered_on_order_dates"}]},"sale_is_estimated_on_estimated_delivery":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.estimated_delivery":{"Target":{"Entity":"sale.estimated_delivery"}}},"SemanticSlots":{"When":{"Role":"sale.estimated_delivery"}},"Phrasings":[{"Verb":{"Verbs":[{"estimate":{"State":"Generated"}}],"Object":{"Role":"sale"}},"State":"Generated","Weight":0.9,"ID":"sales_are_estimated_on_estimated_deliveries"}]},"sale_is_shipped_on_ship_date":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.ship_date":{"Target":{"Entity":"sale.ship_date"}}},"SemanticSlots":{"When":{"Role":"sale.ship_date"}},"Phrasings":[{"Verb":{"Verbs":[{"ship":{"State":"Generated"}}],"Object":{"Role":"sale"}},"State":"Generated","Weight":0.9,"ID":"sales_are_shipped_on_ship_dates"}]},"sale_is_ordered_on_order_time":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.order_time":{"Target":{"Entity":"sale.order_time"}}},"SemanticSlots":{"When":{"Role":"sale.order_time"}},"Phrasings":[{"Verb":{"Verbs":[{"order":{"State":"Generated"}}],"Object":{"Role":"sale"}},"State":"Generated","Weight":0.9,"ID":"sales_are_ordered_on_order_times"}]},"sale_is_ordered_on_order_date":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.order_date":{"Target":{"Entity":"sale.order_date"}}},"SemanticSlots":{"When":{"Role":"sale.order_date"}},"Phrasings":[{"Verb":{"Verbs":[{"order":{"State":"Generated"}}],"Object":{"Role":"sale"}},"State":"Generated","Weight":0.9,"ID":"sales_are_ordered_on_order_dates"}]},"sale_is_return_requested":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.return_requested":{"Target":{"Entity":"sale.return_requested"}}},"Conditions":[{"Target":{"Role":"sale.return_requested"},"Operator":"Equals","Value":{"Boolean":[true]}}],"Phrasings":[{"Adjective":{"Subject":{"Role":"sale"},"Adjectives":[{"return requested":{"State":"Generated"}},{"return-requested":{"State":"Generated"}}]},"State":"Generated","Weight":0.99,"ID":"some_sales_are_return_requested_sales"}]},"manager_manage_sale":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"manager":{"Target":{"Entity":"manager"}},"sale":{"Target":{"Entity":"sale"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"manager"},"Verbs":[{"manage":{"State":"Generated"}}],"Object":{"Role":"sale"}},"State":"Generated","Weight":0.75,"ID":"managers_manage_sales"},{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"manager"}},"State":"Generated","Weight":0.99,"ID":"sales_have_managers"},{"Attribute":{"Subject":{"Role":"manager"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"managers_have_sales"}]},"dynamic_rev_unit_prof_line_is_named_dynamic_rev_unit_prof_line":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line"},"State":"Generated","Roles":{"dynamic_rev_unit_prof_line":{"Target":{"Entity":"dynamic_rev_unit_prof_line"}},"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line":{"Target":{"Entity":"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line"}}},"Phrasings":[{"Name":{"Subject":{"Role":"dynamic_rev_unit_prof_line"},"Name":{"Role":"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line"}},"State":"Generated","Weight":0.99,"ID":"dynamic_rev_unit_prof_lines_are_names_IDs_of_dynamic_rev_unit_prof_lines"},{"Attribute":{"Subject":{"Role":"dynamic_rev_unit_prof_line"},"Object":{"Role":"dynamic_rev_unit_prof_line.dynamic_rev_unit_prof_line"}},"State":"Generated","Weight":0.99,"ID":"dynamic_rev_unit_prof_lines_have_dynamic_rev_unit_prof_lines"}]},"sale_has_all_measure_increase___decrease_revenue_goal":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.increase___decrease_revenue_goal":{"Target":{"Entity":"all_measure.increase___decrease_revenue_goal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.increase___decrease_revenue_goal"}},"State":"Generated","Weight":0.99,"ID":"sales_have_increase___decrease_revenue_goal"}]},"measure_selection_has_all_measure_dynamic_line_value":{"Binding":{"ConceptualEntity":"Measure Selection"},"State":"Generated","Roles":{"measure_selection":{"Target":{"Entity":"measure_selection"}},"all_measure.dynamic_line_value":{"Target":{"Entity":"all_measure.dynamic_line_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"measure_selection"},"Object":{"Role":"all_measure.dynamic_line_value"}},"State":"Generated","Weight":0.99,"ID":"measure_selections_have_dynamic_line_value"}]},"sale_has_all_measure_dynamic_line_value":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.dynamic_line_value":{"Target":{"Entity":"all_measure.dynamic_line_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.dynamic_line_value"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dynamic_line_value"}]},"dynamic_rev_unit_prof_line_has_all_measure_unitsrevenueprofit_region__country_title":{"Binding":{"ConceptualEntity":"Dynamic Rev, Unit, Prof, Line"},"State":"Generated","Roles":{"dynamic_rev_unit_prof_line":{"Target":{"Entity":"dynamic_rev_unit_prof_line"}},"all_measure.unitsrevenueprofit_region__country_title":{"Target":{"Entity":"all_measure.unitsrevenueprofit_region__country_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dynamic_rev_unit_prof_line"},"Object":{"Role":"all_measure.unitsrevenueprofit_region__country_title"}},"State":"Generated","Weight":0.99,"ID":"dynamic_rev_unit_prof_lines_have_unitsrevenueprofit_region__country_title"}]},"salesperson_has_all_measure_unitsrevenueprofit_region__country_title":{"Binding":{"ConceptualEntity":"salespeople"},"State":"Generated","Roles":{"salesperson":{"Target":{"Entity":"salesperson"}},"all_measure.unitsrevenueprofit_region__country_title":{"Target":{"Entity":"all_measure.unitsrevenueprofit_region__country_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"all_measure.unitsrevenueprofit_region__country_title"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_unitsrevenueprofit_region__country_title"}]},"sale_has_all_measure_last_purchase_date":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.last_purchase_date":{"Target":{"Entity":"all_measure.last_purchase_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.last_purchase_date"}},"State":"Generated","Weight":0.99,"ID":"sales_have_last_purchase_date"}]},"revenue_goal_has_revenue_goal":{"Binding":{"ConceptualEntity":"Revenue Goal"},"State":"Generated","Roles":{"revenue_goal":{"Target":{"Entity":"revenue_goal"}},"revenue_goal.revenue_goal":{"Target":{"Entity":"revenue_goal.revenue_goal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"revenue_goal"},"Object":{"Role":"revenue_goal.revenue_goal"}},"State":"Generated","Weight":0.99,"ID":"revenue_goals_have_revenue_goals"}]},"revenue_goal_has_revenue_goal_value":{"Binding":{"ConceptualEntity":"Revenue Goal"},"State":"Generated","Roles":{"revenue_goal":{"Target":{"Entity":"revenue_goal"}},"revenue_goal.revenue_goal_value":{"Target":{"Entity":"revenue_goal.revenue_goal_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"revenue_goal"},"Object":{"Role":"revenue_goal.revenue_goal_value"}},"State":"Generated","Weight":0.99,"ID":"revenue_goals_have_revenue_goal_value"}]},"measure_selection_has_measure_name":{"Binding":{"ConceptualEntity":"Measure Selection"},"State":"Generated","Roles":{"measure_selection":{"Target":{"Entity":"measure_selection"}},"measure_selection.measure_name":{"Target":{"Entity":"measure_selection.measure_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"measure_selection"},"Object":{"Role":"measure_selection.measure_name"}},"State":"Generated","Weight":0.99,"ID":"measure_selections_have_measure_names"}]},"measure_selection_has_measure_order":{"Binding":{"ConceptualEntity":"Measure Selection"},"State":"Generated","Roles":{"measure_selection":{"Target":{"Entity":"measure_selection"}},"measure_selection.measure_order":{"Target":{"Entity":"measure_selection.measure_order"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"measure_selection"},"Object":{"Role":"measure_selection.measure_order"}},"State":"Generated","Weight":0.99,"ID":"measure_selections_have_measure_orders"}]},"all_measure_has_purchase_recency":{"Binding":{"ConceptualEntity":"All Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.purchase_recency":{"Target":{"Entity":"all_measure.purchase_recency"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.purchase_recency"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_purchase_recency"}]},"sale_has_all_measure_purchase_frequency":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.purchase_frequency":{"Target":{"Entity":"all_measure.purchase_frequency"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.purchase_frequency"}},"State":"Generated","Weight":0.99,"ID":"sales_have_purchase_frequency"}]},"customer_has_all_measure_churned_customers":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"all_measure.churned_customers":{"Target":{"Entity":"all_measure.churned_customers"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"all_measure.churned_customers"}},"State":"Generated","Weight":0.99,"ID":"customers_have_churned_customers"}]},"customer_has_all_measure_churned_rate":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"all_measure.churned_rate":{"Target":{"Entity":"all_measure.churned_rate"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"all_measure.churned_rate"}},"State":"Generated","Weight":0.99,"ID":"customers_have_churned_rate"}]},"customer_has_all_measure_repeat_purchases":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"all_measure.repeat_purchases":{"Target":{"Entity":"all_measure.repeat_purchases"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"all_measure.repeat_purchases"}},"State":"Generated","Weight":0.99,"ID":"customers_have_repeat_purchases"}]},"calendar_has_all_measure_selected_periods_titles":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.selected_periods_titles":{"Target":{"Entity":"all_measure.selected_periods_titles"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.selected_periods_titles"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_selected_periods_titles"}]},"churn_period_has_label":{"Binding":{"ConceptualEntity":"Churn Period"},"State":"Generated","Roles":{"churn_period":{"Target":{"Entity":"churn_period"}},"churn_period.label":{"Target":{"Entity":"churn_period.label"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"churn_period"},"Object":{"Role":"churn_period.label"}},"State":"Generated","Weight":0.99,"ID":"churn_periods_have_labels"}]},"churn_period_has_value":{"Binding":{"ConceptualEntity":"Churn Period"},"State":"Generated","Roles":{"churn_period":{"Target":{"Entity":"churn_period"}},"churn_period.value":{"Target":{"Entity":"churn_period.value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"churn_period"},"Object":{"Role":"churn_period.value"}},"State":"Generated","Weight":0.99,"ID":"churn_periods_have_values"}]},"sale_has_all_measure_revenue_share":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.revenue_share":{"Target":{"Entity":"all_measure.revenue_share"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.revenue_share"}},"State":"Generated","Weight":0.99,"ID":"sales_have__revenue_share"}]},"refresh_timestamp_has_all_measure_last_refresh_PQ":{"Binding":{"ConceptualEntity":"Refresh Timestamp"},"State":"Generated","Roles":{"refresh_timestamp":{"Target":{"Entity":"refresh_timestamp"}},"all_measure.last_refresh_PQ":{"Target":{"Entity":"all_measure.last_refresh_PQ"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"refresh_timestamp"},"Object":{"Role":"all_measure.last_refresh_PQ"}},"State":"Generated","Weight":0.99,"ID":"refresh_timestamps_have_last_refresh_PQ"}]},"refresh_timestamp_has_refresh_timestamp":{"Binding":{"ConceptualEntity":"Refresh Timestamp"},"State":"Generated","Roles":{"refresh_timestamp":{"Target":{"Entity":"refresh_timestamp"}},"refresh_timestamp.refresh_timestamp":{"Target":{"Entity":"refresh_timestamp.refresh_timestamp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"refresh_timestamp"},"Object":{"Role":"refresh_timestamp.refresh_timestamp"}},"State":"Generated","Weight":0.99,"ID":"refresh_timestamps_have_refresh_timestamps"}]},"sale_has_all_measure_previous_year_units_sold_color":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.previous_year_units_sold_color":{"Target":{"Entity":"all_measure.previous_year_units_sold_color"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.previous_year_units_sold_color"}},"State":"Generated","Weight":0.99,"ID":"sales_have__previous_year_units_sold_color"}]},"sale_has_shipping_address":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.shipping_address":{"Target":{"Entity":"sale.shipping_address"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.shipping_address"}},"State":"Generated","Weight":0.99,"ID":"sales_have_shipping_addresses"}]},"sale_has_billing_address":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.billing_address":{"Target":{"Entity":"sale.billing_address"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.billing_address"}},"State":"Generated","Weight":0.99,"ID":"sales_have_billing_addresses"}]},"sale_has_return_requested":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.return_requested":{"Target":{"Entity":"sale.return_requested"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.return_requested"}},"State":"Generated","Weight":0.99,"ID":"sales_have_return_requested"}]},"sale_has_tracking_number":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.tracking_number":{"Target":{"Entity":"sale.tracking_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.tracking_number"}},"State":"Generated","Weight":0.99,"ID":"sales_have_tracking_numbers"}]},"sales_item_has_barcode":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"sales_item.barcode":{"Target":{"Entity":"sales_item.barcode"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"sales_item.barcode"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_barcodes"}]},"calendar_has_all_measure_dynamic_tooltip_title":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"all_measure.dynamic_tooltip_title":{"Target":{"Entity":"all_measure.dynamic_tooltip_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"all_measure.dynamic_tooltip_title"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_dynamic_tooltip_title"}]},"sale_has_all_measure_dynamic_tooltip_title":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.dynamic_tooltip_title":{"Target":{"Entity":"all_measure.dynamic_tooltip_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.dynamic_tooltip_title"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dynamic_tooltip_title"}]},"customer_has_all_measure_customers_bought":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"all_measure.customers_bought":{"Target":{"Entity":"all_measure.customers_bought"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"all_measure.customers_bought"}},"State":"Generated","Weight":0.99,"ID":"customers_have_customers_bought"}]},"sale_has_all_measure_customers_bought":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.customers_bought":{"Target":{"Entity":"all_measure.customers_bought"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.customers_bought"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customers_bought"}]},"sale_has_all_measure_customers_bought_this_month":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"all_measure.customers_bought_this_month":{"Target":{"Entity":"all_measure.customers_bought_this_month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"all_measure.customers_bought_this_month"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customers_bought_this_month"}]},"sale_has_customer":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"customer":{"Target":{"Entity":"customer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"customer"}},"State":"Generated","Weight":0.99,"ID":"sales_have_customers"},{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"customers_have_sales"}]},"sale_has_salesperson":{"Binding":{"ConceptualEntity":"sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"salesperson":{"Target":{"Entity":"salesperson"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"salesperson"}},"State":"Generated","Weight":0.99,"ID":"sales_have_salespeople"},{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_sales"}]},"sales_item_has_customer":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"customer":{"Target":{"Entity":"customer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"customer"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_customers"},{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"sales_item"}},"State":"Generated","Weight":0.99,"ID":"customers_have_sales_items"}]},"sales_item_has_product":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"product":{"Target":{"Entity":"product"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"product"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_products"},{"Attribute":{"Subject":{"Role":"product"},"Object":{"Role":"sales_item"}},"State":"Generated","Weight":0.99,"ID":"products_have_sales_items"}]},"sales_item_has_salesperson":{"Binding":{"ConceptualEntity":"sales_items"},"State":"Generated","Roles":{"sales_item":{"Target":{"Entity":"sales_item"}},"salesperson":{"Target":{"Entity":"salesperson"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sales_item"},"Object":{"Role":"salesperson"}},"State":"Generated","Weight":0.99,"ID":"sales_items_have_salespeople"},{"Attribute":{"Subject":{"Role":"salesperson"},"Object":{"Role":"sales_item"}},"State":"Generated","Weight":0.99,"ID":"salespeople_have_sales_items"}]},"customer_has_calendar":{"Binding":{"ConceptualEntity":"customers"},"State":"Generated","Roles":{"customer":{"Target":{"Entity":"customer"}},"calendar":{"Target":{"Entity":"calendar"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"customer"},"Object":{"Role":"calendar"}},"State":"Generated","Weight":0.99,"ID":"customers_have_calendars"},{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"customer"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_customers"}]}},"Agents":{"Internal":{"Version":"1.1.0"}}}
				contentType: json

		expression 'Country Colors' =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Rafael\Documents\GitHub\Big Inventory Data\Country Colors.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"
			lineageTag: 491dd6eb-ed90-4797-b399-10d1c3226009

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["sales","sales_items","products","customers","salespeople","managers","All Measures","Country Colors","Refresh Timestamp"]

		annotation PBI_ProTooling = ["DevMode"]

		annotation __TEdtr = 1

